### ISSUE TITLE
Range widget UI issues

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1023]
The range widgets don't look great currently...

The slider bar is too wide, strong color, and the handle is small:
![image](https://user-images.githubusercontent.com/193367/99810348-e33a8b00-2b43-11eb-9378-a6aa744cc249.png)

The +/- buttons are very narrow:
![image](https://user-images.githubusercontent.com/193367/99809105-1da32880-2b42-11eb-8b26-bcc134930e16.png)

For slider we could use an appearance similar to this (maybe with smaller handle):
![image](https://ivomynttinen.com/content/3-blog/20150928-ios-design-guidelines/ios-slider.jpg)

**Comment by tomasMizera** [comment]
Background of +/- range widget should also have the same color as other widgets
