### ISSUE TITLE
value relation multiple selection not working

### ISSUE THREAD

**Issue by ocelot73** [lutraconsulting/input#1024]
Even of allow multiple selection Is ticket inside qgis attribuite form widget for value relation, latest input app for android shows a list of valide but only one can be selected.
I've experienced this issue pointing to a postgres table in qgis value relation widget

**Comment by saberraz** [comment]
What version of Input are you using? This  issue has been addressed https://github.com/lutraconsulting/input/issues/741 and will be available in the next release soon.

You can try one of the builds to test the upcoming feature, but we are still working on a couple of issues:
https://www.dropbox.com/s/jpiaijsdypqau6a/input-master-840647ab9942b88eb8447e75f3914fbc4a433d47-arm64-v8a-signed.apk?dl=0

**Comment by ocelot73** [comment]
Used INPUT version 0.7.0
