### ISSUE TITLE
Scan folders under Input on sdcard for projects

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#103]
Currently, the projects are all located under Input folder on sdcard. When you have multiple projects, with photos and different layers, it becomes very difficult to pick the fetch the right data.

maybe we can use folders to store each project and its dependencies.

**Comment by wonder-sk** [comment]
That already should be the case that Input also looks into sub-directories.

**Comment by saberraz** [comment]
Ahhh...coool.
I close this then.
