### ISSUE TITLE
Refactor form-related models

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1035]
There are several models linked together making things quite complex - and buggy in some more advanced scenarios, e.g. when using conditional visibility. It would be good to simplify the whole approach - maybe something like this:

- do not link models together - e.g. the dreaded QgsQuickSubModel
- use just simple list models (not hierarchical)
- have one central controller class for all the form logic to avoid spaghetti of signals
- remove QgsQuickAttributeModel if possible - if we don't need that item model then let's keep the logic in the central controller

![image](https://user-images.githubusercontent.com/193367/100242571-4148e300-2f35-11eb-90b9-9745f1eb8f18.png)

**Comment by PeterPetrik** [comment]
+1

**Comment by saberraz** [comment]
Related to #1011
