### ISSUE TITLE
Use paginated endpoint to list projects

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1043]
Let's use the newly available API endpoint that limits number of returned projects (the existing endpoint will be removed).

The new request should look like this:

`https://public.cloudmergin.com/v1/project/paginated?page=1&per_page=50`

The request returns also the total count, so we know if we may need to get more pages or not.

To make things simple, I would suggest that if count is more than the number of items we already have, at the bottom of the list there would be a button "Load more projects" that would fetch another 50 projects and append them to the current list.

**Comment by sklencar** [comment]
Just additional remark: By implementing paging for fetching list of projects, it is not only shorten waiting time, but also fix following issue:

**Issue: Overwritten project list**
Story:
I takes a while when Input is fetching many projects (for instance by opening explore project page). By sending second projects request in a meanwhile which is finished sooner as the first one, list of project is firstly updated with the second request's reply, then is updated again with the first request's reply. **Therefore list of project can be overwritten by earlier request.**

How to duplicate:
* Open Input and go to project page
* Try to open "Explore" public projects (expecting late reply)
* Immediately after try to open either your or shared with you project page (expecting fast reply)
