### ISSUE TITLE
Crash when opening the NAD83 UTM project

### ISSUE THREAD

**Issue by edips** [lutraconsulting/input#1049]
The project works on Input 0.6.2 without crash but it doesn't work for versions 0.7.0 and 0.7.2. This project opens first time without problem, when I open Input again, it clashes on armv8 device. I also tested 0.7.0 version on armv7 device, this project never opened and crashed. I sent crash report with Android. The crash report is very long, I couldn't copy paste. There is some meaningful keywords in the report:
```
Abroad message: 'terminating with uncaught exception of type QgsCsException'
'/lib/arm64/libqgis_core_arm64-v8a.so (QgsCoordinateTransform::TransformDirection) const 172)'
/lib/arm64/libqgs_quickarm64-v8a.so (QgsQuickUtils::transformPoint(QgsCoordinateReferenceSystem const&, QgsCoordinateReferenceSysyem const&, QgsCoordinateTransformContext const&, QgsPointXY const&)+76)
(QgsQuickPositionKit::updateProjectedPosition()+124)
 (QgsQuickPositionKit::onMapSettingsUpdated()+124)
QgsQuickMapSettings::onReadProject(QDomDocument const&)+552
QgsProject::readProjectFile(QDomDocument const&)
QgsProject::readProjectFile(QString const&, QFlags<QgsProject::ReadFlag>)
Loader::forceLoad(QString const&, bool)
(Loader::qt_metacall(QMetaObject(QMetaObject::Call, int; void**)))
```

I compiled Input Master with Qt Creator. this project works without crash on Ubuntu but it crashes on Android. This project worked on Android when I disabled initialization of proj. I think there will be problem about coordinate system without initialization of Proj library. Other projects work without problem.

[contours.zip](https://github.com/lutraconsulting/input/files/5635757/contours.zip)

**Comment by saberraz** [comment]
Indeed, I am experiencing the same issue.

**Comment by PeterPetrik** [comment]
test project; https://public.cloudmergin.com/projects/lutraconsulting/test_grid_shift

**Comment by PeterPetrik** [comment]
probably fixed by https://github.com/qgis/QGIS/pull/40482

**Comment by edips** [comment]
When disabling [mapSettings: mapCanvas.mapSettings](https://github.com/lutraconsulting/input/blob/567db35aa095d3ad86a4bf7f0912f087eb5f3120/app/qml/main.qml#L387) in main.qml, grid shift projects can work on Android 10 without crash. There may be problem about QgsQuickPositioningKit class. If I am able to convert WGS84 to project's coordinate system, I will try to use Qt Quick Positioning plugin instead of QgsQuickPositioningKit. It may be an alternative.

**Comment by saberraz** [comment]
could you try one of the latest APKs from this PR #1051

**Comment by edips** [comment]
@saberraz I tried this one, Input opens the grid shift first but when I open the app again, it suddenly closes like before.
