### ISSUE TITLE
Overwritten project list [handling parallel requests]

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1050]
I takes a while when Input is fetching many projects (for instance by opening explore project page). By sending second projects request in a meanwhile which is finished sooner as the first one, list of project is firstly updated with the second request's reply, then is updated again with the first request's reply. Therefore list of project can be overwritten by earlier request.

The chance to encounter the problem in regular Input use is lowered by #1043. Technically it is still present since parallel requests can be still sent and handled separately, but results are shown on a single page/view.

How to duplicate:
- Open Input and go to project page
- Try to open "Explore" public projects (expecting late reply)
- Immediately try to open either your or shared with you project page (expecting fast reply)

**Comment by tomasMizera** [comment]
This bug occurs regularly on places outside city where requests take a longer time. I experience this issue even when clicking between `My projects` and `Shared with me`
