### ISSUE TITLE
Some items seem to have small clickable area

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1054]
For example, today when testing I had issues tapping some buttons:
- switches in settings
- left/right arrows in settings
- back button in multiple pages

Extending their active mouse area would probably help

**Comment by tomasMizera** [comment]
@wonder-sk Do you have any specific pages in mind that has small back button clickable area?

**Comment by wonder-sk** [comment]
I would have thought that all pages have this problem - e.g. Settings page just to name one :-)
