### ISSUE TITLE
*Image not available* seen when taking photos on iOS

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#1056]
Please ask me for access to the project to recreate this issue.  Ideally please clone the project as it's being used in production.

So to reproduce:

- Using iOS / iPhone
- Take a new survey point and add a photo (the form will display *Image not available*
- Sync the project
- Look at it in QGIS - the photo has been synced properly (cannot remember whether the path is right but it's there)
- When you look at the surveyed point in Input, you can only see the error *Image not available*

Please note that the photos must be stored in the subfolder seen in the project.

Pete

**Comment by PeterPetrik** [comment]
This is tested regularly and working
