### ISSUE TITLE
Unable to open project without any editable layers

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1063]
It is impossible to use EPSG:2959. Input crashes everytime trying to open the project.

See: https://public.cloudmergin.com/projects/saber/crash

**Comment by PeterPetrik** [comment]
works on 0.7.0, works on 0.7.2, crashes on 0.7.3 (diff https://github.com/lutraconsulting/input/compare/0.7.2...0.7.3)

**Comment by PeterPetrik** [comment]
this is a regression caused by https://github.com/lutraconsulting/input/commit/34c3c3a2bbfd31dabfefaf2f2095f1329a3db921

looks like infinite loop/recursion where the crash message is not much helpful 
```
ActiveLayer::resetActiveLayer() emits activeLayerChanged( QString() );
main.qml::onActiveLayerChanged() (~line 486) calls main.qml::updateRecordToolbar(); 
main.qml::updateRecordToolbar() calls __loader.setActiveLayer()
Loader::setActiveLayer calls  mActiveLayer.resetActiveLayer();
```
