### ISSUE TITLE
Taking picture via camera or adding image from gallery not working for existing app

### ISSUE THREAD

**Issue by ghillert** [lutraconsulting/input#1064]
I am running into a weird problem with an existing Input app (On Android 11). After a recent update of Input, I can no longer take pictures from within the app or add pictures from the gallery from within the app.

Actually, the camera app opens, I take the picture - but then the picture is not added to the app. I cannot add the picture via the gallery either. While the Gallery app opened and I can select a picture it is never added to the app's form.

If I create a brand new app, it works. If I add a totally new layer to my pre-existing app, it does NOT work. I am just wondering if my QGIS app/project got somehow corrupted?

**Comment by PeterPetrik** [comment]
Hi, 

which Input version do you use (0.7.6 is the latest from the store)? Also, can you please specify what do you mean by "app" in the description
> If I create a brand new app, it works. If I add a totally new layer to my pre-existing app

Can you please send us a log from settings > diagnosis log and state the name here so we can investigate? 

Thanks a lot,
Peter

**Comment by ghillert** [comment]
Hi Peter,

I am using the latest app - `0.7.6` on Android `11`. Sorry by app I mean the Input app. I just submitted the diagnostic log. My name is `hillert`. I try to add a few pictures (From gallery and camera) but nothing happens. I did not see any additional entries in the diagnostic log as a result of those actions. My form is showing pre-existing pictures correctly and I was previously able to add new images for the same project (But that was with the old Input app that was not using the Camera app)

I just verified that the Android version has no impact - testing the same project with Input 0.7.6 on an old Android device (Android 6) - same issue.

Also, I wonder if my project got somehow corrupted. A brand-new project (where I create a form-field for an image as attachment) works fine. It is just frustrating that I don't see any error/warning.

**Comment by PeterPetrik** [comment]
Hi, 
yes I see the log, nothing unfortunately there. If you suggest that it is possible to add new images in the new project, it could be indeed some configuration issue (that changed between versions?)

Maybe you can read through https://help.inputapp.io/howto/project_config section "Attachement (External resource) widget" to see if there is something?

**Comment by ghillert** [comment]
Hi Peter,

Took me a while to get back to this and figure this thing out. I finally was able to get it to work. Looks like it was a path-issue which also affected the selection of images in _Input_. The setting of image (attachment) paths in _QGIS_ is not necessarily intuitive/fault-tolerant (e.g. even the trailing folder slash is critical). Nonetheless, this is now working with the following settings:

![image](https://user-images.githubusercontent.com/685363/110224697-f74f9180-7e81-11eb-831f-275e85e6d745.png)

`@project_home + '/images/'`

Not sure if this was a change in QGIS or Input, but previously I did not have to use the `@project_home` variable to make this work.

I wonder if you could add some better validation logic / error reporting in Input. Selecting an images / taking a picture via the camera and "nothing happens" is a bit annoying.

**Comment by saberraz** [comment]
@ghillert I believe this is working. Best to add more note on documentation and plugin when packaging the project.
