### ISSUE TITLE
Better quota error message in Input

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#1089]
When someone tries to push a 20MB sync when their quota is 90/100MB, they get a message like this:

"You have reached your storage limit" <- not exact message text

This confuses users - better would be something like:

_**Could not push changes**_
_Pushing these changes would put your account over its current storage limit of 100MB. Please subscribe to a plan to increase your storage limit._

If the current message can be triggered by different scenarios, then perhaps it would be good to list common solutions, such as _Could not upload changes (20MB) please check: (1) the target project has enough free space, (2) something else, (3), bla bla_

**Comment by saberraz** [comment]
This issue is now resolved with a more verbose message and link to update the plan.
