### ISSUE TITLE
Default value not applied ...

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1090]
when the value depends on another attribute value.

See the example project. It works in QGIS but not in Input:
When user adds a new point, the **value** column will be assigned the default value based on:
- The latest entry
- And the Sample value

[survey_default_value.zip](https://github.com/lutraconsulting/input/files/5801496/survey_default_value.zip)

**Comment by sklencar** [comment]
Input evaluate expressions differently, and not yet sure why. However, here are some findings how to fix the project:
Expression uses function `get_feature` which "Returns the first feature of a layer matching a given attribute value." It seems that Input somehow always returns current feature as the first one, therefore the field value cannot be set correctly from a "sample" feature.

Workaround - Use an attribute with unique values in `get_feature` to make sure that function returns exactly one (or none) feature. So, as an example using fid as an unique value attribute (or introduce a new one for the given project, eg. `sample_id`):
current expression: `attribute(get_feature('default_value', 'sample',"sample"), 'value')`
suggested expression: `attribute(get_feature('default_value', 'fid',"sample"), 'value')`
