### ISSUE TITLE
Add projects for manual tests

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1094]
Testers now need to look for or create projects for several test cases. This can eat up a lot of testing time. Create/link projects that can be used with test cases (all TCs that do not have one)

**Comment by jozef-budac** [comment]
I am upgrading the testcases on the way so in the future, all testcases will have its own dedicated project.

**Comment by jozef-budac** [comment]
Hopefully all TC have  it own dedicated project so closing this issue
