### ISSUE TITLE
Date Picker icon not clickable

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#1104]
IOS v0.7.8 - Using the 'Capturing Field data tour' - the date picker icon doesn't open the calendar (unlike up/down arrows for picklists). You need to click to the left of the icon to access the calendar widget.

**Comment by saberraz** [comment]
@mostlyAtNight could you have a look. It is not appearing at all for me.

**Comment by saberraz** [comment]
Related and duplicate of #1377
