### ISSUE TITLE
numeric keyboard issue for ios input

### ISSUE THREAD

**Issue by ocelot73** [lutraconsulting/input#1105]
After setting a qgis project for trees survey (only one file that read/writes data in a remore postgres/postgis db for trees survey), when trying to enter a tree's heigth/length/etc measure input v0.7.7 app for ios only shows a numeric keyboard with no comma or point soI'm not able to enter decimal numeric values (I have to manually insert decimal point in db)
It's not a matter of db column format because it happens both with double precision both with numeric types.
I think it's a v0.7.7 app issue for ios (app for android is working well)

**Comment by saberraz** [comment]
Do you know if this is reproducible with Geopackage?

**Comment by ocelot73** [comment]
No because I don't use geopackage format. I could try but I think it would be the same..I'll let you know as soon as I can

**Comment by ocelot73** [comment]
Just tested. the issue is reproducible with Geopackage, too (it appears a keyboard with only numbers, no comma or point for inserting decimal numbers)

**Comment by saberraz** [comment]
https://user-images.githubusercontent.com/2649047/105381726-380f8600-5c07-11eb-9fb8-a3806472770e.MP4

Hmm, it works fine for me. The . appears in the lower left corner.

**Comment by saberraz** [comment]
@ocelot73 could you clarify what language setting you use for your iOS system? This could be related to the system locale.

**Comment by saberraz** [comment]
This is replicate of #1395
