### ISSUE TITLE
'Value Map' Text Field recording incorrect NULL values

### ISSUE THREAD

**Issue by domhinch** [lutraconsulting/input#1108]
## Issue
NULL values in text fields are displaying incorrectly as strings in QGIS after surveying with Input.

![Screenshot 2021-01-21 174113](https://user-images.githubusercontent.com/63502520/105391983-91c97d80-5c12-11eb-9e42-5c25bb8204e0.png)

## Reproduction

1. Create GeoPackage in QGIS with text field.
2. Add attribute form styling as `'Value Map'` and `'Add "Null" Value'`.

  ![Screenshot 2021-01-21 174426](https://user-images.githubusercontent.com/63502520/105392339-000e4000-5c13-11eb-86c9-57eadf67a442.png)

3. Upload to Mergin & sync to device.
4. Take survey point selecting `<NULL>` for some points **OR** leaving fields blank (not selecting anything from dropdown).
5. When complete sync, download and view in QGIS.

## Scenarios

- `<NULL>` selected in Input --> string value `2839923c-8b7d-419e-b84b-ca2fe9b80ec7` in QGIS.
- No values selected from the dropdown --> correct *`NULL`* value in QGIS.

I tried setting up a GeoPackage without a `<NULL>` value option however, in Input, if you select a dropdown value and wish to 'cancel' (reset to NULL) there is no option to. The only way I can see is to delete the point and retake; making sure that you leave the dropdown well alone.

## Versions
GeoPackage created in QGIS 3.16.3
Input v0.7.8 on Android

**Comment by saberraz** [comment]
This appears to have been fixed. The values are correctly populated as NULL but it is displayed with some random string in the preview panel:
![image](https://user-images.githubusercontent.com/2649047/118138163-ea10cf00-b3fd-11eb-976e-7ba65016e28b.png)

But in the form, the correct value is populated (both for QGIS and Input).
![image](https://user-images.githubusercontent.com/2649047/118138276-090f6100-b3fe-11eb-98f3-1f891d3a3fcc.png)

**Comment by saberraz** [comment]
I'd say this is a minor bug and we can open another one. The behaviour is correct, it is just the displaying of the NULL value which is not correct.
