### ISSUE TITLE
Can’t delete example project

### ISSUE THREAD

**Issue by katagen** [lutraconsulting/input#1109]
Since the last update on iOS, the exemple projects « start here! » and « Capturing field data tour » are always present. I can delete them, but when I restart the app, they are here again!

**Comment by saberraz** [comment]
This is intentional for the time being. It will be optional in the future releases when we revamped the Home page.

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/input-manual-tests/issues/19 test A
