### ISSUE TITLE
When in landscape mode, unable to login to mergin

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#1114]
related to https://github.com/lutraconsulting/input/issues/933

the name and password is not visible at all and cannot scroll

![Screen Shot 2021-01-28 at 11 09 00](https://user-images.githubusercontent.com/804608/106122769-5ae6f080-6159-11eb-8f8c-c8a11319dc53.png)

**Comment by saberraz** [comment]
Duplicate of #1304
