### ISSUE TITLE
Translated it to Japanese language

### ISSUE THREAD

**Issue by JinIgarashi** [lutraconsulting/input#1121]
Hi, I have translated Input app to Japanese language in Transifex. I would like to check translations on test flight app. Could you build apk for checking?

**Comment by PeterPetrik** [comment]
Hi thank you very much for your efford. We are preparing for the release, and I have just updated the transifes sources with the final set of string to translate. Would you have time to fix those extra 20 new strings and I will prepare you APK afterwards?

**Comment by JinIgarashi** [comment]
Hi, Peter, thank you for the response. Yeah I will translate those additional one tomorrow.

**Comment by JinIgarashi** [comment]
Hi @PeterPetrik , I have translated additional one. Let me know if apk is ready. I will check my translations.

**Comment by JinIgarashi** [comment]
I have installed apk on this PR.
https://github.com/lutraconsulting/input/pull/1134

However, Japanese language was not enabled although version became v0.8.0.

**Comment by PeterPetrik** [comment]
Hi @JinIgarashi  try one of these https://github.com/lutraconsulting/input/commit/1a0deabfad209111c59cbda589a479b2c91998df

thanks!

**Comment by JinIgarashi** [comment]
Hi @PeterPetrik I tried that apk! Now everything became Japanese. However, I found two strings are too long, so I just modified in transifex for making those strings become shortly. I think now it is okey.

**Comment by PeterPetrik** [comment]
nice!

**Comment by JinIgarashi** [comment]
@PeterPetrik I have a suggestion. Is there a way to translate official documentation to Japanese language?

https://help.inputapp.io

Although I already translated [GIS OpenCourseWare's manual](https://courses.gisopencourseware.org/course/view.php?id=24) for Japanese users, but it is better to have official Japanese documentation like QField.

**Comment by saberraz** [comment]
hi @JinIgarashi thanks for your help with translation.

I have opened a ticket here:
https://github.com/lutraconsulting/input-docs/issues/20

Where we keep the documentation for Input.
