### ISSUE TITLE
App crash when adding new feature to a project created with wizard

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input#1126]
When doing tests https://github.com/lutraconsulting/input-manual-tests/issues/2 G.10 with Xiaomi Redmi Note Pro 8, after creating a new project with wizard, when trying to add a point the app crashed.

When opened again, I was able to succesfuly add a point though.

**Comment by tomasMizera** [comment]
Could not reproduce, probably related to #1035

**Comment by tomasMizera** [comment]
Another reproducible scenario:
 - open `saber\photo_survey`
 - Download lutraconsulting\test_exif
 - Add a point

https://github.com/lutraconsulting/input/issues/1306

**Comment by saberraz** [comment]
I cannot reproduce the issue. Please re-open if it resurfaces.
