### ISSUE TITLE
Value relation widget - can't set value other than the first from available values

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input#1128]
When on tests lutraconsulting/input-manual-tests#25 and https://github.com/lutraconsulting/input-manual-tests/issues/6 

Project: cloned documentation\form_setup 

Test A4: I can't make the Species widget get values other than the first from the available values list. For example, for Farmland > Flower it is always Rose, for In-door > Fruit it is always Apple

**Comment by saberraz** [comment]
This is a bad project set up. Try documentation\forms_setup

**Comment by erpas** [comment]
For documentation/form_setup still holds...

**Comment by saberraz** [comment]
@erpas how about documentation\form_cascade?

**Comment by erpas** [comment]
@saberraz documentation\form_cascade works as expected.

**Comment by saberraz** [comment]
OK, it is the wrong project set up on the others.
