### ISSUE TITLE
missing proj datum shift when reprojecting

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input#1131]
When on tests lutraconsulting/input-manual-tests#25 and https://github.com/lutraconsulting/input-manual-tests/issues/24

Test A6 Restarting the app doesn't help - I still see the missing datum shift grid missing dialog and when hit Ignore, I only see empty map - no global map, as suggested in test.

**Comment by PeterPetrik** [comment]
@erpas can you check on the desktop that the grid files are actually bundled with the project (they are present in the proj/ directory?)

**Comment by erpas** [comment]
nope, the grid files are missing on desktop.

**Comment by saberraz** [comment]
same issue with the iOS. You can test:
https://public.cloudmergin.com/projects/lutraconsulting/test_grid_shift_with_proj/tree

**Comment by PeterPetrik** [comment]
ok so the test passes on Android. @saberraz on iOS it is not working based on the updated test case?

**Comment by saberraz** [comment]
@PeterPetrik correct. It works as expected on Android, but not iOS.
