### ISSUE TITLE
No feedback to user when Fetch more is pressed

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1143]
If I go to Projects > Explore and at the bottom of the list, press Fetch more....there is a delay in fetching the list. But there is no visual feedback to the user that Input is fetching items. It would be good to give user a visual feedback...maybe a moving small ribbon similar to the one when map rendering in in progress in the main map view.

**Comment by wonder-sk** [comment]
Yes... and if possible, we should probably just avoid having that button - a better UX would be that as soon as you get to the bottom of the list, at the bottom we would immediately start another request + show animated progress indicator icon until the request is done.
