### ISSUE TITLE
Feature information - wrong highlight of multi-geometry feature

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#1182]
After 0.8 update, I'm getting strange feature highlight geometries when clicking on feature to get feature information popup: 

![image](https://user-images.githubusercontent.com/4533263/107670292-e05abc80-6c92-11eb-8fca-0d24a10b430b.png)

Project: dracic/Naturavita Osijek - Saber has permissions.

**Comment by saberraz** [comment]
This appears to be an issue with the multi-polygon geometry type.
Here is a public project with the example:
https://public.cloudmergin.com/projects/saber/Identify-issue/

**Comment by dracic** [comment]
The issue is also visible on polylines. You can try to click one of the roads...
