### ISSUE TITLE
Photo azimuth

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1188]
A placeholder for https://github.com/qgis/QGIS/issues/41614

**Comment by sklencar** [comment]
NOTES:
* set azimuth bearing if not present in EXIF data
*  latitude, longitude, azimuth bearing, time should be read from EXIF and set to predefined fields (if exists)
* predefined fields are named as following (e.g. for field `photo` -> `photo_lat`): 
    * first part is the same as related photo field is named
     * reserved postfix according exif attribute

**Comment by saberraz** [comment]
There will be two tasks here:
1- To write the metadata information to the photo. So the info can be visible to any exif-reader
2- we then need some system variables in Input to read the exif data and parse them as default values to fields in forms (similar to `@mergin_username`). The variable syntax can be like this:
`photo_azimuth(field)` the function will take a field where photo is saved and returns the azimuth.
