### ISSUE TITLE
Show a warning when the accuracy is low

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1192]
Sometimes users are not aware of the fact their GPS accuracy is low (the yellow dot by the GPS icon is not very prominent).

The suggestion is that when user is in "Record" mode AND the crosshair is centered at the GPS position AND the accuracy is not "green", we should show a warning message on top of the map in the lower part of the screen (just above the toolbar), saying something like ":exclamation: Low GPS position accuracy (XXX m)"

cc @mostlyAtNight

**Comment by sklencar** [comment]
Do we want to have it as a popup window that is visible for a few seconds or rather permanent warning (can be closed)?
Any visual preferences?

**Comment by wonder-sk** [comment]
Maybe something like this - sorry I am unable to get anything better right now :-)

![image](https://user-images.githubusercontent.com/193367/109839967-e9163100-7c47-11eb-9d8d-4fc83c64a7da.png)
