### ISSUE TITLE
Support for better feature/layer addition

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#12]
When recording data, it will be easier to first prompt for layer or categorises under a layer and then record the feature.

We should move away from setting a single layer in edit mode for all the survey.

**Comment by wonder-sk** [comment]
Tasks:
- remove the button to pick active layer (and remove the label with current layer)
- when record button is clicked, Input will show a list of layers and user can choose which one will get the new feature
- after picking layer:
  - if it is point layer, store the current GPS position and show attribute form. When confirmed, the feature is added
  - if it is a line layer, start recording linestring from GPS. when record button is clicked again, attribute form will be shown. When confirmed, the feature is added

(maybe in the future we will add a way to select default layer for new features to make life easier for those who are going to add lots of features from one layer - but let's leave it out of scope for now)

**Comment by saberraz** [comment]
How about showing the classes for each layer to capture as a feature?

**Comment by wonder-sk** [comment]
> How about showing the classes for each layer to capture as a feature?

Let's leave this for a later stage... it may get a bit tricky there and it is just a small extension. If layer uses categorized renderer style, it would be relatively straightforward to extract categories. But not so if rule-based renderer is used. And maybe we would like to offer users to add some presets manually (a preset could possibly fill in default values to multiple attributes). So until we figure out how exactly we want it to work let's defer it.
