### ISSUE TITLE
"Start here!" project complains about missing grid

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1222]
Opening the project will show the error message with missing OSTN15 grid file - not the best welcome :-)

Let's fix the project by adding the missing file...

**Comment by saberraz** [comment]
This was supposed to fix the issue:
https://github.com/lutraconsulting/input/pull/1137

**Comment by wonder-sk** [comment]
:man_shrugging:  I can still see the issue: I remove the "start here!" project, uninstall input, then install it again, tap the project, and I get the PROJ warning...

**Comment by saberraz** [comment]
Let me do it again. Not sure what happened. Best to reproject the data instead of adding more MB to the app size.
