### ISSUE TITLE
Missing vertical space before group title

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1230]
Before "aldersvariation" there should be vertical space:

![image](https://user-images.githubusercontent.com/193367/110087074-77e39480-7d93-11eb-8900-624318878165.png)

**Comment by saberraz** [comment]
@wonder-sk I think the root cause is #1035

**Comment by wonder-sk** [comment]
@saberraz I think those are independent issues. This issue may be result of the recent layout spacing changes. It's worth checking with a properly configured groups (no tabs) if the spacing is correct.

**Comment by saberraz** [comment]
It looks fine when there is no "orphan" fields in D&D designer
![Screenshot_20210305-090029](https://user-images.githubusercontent.com/2649047/110092342-67cab580-7d91-11eb-98a0-e5d01a5c6b67.png)
![Screenshot_20210305-090003](https://user-images.githubusercontent.com/2649047/110092346-68634c00-7d91-11eb-829f-6ad121e832fc.png)

**Comment by saberraz** [comment]
@wonder-sk you are right:
![image](https://user-images.githubusercontent.com/2649047/110092876-ff300880-7d91-11eb-8bd6-c0082e8478a2.png)
