### ISSUE TITLE
Value Map field doesn't show the selected value in the form

### ISSUE THREAD

**Issue by jordyxt** [lutraconsulting/input#1231]
It appears that some fields on my form show empty values but when I open the dropdown there is a selected value.
I think this only happens in the new version (0.9.0).

**Comment by dracic** [comment]
I can confirm this issue. It started with 0.9.0 version

**Comment by saberraz** [comment]
I can confirm the issue. To replicate:
1- Open documentation\form_setup
2- Capture a feature and fill in the form, including the ones from the drop-down values
3- Save the feature
4- When back in the map, click on the captured point.
5- The form will open but the values appear as blank. Clicking on the drop-down menu displays the correctly selected value.

**Comment by saberraz** [comment]
@tomasMizera could you have a look at this? It is a regression and we need to fix and release a new version.
