### ISSUE TITLE
Input creates tab for each widget in form

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1233]
Probably related to #1035. 

@wonder-sk finally found reproducible scenario for this bug.

To reproduce:
 - open project `lutraconsulting/test_forms`
 - open feature form
 - open different project that does not have multiple tabs

Experienced:
 - you will see tabs created for all widgets

Sometimes application crashes when this bug happens.
I could reproduce this issue on all platforms

![image](https://user-images.githubusercontent.com/22449698/110295412-5da6f200-7ff1-11eb-93ff-f1366dba0961.png)

**Comment by saberraz** [comment]
This has been annoying me so much but I could not consistently reproduce the issue. I am glad you got to the bottom of it.
