### ISSUE TITLE
Back button causing crash

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1243]
It seems that there are places where we do not catch back button on Android. Hitting back on these places actually leads to a crash. Would be best to find all these places and handle that correctly since it can higher the number of crashes in play store/app store. 

Found places:
 - open recorder feature form in view state -> hit back -> 💥 

Best to fix together with #755

**Comment by sklencar** [comment]
The reported bug is gone - instead of crash, the `Unsaved changes` dialog opens.

The feature form and back button are indeed not working - widgets are stealing focus.

**Comment by saberraz** [comment]
@sklencar is there a PR for this?
