### ISSUE TITLE
New project: incorrect empty project error

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1249]
If I just enter project name and tap Create project, Input complains about empty project name...

![Screenshot_20210309_191831_uk co lutraconsulting](https://user-images.githubusercontent.com/193367/110521076-9b01a180-810f-11eb-966c-c07100a265e2.jpg)

**Comment by sklencar** [comment]
@wonder-sk Could you please add steps how to replicate? Thank you.

**Comment by wonder-sk** [comment]
1. open Create project wizard
2. type in project name + tap enter on the keyboard to hide it
3. tap "Create project" button

If I would tap on some other text edit field after entering text (i.e. change focus), things work correctly. But not if I only type in project name.

**Comment by tomasMizera** [comment]
I think this is again problem that we should use `displayText` from `TextField` component

**Comment by sklencar** [comment]
Yes, thats the first what crossed my mind, but couldn't replicate it. So was just wondering about the use-case

**Comment by tomasMizera** [comment]
Hmm, I haven't had similar problem in form, but it is probably there if we use `onEditingFinished` and `onTextChanged`. I faced this  problem with searchbar, but it is fixed already.
