### ISSUE TITLE
Detect missing layers and show warnings

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1263]
Users get confused when their layers do not appear on Input but shows up in their QGIS sessions. This at least one bug related to missing layer (#1257). In other occasions (I think if the missing layer is an online service) it takes a long time for any map to appear.

It would be good to show warnings and point the user to the packaging help documents, as this is very likely caused by incorrect packaging of layers/services.

**Comment by jozef-budac** [comment]
Related to https://github.com/lutraconsulting/input/issues/580
