### ISSUE TITLE
Cut polygon

### ISSUE THREAD

**Issue by rauledop1** [lutraconsulting/input#1284]
There is option to cut polygon in INPUT?

regards

**Comment by PeterPetrik** [comment]
No, you can use the QGIS tools when project is transferred to QGIS desktop

**Comment by saberraz** [comment]
I think this is feature. Let's have it open as a feature request.

**Comment by saberraz** [comment]
Related to #654

**Comment by saberraz** [comment]
Duplicate of https://github.com/lutraconsulting/input/issues/471
