### ISSUE TITLE
INPUT don´t save edited attribute when there are hole in polygon

### ISSUE THREAD

**Issue by rauledop1** [lutraconsulting/input#1285]
In many ocations I try edit polygon atributte, when I push 'Save' they not work, in all this situations the polygon there are holes inside like lake or island

kind regads

**Comment by saberraz** [comment]
This looks like a major bug, we will look into that for the next release.

**Comment by saberraz** [comment]
Seems to be working with this project and the current master:
https://public.cloudmergin.com/projects/saber/polygon-hole
