### ISSUE TITLE
Custom Mergin Server

### ISSUE THREAD

**Issue by bastooo** [lutraconsulting/input#1287]
I saw that it's possible to set up a custom server when I login to my account, but couldn't find anything, if I can setup my own server? 

1. Is it possible to host a Mergin-Server on your own server infrastructure?
2. If not, is there a plan for the future to offer this opportunity?

**Comment by saberraz** [comment]
Currently, we offer on-premise Mergin service. You need to purchase the service from us. For more info, see:
https://twitter.com/lutraconsulting/status/1374312129239654403

**Comment by saberraz** [comment]
@bastooo please contact us (info@lutraconsulting.co.uk) for more details.
