### ISSUE TITLE
Upload bugs/features

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#129]
* If there is an update from server before upload, new versions of files are download. Among newly downloaded files are also files which have not changed in meanwhile, but are in conflict with locally modified files. Local modified files are marked as conflicted_copy, local conflicted files are replaced by server files and sent to server.
* If conflicted copies of files are removed on server, after update they are also removed from local files.
* [BUG] If a file has been removed in a meanwhile on the server, it will be uploaded back to the server after an update (even if it unmodified).

* [Feature] Current implementation have upload and update as two different actions triggered one after the other. The best would be merge it to one sync-action.

**Comment by wonder-sk** [comment]
The issues should be resolved after the big mergin client refactoring.
