### ISSUE TITLE
QGIS cmake installation error

### ISSUE THREAD

**Issue by edips** [lutraconsulting/input#130]
When I try to install QGIS with cmake, I get the error:
```
cmake    -GNinja    -DCMAKE_BUILD_TYPE=Release    -DCMAKE_INSTALL_PREFIX=/home/edip/workspace/apps    -DWITH_GUI=FALSE    -DWITH_QUICK=TRUE    -DWITH_QTWEBKIT=FALSE    -DENABLE_TESTS=FALSE    -DWITH_BINDINGS=FALSE    ..
-- QGIS version: 3.5.0 Master (30500)
-- Found OpenCL C++ headers: /home/edip/workspace/QGIS/external/opencl-clhpp/include
-- Could not find GRASS 7
CMake Error at CMakeLists.txt:141 (MESSAGE):
  Desktop cannot be built without gui.  Enable WITH_GUI or disable
  WITH_DESKTOP.


-- Configuring incomplete, errors occurred!
See also "/home/edip/workspace/QGIS/build-cmd/CMakeFiles/CMakeOutput.log".
See also "/home/edip/workspace/QGIS/build-cmd/CMakeFiles/CMakeError.log".
```
Edit:
I installed QGIS with disabling WITH-DESKTOP.
QGIS installation path: /home/edip/workspace/apps
Input installation path: /home/edip/workspace/input
Before installing QGIS, I installed necessary libs:
`sudo apt-get install bison ca-certificates ccache cmake cmake-curses-gui dh-python doxygen expect flex gdal-bin git graphviz grass-dev libexiv2-dev libexpat1-dev libfcgi-dev libgdal-dev libgeos-dev libgsl-dev libosgearth-dev libpq-dev libproj-dev libqca-qt5-2-dev libqca-qt5-2-plugins libqt5opengl5-dev libqt5scintilla2-dev libqt5serialport5-dev libqt5sql5-sqlite libqt5svg5-dev libqt5webkit5-dev libqt5xmlpatterns5-dev libqwt-qt5-dev libspatialindex-dev libspatialite-dev libsqlite3-dev libsqlite3-mod-spatialite libyaml-tiny-perl libzip-dev lighttpd locales ninja-build ocl-icd-opencl-dev opencl-headers pkg-config poppler-utils pyqt5-dev pyqt5-dev-tools pyqt5.qsci-dev python-autopep8 python3-all-dev python3-dateutil python3-dev python3-future python3-gdal python3-httplib2 python3-jinja2 python3-markupsafe python3-mock python3-nose2 python3-owslib python3-plotly python3-psycopg2 python3-pygments python3-pyproj python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtsql python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-requests python3-sip python3-sip-dev python3-six python3-termcolor python3-tz python3-yaml qt3d-assimpsceneimport-plugin qt3d-defaultgeometryloader-plugin qt3d-gltfsceneio-plugin qt3d-scene2d-plugin qt3d5-dev qt5-default qt5keychain-dev qtbase5-dev qtbase5-private-dev qtpositioning5-dev qttools5-dev qttools5-dev-tools saga spawn-fcgi txt2tags xauth xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable xvfb`

```
cmake    -GNinja    -DCMAKE_BUILD_TYPE=Release    -DCMAKE_INSTALL_PREFIX=/home/edip/workspace/apps    -DWITH_GUI=FALSE -DWITH_DESKTOP=FALSE    -DWITH_QUICK=TRUE    -DWITH_QTWEBKIT=FALSE    -DENABLE_TESTS=FALSE    -DWITH_BINDINGS=FALSE ..
ninja
ninja install
```
But when setting path variables on terminal I get error,
```
APP=/home/edip/workspace/apps
LD_LIBRARY_PATH=$APP/lib/ QML2_IMPORT_PATH=$APP/qml QGIS_PREFIX_PATH=$APP $APP/bin/input
```
`bash: /home/edip/workspace/apps/bin/input: No such file or directory`
Should I copy input app to QGIS's installation folder?

**Comment by saberraz** [comment]
I have the same set up (Ubuntu 18.10) but decided to go through docker route:
- Install docker image for osgeo4a
- then you can easily compile Input:

`docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-armv7" -e "ARCH=armv7"  -it osgeo4a`
- Assumes your pwd is input folder checked out from this repo.

Once you are in the container:
`/opt/android-sdk/tools/bin/sdkmanager --licenses`
Agree to all licenses. Then:
`/usr/src/input/scripts/docker-build.sh`

**Comment by edips** [comment]
Sorry, I haven't used docker before, I searched about it, installed docker but I couldn't find image for Osgeo4A. I searched it on hub.docker.com but no result. Could you explain it please? 
Thanks.

**Comment by saberraz** [comment]
https://github.com/opengisch/OSGeo4A

**Comment by PeterPetrik** [comment]
you do not need to compile SDK, see here https://github.com/lutraconsulting/input/blob/master/.travis.yml#L17

**Comment by PeterPetrik** [comment]
@saberraz maybe add this description to README (how to build on docker?)

**Comment by edips** [comment]
After installing OsGeo4A, I tested on desktop, it worked without problem but now I tested on Android, it doesn't work. The installation took many hours on Virtualbox. I will do a clean installation again. I hope this time it will work :) I am not familiar with docker maybe I did something wrong. When running input on Qt Creator, it gave many errors like this: :`-1: warning: skipping incompatible /home/edip/workspace/apps/lib/libqgis_core.so while searching for qgis_core` I checked `/home/edip/workspace/OSGeo4A/stage/armeabi-v7a/lib` path, There isn't qgis_core.so. @PeterPetrik  I set environment path, I am not sure docker included SDK for building.

**Comment by saberraz** [comment]
@edips as per my comment:
after creating osgeo4a container, in terminal:
`docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-armv7" -e "ARCH=armv7" -it osgeo4a`
This will take you to bash in docker environment (in front of `root@something#`):
```
/opt/android-sdk/tools/bin/sdkmanager --licenses
/usr/src/input/scripts/docker-build.sh

```

**Comment by PeterPetrik** [comment]
"skipping incompatible" means you are mixing up native OS libraries and libraries for Android from OSGeo4A. Best to use approach suggested by Saber.

**Comment by PeterPetrik** [comment]
you do not need to set any environment variables. With docker approach you download already prepared OSGeo4A and build Input in the container.

**Comment by edips** [comment]
Thank you @saberraz and @PeterPetrik, fortunately I built APK with docker. I was missing to set osgeo4a image path , I set local OSGeo4A folder before. After changing osgeo default path to /home/osgeo4a, the script worked. But when I open the app, it didn't work like desktop version.

**Comment by edips** [comment]
I built it with docker again, this time "mergin" page is asking user name and password.
