### ISSUE TITLE
Can't enter credentials

### ISSUE THREAD

**Issue by waiotahi** [lutraconsulting/input#1304]
Input App 0.9.2 / screen resolution 640 x 480 /landscape
Cant enter /signin  with credentials on Login page.
The signup for free & reset links both work but nothing on SIGNUP?

**Comment by waiotahi** [comment]
This is the same behavior as ticket # 1114

**Comment by saberraz** [comment]
To reproduce, you can use your iOS device in Landscape mode.

**Comment by waiotahi** [comment]
![Screenshot_20210518-151846](https://user-images.githubusercontent.com/53323943/118585289-ae567a80-b7ec-11eb-90e9-8d484cf44dad.png)
I finally got around to updating to 0.9.3 and testing - I still don't seem to be able to login - It will send me to reset the password or register a new account but not signin
