### ISSUE TITLE
[iOS] Exif for camera images

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1305]
Extend the functionality to have EXIF working with image from a camera.

Current implementation of Camera works only with raw QImage data, not file itself - so all metadata are missing. Moreover, CameraPicker doesn't have reference URL, so Photo asset library needs to be used to actually save the image from camera.

Whats needed (and suggested):
* get location manager working
	- implement custom delegateView with LocationService implementation (similar to Android)
	- fetch data when a capture is done

* write data with Photo (PHAsset) library (NSPhotoLibraryAddUsageDescription NSPhotoLibraryUsageDescriptionkey need to be added)
	 - copy captured image with some metadata to gallery/or directly to target location and extend it with GPS metadata

**Comment by PeterPetrik** [comment]
done in 0.9.3
