### ISSUE TITLE
Crash when recording a feature

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1306]
1- Download lutraconsulting\test_exif
2- Add a point
3- Crash 

Tested with APK from master and iOS test flight (https://github.com/lutraconsulting/input/commit/cb0885c4ac96a719173d35fa7ee2c78454f34703#commitcomment-49310454)
This is likely to be due to the new default value.

**Comment by tomasMizera** [comment]
Another occurrence of #1126 or https://github.com/lutraconsulting/input/issues/1233 (Form models generally)
