### ISSUE TITLE
JS Error, property is not a function in Feature form

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1312]
Open project `tomas/Testiky` (but seems to be reproducible on all projects), open feature form, in console you will see many errors like: `TypeError: Property 'supportsDataImport' of object QObject_QML_67(0x5636ddd5f140) is not a function`

![image](https://user-images.githubusercontent.com/22449698/114403250-e989dc00-9ba4-11eb-86b4-ffb8190901cd.png)

It seems that it throws this error for each field in the form.

**Comment by saberraz** [comment]
This can be reproduced by 
- opening lutraconsulting\test_exif
- record a point + photo
- add the 2nd point 
And there will be am error with data type which does not disappear until you force close Input.

Tested with APK from master

**Comment by saberraz** [comment]
![Screenshot_20210412-145228](https://user-images.githubusercontent.com/2649047/114405707-d96efe00-9b9e-11eb-8942-72b53638f3ad.png)
