### ISSUE TITLE
relationship

### ISSUE THREAD

**Issue by waiotahi** [lutraconsulting/input#1314]
I have a spatial table referencing a point with multiple attributes(Table A). I also have a table with no geometry (Table B) where I capture multiple features that I need  to link to Table A. At the moment I can capture the point , then save and then go to browse features where I can open Table B and start adding features - it would be nice to do this while Table A is still open. I'm assuming that 'Input' doesn't support joins/relationships at this time - given that,  what would be the best solution to link these 2 tables ?
Similar to #452

**Comment by stevenjh** [comment]
I'm interested in progress against this workflow too, mostly in relation to capturing multiple photos against a location.

**Comment by saberraz** [comment]
It is in the pipeline for future releases, if you want to co-fund this feature, please contact us on info@lutraconsulting.co.uk

**Comment by saberraz** [comment]
Duplicate of https://github.com/lutraconsulting/input/issues/452 ?

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/input/issues/1511
