### ISSUE TITLE
Problem with Android Pie

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#132]
Not compatible with Android Pie.
![download_20190128_212915](https://user-images.githubusercontent.com/2649047/51867726-1d6de380-2344-11e9-991e-da7d631b14a6.jpg)

**Comment by gubuntu** [comment]
yes it's quite unstable - sometimes doesn't open, hangs, crashes. A few days ago I could open some projects under My Projects and I could download (but not open) projects under all projects. 

Today I downloaded the Kartoza2 project but thereaafter no response at all from either project screen

**Comment by saberraz** [comment]
@gubuntu it is indeed a bit slow. I think Kartoza2 relies on a Postgis layer and a couple of XYZ tiles so, it takes time depending on your connection speed to load the project.
