### ISSUE TITLE
Feature information - crash when selecting multipolygons or polygons with rings

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#1322]
Project dracic/sumarija-novi-vinodolski
layer: ods

Saber has access to my project

Try polygons on south edge

**Comment by saberraz** [comment]
Isn't this duplicate of https://github.com/lutraconsulting/input/issues/1182?

**Comment by dracic** [comment]
This time Input crashes completely when selecting polygons. It is not just wrong highlighting.
