### ISSUE TITLE
"URL not found" error

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/input#1331]
In "Explore" after I fetch of multiple public projects, there is a URL not found error.
More info in the record

https://user-images.githubusercontent.com/78033756/115000339-f6f3de80-9ea2-11eb-8aa6-6fcb1d94a374.mp4

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/input/issues/1391

**Comment by jozef-budac** [comment]
Can't simulate anymore. Probably fixed by fetch refactoring
