### ISSUE TITLE
[Duplicate] Crash after add new feature

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/input#1332]
When I am trying to add new feature, there is sometimes a crash of application.
Unfortunately (or luckily?), the app doesn't crash always. 

Steps to reproduce:
1) download lutraconsulting\test_forms
2) open it
3) try to add feature

https://user-images.githubusercontent.com/78033756/115001127-b8aaef00-9ea3-11eb-94ae-401ba3e289b2.mp4

**Comment by saberraz** [comment]
Duplicate of this:
https://github.com/lutraconsulting/input/issues/1281

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/input/issues/1035 and duplicate of #1281

**Comment by saberraz** [comment]
Resolved after form refactoring.
