### ISSUE TITLE
Upper case switch on automaticaly

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/input#1334]
During creation of new project and adding new field, upper case switch on keyboard is automatically turn on even after turn it off manually. This problem is not visible with project name

https://user-images.githubusercontent.com/78033756/115005892-9b2c5400-9ea8-11eb-9a80-85390ee127fb.mp4

**Comment by saberraz** [comment]
This bug also affects the field creation in the project wizard too.
