### ISSUE TITLE
ability to hide tables/layers in Input

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/input#1346]
Hi guys, I was wondering if its possible to hide certain tables/layers from the user in Input, similar to what this plugin [gacarrillor/InvisibleLayersAndGroups](https://github.com/gacarrillor/InvisibleLayersAndGroups) does in QGIS. For us who use the Mergin/Input combo with non technical clients, the ability to "browse features" in input and see all tables/features like lookup tables causes a lot of confusion and questions from our clients. Is there a way to do this currently? It would mike my life easier 😁

**Comment by dracic** [comment]
https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_configuration.html#data-sources-properties

You do that in project properties/data sources by making some of layers not searchable/private

**Comment by saberraz** [comment]
Yes, that should do the trick.
