### ISSUE TITLE
Log in button covered by keyboard

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#137]
![screenshot_20190131-200510_input](https://user-images.githubusercontent.com/2649047/52082055-ad559c80-2593-11e9-9903-2845bcc11846.png)

**Comment by wonder-sk** [comment]
Just checked other apps and they seem to resize the login screen when the keyboard opens up. I think we can use `Qt.inputMethod.visible` and `Qt.inputMethod.keyboardRectangle` and resize the auth panel accordingly.
