### ISSUE TITLE
Better handling of userInfo + subsciptionInfo

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1375]
UserInfo and subscriptionInfo have been split into 2 separate requests due to support for CE Mergin.
AccountPage and also StorageLimitInfo dialog send those two requests before they are opened to show updated data.
Since there are two requests, page/dialog updates content after each request which looks unprofessional.

Would be good to wait till all data are fetched.
Additionally, userInfo can automatically call subscriptionInfo if possible.

Endpoint for Mergin has been added:
https://gitlab.cloud.lutraconsulting.co.uk/mergin/mergin/-/issues/668

**Comment by PeterPetrik** [comment]
New endpoint in mergin should be on place
