### ISSUE TITLE
Date Time widget does not work

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1377]
Currently, we only support calendar widget which user can set the date. But if the field is Date&Time there is not an option to pop-up for calendar does not appear and there is no way to set the time.

An example project, is  **Date added (automatic)** field in **Capture field data tour** project
A work-around is to have Date and Time in different fields.

![image](https://user-images.githubusercontent.com/2649047/117283305-92062580-ae5d-11eb-8015-0f570f08f7af.png)

**Comment by jozef-budac** [comment]
I can't simulate this in latest INPUT. Probably it was fixed by forms refactoring.
@saberraz  can you confirm?
