### ISSUE TITLE
HTML tooltip doesn't work

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#138]
If I set a HTML tooltip for my survey layer, it still shows the first column as the identify panel (fid) as the header.
![screenshot_20190131-201225_input](https://user-images.githubusercontent.com/2649047/52082572-070a9680-2595-11e9-8b44-8b473a38f376.png)

It should show:
![image](https://user-images.githubusercontent.com/2649047/52082536-f78b4d80-2594-11e9-88ba-6699763fb91d.png)

**Comment by wonder-sk** [comment]
It works like this in preview panel:
- for the feature title, you need to set the "Display name" to a field or an expression
- for the content, Input shows two fields with their values. By default it will show the first two fields. If you want to override the fields that should be displayed, you can set HTML Map Tip content by specifying two field names (one on each separate row). So this is completely different from how it works in QGIS - for simplicity. The problem with proper HTML map tips would be that it would be difficult to get the formatting right. But we can add support for arbitrary content at some point later...

**Comment by saberraz** [comment]
> for the feature title, you need to set the "Display name" to a field or an expression

@wonder-sk here is my settings for the above screenshots in QGIS but the title still appears as **1**:
![image](https://user-images.githubusercontent.com/2649047/52107268-a0659700-25ed-11e9-9bc7-497e9e2e57b5.png)
