### ISSUE TITLE
Edit geometry works only first time

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1380]
When I add a feature and want to change geometry, the second time the geometry is not changes but stayed in the same position.

https://user-images.githubusercontent.com/83582181/117302349-d1dc0580-ae7b-11eb-87ee-8b0e6a41b664.mp4

**Comment by sklencar** [comment]
The issue seems to be more complex. Edited feature cannot be also identified in both Input and QGIS.
After discussion with Martin, issue can be related with geodiff and spatial indices.

related to https://github.com/lutraconsulting/input/issues/1124

**Comment by saberraz** [comment]
This appears resolved in master. @sklencar could you reference the PR and close if it is done?
