### ISSUE TITLE
SVG marger doesn't work in input

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1382]
In QGIS 3.16 there is an predefined SVG marker named "shield disability"

![Screenshot at 2021-05-06 21-19-38](https://user-images.githubusercontent.com/83582181/117354028-2a79c580-aeb1-11eb-8d94-e6d279b2ca1b.png)

In input is shows only question mark:

<img src="https://user-images.githubusercontent.com/83582181/117354257-6c0a7080-aeb1-11eb-9447-05056756c2c2.jpg" width=250>

**Comment by wonder-sk** [comment]
See #139 - Input does not ship the SVG symbols that come with in QGIS. We should add packaging of SVGs to QGIS mergin plugin to avoid this issue: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/209

**Comment by saberraz** [comment]
Indeed, this is a duplicate and let's address it in the plugin.
