### ISSUE TITLE
Not all strings are translated

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1387]
There are multiple strings, which are not translated into system language:
- Privacy policy
- Mergin terms of service
- Diagnostic logs
- On the main window (Home, My projects, Shared, Expolore, Projects )

But it looks like the problem is just with some of the translations

https://user-images.githubusercontent.com/83582181/117636744-69459f00-b181-11eb-82b6-a0e0f4ea2870.mp4

**Comment by PeterPetrik** [comment]
This is expected and happens in following situation
1) language is 100% translated
2) we release with all strings
3) the next release the new language strings are not translated
4) we release with only not-modified strings from 1-2) (old version)
