### ISSUE TITLE
App is very slow without location permission

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1389]
Without location permission, the app is almost unusable. It is too slow to do anything.

https://user-images.githubusercontent.com/83582181/117645219-a3676e80-b18a-11eb-80ca-11ef8be82830.mp4

**Comment by tomasMizera** [comment]
Duplicate of #1101 and related to #1057

**Comment by tomasMizera** [comment]
Closing since it is a duplicate
