### ISSUE TITLE
Missing svgs

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#139]
Some of the default SVGs used in QGIS are not available in Input and you will end up with ?
![screenshot_20190131-201225_input](https://user-images.githubusercontent.com/2649047/52082636-391bf880-2595-11e9-8880-61b1351cd414.png)

**Comment by timlinux** [comment]
Getting this here in my projects too:

![Screenshot_20190319-165438](https://user-images.githubusercontent.com/178003/54618932-bcb57a00-4a5b-11e9-8c76-1cabbb8d28e7.png)

**Comment by wonder-sk** [comment]
@timlinux compared to qgis, Input does not ship "standard" svg files ... you'll just need to copy any SVGs you have used to the project folder and it should work

**Comment by saberraz** [comment]
You can even embed the svgs to your QGIS project file.

**Comment by timlinux** [comment]
Ok I will try that thanks!
