### ISSUE TITLE
Fields outside of groups ignored even when there are no tabs

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1412]
I have a project with a following form structure:

![image](https://user-images.githubusercontent.com/22449698/118805393-2a60c900-b8a6-11eb-8ac2-72f414a272c2.png)

There are 5 fields and 1 group. One field is inside the group, others are outside. Distance group has visibility set based on boolean *ShowNearest* Input renders it like this:

<img src="https://user-images.githubusercontent.com/22449698/118805494-449aa700-b8a6-11eb-90d4-19c3c41c28bf.png" width=300>

It omits the outside fields. This behavior is correct for tabs, but it is doing the same for groups. We need to differentiate between groups and tabs.  

Logs from console: 
```
element in tab layout that is not part of any tab. Ignoring!
element in tab layout that is not part of any tab. Ignoring!
element in tab layout that is not part of any tab. Ignoring!
element in tab layout that is not part of any tab. Ignoring!
```

They are coming from here https://github.com/lutraconsulting/input/blob/master/app/attributes/attributecontroller.cpp#L301 we need to check for group and handle it.

Forms before refactoring render this as expected.

**Comment by saberraz** [comment]
See https://public.cloudmergin.com/projects/lutraconsulting/12_form_group/tree which is a combination of conditional visibility of groups, sub-groups and individual fields. It is completely broken in Input but works fine in QGIS.

**Comment by saberraz** [comment]
Fixed the issue temporarily by simplifying the form. If you plan to fix it, you need to check Version 1, before the simplification.

**Comment by jozef-budac** [comment]
@tomasMizera I can't simulate this anymore. I think it is already fixed.
