### ISSUE TITLE
Duplicate project entries on device / ability to delete my projects in app

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#142]
![img_8523](https://user-images.githubusercontent.com/178003/52123419-b8113f80-262e-11e9-8cf5-d6838b923fea.JPG)

I somehow managed to end up with two copies on the device. It probably relates back to the MERGIN issue where if you overwrite a QGIS project you lose your tags requiring that you delete and recreate your project on MERGIN. It would be great if I could delete a MY PROJECTS project from within the app.

**Comment by saberraz** [comment]
I think the ... to the right is reserved for delete and some other options.

**Comment by wonder-sk** [comment]
This is just because the "my projects" lists project file names (not mergin project file names) so those are probably .qgs files from two different mergin projects. This should be addressed soon when #133 is fixed
