### ISSUE TITLE
Sign in notification are missing again

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1427]
App version 0.9.7.

All toast notification are missing. 

One example is:
When signing in, there is no notification when wrong or no login/password is used.
This steps in TC01 (input-manual-tests#2) failed:

B7. Application should stay at login page and popup with text: Invalid username or password shall be visible
B8. Wait till notification will disappear (in few seconds)
B10. Popup should inform you with text: Please enter your login details
B11. Repeat B9 and B10 with password (leave username empty)

Other occurences:
1)  during creation of new project when adding 2nd empty name field.
2) show local changes on the project when there are none

**Comment by tomasMizera** [comment]
@jozef-budac I could not reproduce this on current master (local build) nor apk built from latest commit. Tested with `android arm64-v8a`

<table>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/22449698/119788783-bb512900-bed2-11eb-9aab-6f6779576e07.jpg" width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/119788809-c1dfa080-bed2-11eb-8075-9db2be301b1d.jpg"  width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/119788813-c441fa80-bed2-11eb-8db8-b03a8a8fbb5c.jpg"  width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/119788822-c60bbe00-bed2-11eb-8b3c-098e71bb914a.jpg"  width="300"/></td>
  </tr>
 </table>
