### ISSUE TITLE
New iOS update: lot of bugs

### ISSUE THREAD

**Issue by katagen** [lutraconsulting/input#1448]
Hi,
I just download the last update for iOS.

1. My aerial orthophoto background doesn’t load anymore (themes).

2. When I try to save a new point, I can’t pitch in or out anymore, can’t select GPS button. Everything is freezing!

This update is really problematic.

**Comment by saberraz** [comment]
Hi,

Could you uninstall and re-install the app?

Also could you let me know what iOS version you are using?

**Comment by saberraz** [comment]
If all fails, could you share your project with me on Mergin (my username is saber).

**Comment by katagen** [comment]
Hi,
All the problems are still here, even after a new install.
I share the projet with you!

I use iOS 14.6 and Input 0.9.7
Before this new version of Input, everthing worked properly!

———————
Antoine Stocker
Avenue du Servan 24
1006 Lausanne
078 / 915 18 72
***@***.***

**Comment by saberraz** [comment]
See #1450 with detail explanation and suggested work-around until we fix the issue.
