### ISSUE TITLE
Digitizing and background map issue when projection transformation is missing

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1450]
This issue is specifically related to the iOS:

When projection transformations are not set explicitly, the background map does not show up and also it is not possible to digitize.

As an example, see:
https://public.cloudmergin.com/projects/saber/123_gmaps/tree

The work-around is to make the following changes in QGIS:
1- Set the canvas projection to match the background CRS (EPSG:3857)
![image](https://user-images.githubusercontent.com/2649047/120587437-44b1af80-c42d-11eb-8cd1-206d594e3f08.png)

2- Add the transformation
![image](https://user-images.githubusercontent.com/2649047/120587444-4b402700-c42d-11eb-8aa4-3f10f1fb74d4.png)

The issue is not present in Android, which leads me to believe the issue is related to the SDK (not sure which one is using what version of proj, QGIS)

**Comment by PeterPetrik** [comment]
both use proj=6.3.2

**Comment by saberraz** [comment]
In another project, when there was an unused transformation, the points were captured but Local changes were shown to be non-existent:
https://public.cloudmergin.com/projects/lutraconsulting/ios_issue/tree

**Comment by saberraz** [comment]
The work-around is to remove the (unused) Transformation in the Project Properties in QGIS and it works again:
![image](https://user-images.githubusercontent.com/2649047/120967870-f91a4100-c75f-11eb-9d3b-8415c756bd20.png)

**Comment by PeterPetrik** [comment]
0.9.6 is based on qgis 3.16, 0.9.7 on qgis 3.19. By bisecting 

```
Bisecting: 0 revisions left to test after this (roughly 1 step)
[bd26ae1d2923b22447ed210e3c7e37e0043c1591] Add basic support for coordinate epoch of dynamic (not plate fixed) crs to QgsCoordinateTransform
```

it looks like this is the commit that broke iOS for some reason. 
https://github.com/qgis/QGIS/commit/bd26ae1d2923b22447ed210e3c7e37e0043c1591

**Comment by saberraz** [comment]
Here is another example:
https://public.cloudmergin.com/projects/lutraconsulting/test_position_variables/tree

**Comment by PeterPetrik** [comment]
It happens when one CRS is static and other dynamic 

EPSG:2056 - CH1903+ / LV95: Static (relies on a datum which is plate-fixed)
EPSG:3857 - WGS 84 / Pseudo-Mercator: Dynamic (relies on a datum which is not plate-fixed)



Dynamic (relies on a datum which is not plate-fixed)
--



EPSG:2056 - CH1903+ / LV95 -> Static (relies on a datum which is plate-fixed))

**Comment by PeterPetrik** [comment]
added manual test @jozef-budac https://github.com/lutraconsulting/input-manual-tests/issues/24 TEST-B

**Comment by PeterPetrik** [comment]
fixed by https://github.com/lutraconsulting/input-sdk/commit/2d4d7623320df72c1c779196d62ccd47305caba5, see https://developer.apple.com/forums/thread/656056

**Comment by wonder-sk** [comment]
By the way - the source of the problem: https://github.com/qgis/QGIS/blob/master/src/core/proj/qgscoordinatetransform.cpp#L657

isnan() was returning false for a value that is NaN

**Comment by saberraz** [comment]
I can confirm the new SDK has resolved the issue.
