### ISSUE TITLE
Text field limit is ignored for alphabetical characters

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1455]
Then there is Text Edit widget type on QString field with max length 10 characters, during recording of the new feature INPUT limits the length for numbers but not for alphabetical characters. 
After saving the feature, the string is trimmed to 10 characters

https://user-images.githubusercontent.com/83582181/121004659-3e099c00-c78f-11eb-9006-543120ea7f6c.mp4

**Comment by tomasMizera** [comment]
Related to #1541
