### ISSUE TITLE
Lack of user documentation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#146]
How should I use this software?

**Comment by saberraz** [comment]
Feel free to do a PR to add it to the developers doc.

**Comment by wonder-sk** [comment]
Started some docs:

https://github.com/lutraconsulting/input/blob/master/docs/intro.md
https://github.com/lutraconsulting/input/blob/master/docs/project_config.md
https://github.com/lutraconsulting/input/blob/master/docs/using_input.md
https://github.com/lutraconsulting/input/blob/master/docs/data_sync.md
