### ISSUE TITLE
The form doesn't use checkbox date widgets with autogenerated form

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1464]
When I create new project with auto-generated form, in INPUT, checkbox and Date&Time widgets (and probably also range) shows only simple field without slider, calendar or square for check.

you can check this on project tin1/test4

![Screenshot_20210608-110012](https://user-images.githubusercontent.com/83582181/121156259-d6178c00-c848-11eb-9ea4-5cefd61429d5.png)

**Comment by wonder-sk** [comment]
Isn't QGIS also showing all the fields as simple "text edit" widgets? I think that's the default QGIS behavior to leave widgets for any column type as "text edit" ?

**Comment by jozef-budac** [comment]
The same project in QGIS shows the checkbox. 
The form for date and checbox is not set as "Text edit". 
Date have "Date/Time" widget
Checkbox have "Checkbox" widget

![Screenshot at 2021-06-08 11-01-24](https://user-images.githubusercontent.com/83582181/121665163-88995a00-caa8-11eb-97a7-491d9491800d.png)

**Comment by tomasMizera** [comment]
Might be related to https://github.com/lutraconsulting/mergin/issues/3
