### ISSUE TITLE
Polygon labels crash Input for iOS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1466]
1- Download this project: https://public.cloudmergin.com/projects/lutraconsulting/ios-label-crash/tree
2- Zoom in so the labels for polygon becomes visible
3- Crash

It does not crash Android.

**Comment by saberraz** [comment]
Duplicate of #1450 and now works with the new iOS sdk.

**Comment by saberraz** [comment]
@jozef-budac this is closed, but worth checking on your device too.

**Comment by jozef-budac** [comment]
It works well in on iOS in version 0.9.8.
