### ISSUE TITLE
App crash during recorging the polygon

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1473]
Steps to reproduce:

1) start record the polygon
2) add 3 point but don't press done yet
3) move cursor for adding new point and cross already created line (side) of polygon and do it when zooming the project (have 2 fingers on the screen)
4) the app crash

https://user-images.githubusercontent.com/83582181/121645183-30585d00-ca94-11eb-8118-fbf45e1d1ee6.mp4

**Comment by saberraz** [comment]
To successfully reproduce the crash, move the cross to snap to an existing vertex.

**Comment by jozef-budac** [comment]
Can't simulate anymore so closing this bug
