### ISSUE TITLE
Value relation problem

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1477]
This issue is on both Android and iOS version
In TC05, there are steps:

A4. Test value relation widget:

    Click on widget
    New page shall open listing all features from referenced layer
    Page has searchbar
    Find a feature via searchbar and select it
    Page shall close and correct name should appear in widget

Sometimes the step "Page shall close and correct name should appear in widget" doesn't work well.

Steps to reproduce:
1) download project input-testing/form_widgets
2) record the feature and go to Relation tab
3) in type choose "Deciduous"
4) click on the "Name" and pick "Apple tree"
5) click on the "Name" again, put "Pear" into the searchbox. Only the Pear Tree should filter. Select it.
6) The result is that empty value is inserted into "Name" field instead of "Pear tree"

**Comment by tomasMizera** [comment]
What do you mean by "it doesnt work well"?

**Comment by jozef-budac** [comment]
It means, when I select item from the filtered list (by a search bar), it should appears in the field. But it isn't

**Comment by tomasMizera** [comment]
Related #1559

**Comment by tomasMizera** [comment]
Awaits #1507 and #1517

**Comment by tomasMizera** [comment]
Closing, will be fixed in: #1640
