### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1478]
What is in English "Updated x minut ago"
is in German "1% actualiziet"

![a](https://user-images.githubusercontent.com/83582181/121662290-72d66580-caa5-11eb-84e9-d7ea9bcf963f.jpg)
![b](https://user-images.githubusercontent.com/83582181/121662303-75d15600-caa5-11eb-9237-1f97a20c3db7.jpg)

**Comment by wonder-sk** [comment]
Should be fixed by #1811
