### ISSUE TITLE
Inconsistent Issues adding point features

### ISSUE THREAD

**Issue by roya0045** [lutraconsulting/input#1479]
Greetings,

We are using input mainly to add points with a form and in some instances the points are never added.

To resolve the problem we are forced to restart the app, edit the geometry and then save. This only works on the first point, this must be redone for each point and work 50% to 30% of the time.

We have 3 distinct iPhone and sometime one works flawlessly and on some other instances two of them have this issue for the whole day.

The project worked fine previously but this started to occur a few months ago.

**Comment by roya0045** [comment]
In the diagnostic log I get `geometry type is not compatible with the current layer` Unsure if the error is right.

**Comment by PeterPetrik** [comment]
@roya0045 We have fixed major iOS issue related to geometry handling and CRS caused by recent update of compiler to clang12, see https://github.com/lutraconsulting/input/issues/1450.

Can you please update all your iOS devices to version 0.9.8 and if the problem persists report it back? Thanks

**Comment by roya0045** [comment]
@PeterPetrik Will do, thanks a ton! I'll close this in the meantime.
