### ISSUE TITLE
"Learn more" link show 404 page not found

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1489]
On this page, "Learn more" (or Errfahre mehr) shows 404 Page not found error

![image0](https://user-images.githubusercontent.com/83582181/122175318-da185f00-ce83-11eb-8201-8c9ffb95af4e.png)

**Comment by wonder-sk** [comment]
@sklencar is this the same issue as reported in #1536 ? (point 2)

**Comment by jozef-budac** [comment]
Yes, it is
