### ISSUE TITLE
Multiline widget text dissapears

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/input#1502]
INPUT: 0.9.8
project: tin1/forms_widgets

In multi-line widget, when scrolling out of the window, the text sometimes disappears. 
Steps to reproduce:
1) open project tin1/forms_widgets
2) record the feature in POI layer
3) go to relation tab, set some type, name and country in the Value relation fields
4) go down, set some text into Multiline field, scroll up and down again and see that the text disappears.

https://user-images.githubusercontent.com/78033756/122540942-6912ac00-d029-11eb-9cdf-45fc5b842c03.mp4

**Comment by saberraz** [comment]
@jozefbudac do we have a test project for this to reproduce the issue and in future for manual test?

**Comment by jozef-budac** [comment]
Still exists in lastes master
Version: 57994275d071fe6efe7e4a2f830e9364c8cdabc2
OS: Android arm64-v8a

**Comment by jozef-budac** [comment]
Still exists in 0.9.9 Beta
