### ISSUE TITLE
Range editable widget followup

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1518]
Known issues from #1500 

- [x] it is possible to save when hitting save directly before commiting text (due to a Qt bug https://bugreports.qt.io/browse/QTBUG-94499?jql=status%20in%20(Reported%2C%20Open)%20AND%20text%20~%20%22qt%20inputmethod%20visible%22%20ORDER%20BY%20created%20DESC)
- [x] "invalid value text" disappears if you commit the same text twice
- [x] polish loop (when field has suffix, we need to center it)

~CRASH!: _also sometimes the app crashes when editing existing feature. An it crashed in a way, that even screen recorder crashes. So maybe there is a bigger problem (in android?). The project used for testing is input-testing/test_decimals_~

Double check these issues: https://github.com/lutraconsulting/input/pull/1500#pullrequestreview-690441941

**Comment by jozef-budac** [comment]
Few notes:
- For big numbers, the text should be centered even without suffix
- When inserted really big number, +- signs are active but don't work

**Comment by jozef-budac** [comment]
I will start new comment :) 
There is another crash in relations widget. Step to simulate:

1) open project input-testing/forms_widgets
2) go to tab relations
3) set type to Deciduos, name to Apple Tree, country to Czech and then type to Evergreen

https://user-images.githubusercontent.com/83582181/123777302-5a04e700-d8d0-11eb-92de-36bdb6e6f0ca.mp4

**Comment by tomasMizera** [comment]
The latest mentioned crash should be sorted out in https://github.com/lutraconsulting/input/pull/1524 Needs to be tested though. I tested different project

**Comment by tomasMizera** [comment]
Both crashes should be fixed now
