### ISSUE TITLE
Value input relation generates error

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1522]
It happens for number fields with textedit widget. Can be replicated with project `tin1/forms_widgets`

TypeError:
`qrc:/editor/inputvaluerelation.qml:125: TypeError: Property 'startsWith' of object ... is not a function`

**Comment by tomasMizera** [comment]
I have also received `qrc:/editor/inputvaluerelation.qml:125: TypeError: Type error` for the same project

**Comment by tomasMizera** [comment]
For project `tomas/test-general` I also experienced `qrc:/editor/inputvaluerelation.qml: RangeError: Maximum call stack size exceeded` when searching for feature in value relation page and selecting one!

**Comment by tomasMizera** [comment]
Inf loop with `Maximum call stack size exceeded` should be sorted in https://github.com/lutraconsulting/input/pull/1524
