### ISSUE TITLE
App gets stuck and synchronization is broken when connection is unstable

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/input#1523]
Download ttester/bigproject and during the download, turn off data and internet connection for a while.
The app stucks and needs to be restarted.

https://user-images.githubusercontent.com/78033756/123599217-a9c2b000-d7f5-11eb-9712-b72b5604ee78.mp4

Similar problem is with synchronization. When connection is lost during it, the synchronization is broken and even restart of app doesn't fix it.

https://user-images.githubusercontent.com/78033756/123600634-25712c80-d7f7-11eb-9fff-2b3c234791c0.mp4

Small problem is with toast notification of connection problem, when there is a `<br/>` sign

**Comment by jozefbudac** [comment]
I was even able to get this error :). I did it when canceling the upload on the broken project. 

![Screenshot_20210628-100127](https://user-images.githubusercontent.com/78033756/123601429-f5765900-d7f7-11eb-91eb-8e25720314e6.png)

The good news is, that the synchronization is not broken forever. It works after a while again.

**Comment by tomasMizera** [comment]
@jozef-budac I will need an application log to continue working on this issue. My device automatically cancels the download/upload.

**Comment by tomasMizera** [comment]
@jozef-budac have you followed the steps stated in this ticket when creating the logs? I can not see any abnormality in them.
