### ISSUE TITLE
Issues in master branch 8a32b03

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1533]
1) opening complex forms are sometimes laggy
2) 'Reuse last value' feature is not working
3) After restarting the app, layer which is not present in the them, can be set as default for recording. This can be very confusing.

https://user-images.githubusercontent.com/83582181/124245443-49e34680-db20-11eb-845e-af27516d42f4.mp4

**Comment by jozef-budac** [comment]
4) if there is a validation problem on a feature and I delete a feature, the validation error remains on the new feature.
Steps to reproduce:
 - open project input-testing/decimals
 - go to default value tab, set 11 into the 2nd field 
 - not delete the feature
 - open new feature and you are not able to save it, even when there is not constrain violated

https://user-images.githubusercontent.com/83582181/124250550-456d5c80-db25-11eb-88c6-43fb6b34e478.mp4

**Comment by jozef-budac** [comment]
5) there is a problem with value relations, that after user searches for value and click on it, it is not set into the field
 Steps to reproduce:
 - open project tomas/VR-Filtering
 - create new feature with all data
 - edit the feature and and in Car-Manufactured search for Audi, and click on the result. 
 - No value is set into the field


https://user-images.githubusercontent.com/83582181/124252974-d5aca100-db27-11eb-96f5-3633325751bf.mp4

**Comment by jozef-budac** [comment]
6) slider widgets for infinite values are working strangely. 
open project input-testing/decimals and go to 2nd tab

https://user-images.githubusercontent.com/83582181/124254675-98e1a980-db29-11eb-9d46-6fa04c441a45.mp4

**Comment by jozef-budac** [comment]
7) issue described in ticket https://github.com/lutraconsulting/input/issues/1502 is there again: 

https://user-images.githubusercontent.com/83582181/124262329-2f19cd80-db32-11eb-8021-fe1ccb97fe72.mp4

**Comment by tomasMizera** [comment]
> 1. slider widgets for infinite values are working strangely.
>    open project input-testing/decimals and go to 2nd tab
> 
>  20210702_113350.mp4

There is a ticket for this one: https://github.com/lutraconsulting/input/issues/1516

**Comment by jozef-budac** [comment]
Closing this tiket:
1) performance problem on older phones
2) fixed in latest master
3) fixed in latest master
4) separate ticket https://github.com/lutraconsulting/input/issues/1560
5) separate ticket https://github.com/lutraconsulting/input/issues/1559
6) separate ticket https://github.com/lutraconsulting/input/issues/1516
7) separate ticket https://github.com/lutraconsulting/input/issues/1502
