### ISSUE TITLE
Issues in 0.9.9 - 2.15.210702185053 testflight

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1536]
1) terms and conditions on SignIn page are not working (404 error)

2) "learn more" on subscription page still doesn't work (404 error)

3) subscription doesn't work for individial same as professional

4) there is sporadic "undo - undo" on home screen
![IMG_0051](https://user-images.githubusercontent.com/83582181/124434545-49db8480-dd74-11eb-91ed-bc5681e0795b.PNG)
I don't have way to simulate it. It just randomly appears. I suspect, it can be something with subscription, because I tried to subscribe multiple times and now this errors appears randomly when I am working with INPUT

5)  "Reuse last value" feature doesn't work. After first record, the check boxes disappears.

6) the infinite range slider doesn't work

7) "Number is outside of specific range" - is not set for translation

**Comment by jozef-budac** [comment]
8) for relations, I can't add photo for referencing feature. Steps:
 - open input-testing/tc05_relations project
 - in 'pois' layer open a feature and edit it
 - add to attached photos
 - try to take a picture with camera or choose from a gallery
 - the photo widget is not updated with a picture

**Comment by sklencar** [comment]
Points 1, 5, 8 addressed in https://github.com/lutraconsulting/input/pull/1549

Some notes to reported issues:
2. What link should be used instead?
3. Please, provide more info about the issue. Is it a case of https://github.com/lutraconsulting/input/issues/1475 ? 	
4. Regarding "undo - undo" on home screen- It can be replicated by shaking an iOS device - you can read more and change the setting in Settings -> accessibility -> Touch -> Shake to undo
6. The infinite range slider doesn't work - QML Slider has limitation and does not work properly with wide range and small step size. Such case suppose to be rather rare and as Martin suggested, this bug can be ignored for a time-being. It would require custom implementation of slider widget.
7. I could not find that specific string, however found similar "Number is outside of specific range" which seems to have translation and is wrapped in translation function. Can you please be more specific
8. Image default path is set incorrectly(home/tomasmizera/lutra/projects/qgis-projects/transportation) - photo field config should be fixed for a project input-testing/tc05_relations. However, notification has been added if an error occurs during photo/gallery image handling.

9. and 10. kept for another round.

**Comment by wonder-sk** [comment]
For 9+10 there's now a ticket #1550

**Comment by jozef-budac** [comment]
3. Please, provide more info about the issue. Is it a case of #1475 ?
-> yes it is

7. I could not find that specific string, however found similar "Number is outside of specific range" which seems to have translation and is wrapped in translation function. Can you please be more specific
-> it is this one:
![Screenshot_20210719-095128](https://user-images.githubusercontent.com/83582181/126123117-2f6cc531-5d14-4ac1-be80-5c7f7041caa0.png)

**Comment by jozef-budac** [comment]
Closing this issue as:
1) fixed in latest version
2) https://github.com/lutraconsulting/input/issues/1489
3) https://github.com/lutraconsulting/input/issues/1536
4) configuration problem 
5) fixed in latest version
6) https://github.com/lutraconsulting/input/issues/1516
7) added into ticket: https://github.com/lutraconsulting/input/issues/1486
8) configuration problem but there was also small fix with notification for more clarity
9) https://github.com/lutraconsulting/input/issues/1550
10) https://github.com/lutraconsulting/input/issues/1550
