### ISSUE TITLE
Forms not saved when a field exceeds the character length

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1541]
In QGIS, fields length (e.g. a text field with 120 character length) is not required when user fills the form, i.e. user can add a 200 characters length inside the field and QGIS happily saves the Geopackage. But in Input, forms do not get saved.

To replicate the issue:
1- Create a project with a layer that has a field with 2 characters length
2- Set the widget type to value relation
3- Within the value relation, add some values which exceed 2 characters length
4- In QGIS, you can select the values and save the form
5- In Input, when you edit the existing features and save the form, when you go back, your values have disappeared

**Comment by wonder-sk** [comment]
Related to #1507

**Comment by tomasMizera** [comment]
@saberraz is this ticket only about value relations? In QGIS 3.20 f.e. in text field I am not able to write more letters than set when creating an attribute

**Comment by tomasMizera** [comment]
This ticket will be fixed in plugin, see: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/296
