### ISSUE TITLE
Invalid project removes the possibility to sync

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1547]
If I have an invalid Input project (e.g. having two QGIS projects), it becomes impossible to sync the project again.

**Comment by saberraz** [comment]
Steps to replicate:
1- Create a basic project using the plugin
2- Download it from Input
3- On desktop, add another QGIS project to the same folder and sync
4- Sync your project from mobile
5- It becomes greyed out
6- Remove the additional QGIS project from the folder and sync
7- No way of syncing the new changes back to the device. The only way is to delete and re-download the project

**Comment by tomasMizera** [comment]
What is the expected behavior here? Project can be synchronized and becomes valid right after synchronization?

**Comment by saberraz** [comment]
Correct. I think the syncing should be independent of the project validity check. Any project can sync, but only valid projects can be opened in the app
