### ISSUE TITLE
Add "Reference relation" widget

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1550]
For linked features that have "reference relation" widget assigned to an attribute in form configuration, Input currently only shows a simple text edit with the linked feature ID. It is desirable to have the "reference relation" widget implemented, so that:
- user can see the textual representation of the linked feature, not just its ID
- user can click on the linked feature to open its attribute form
- [in edit mode] user can open the list of features and change the link to some other feature
- [in edit mode] user can unlink existing feature (if "Allow NULL value" option is checked in the widget config)

It would be similar to Value Relation widget, with few extra features...

**Comment by tomasMizera** [comment]
@wonder-sk by `Allow NULL` did you mean the _QGIS not null constraint_ or the _QGIS Relations reference allow null_ option?


![Screenshot from 2021-07-20 13-21-16](https://user-images.githubusercontent.com/22449698/126315763-0cda2b79-9250-465e-9dfe-f43fd2b96eae.png)
