### ISSUE TITLE
Remove HTML tag in the toast message

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1558]
There is HTML tag visible in the toast message

Also the log in page looks very strangely, when using wrong URL for mergin server.
There is update button and there is a text overlay on the top of the page

![Screenshot_20210720-103005](https://user-images.githubusercontent.com/83582181/126288678-885bf154-e613-49b7-a09f-ed346c389663.png)

**Comment by tomasMizera** [comment]
Duplicate with #1680 there html tags all around the place, they are coming from server
