### ISSUE TITLE
Value not set in the value relation widget

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1559]
There is a problem with value relations, that after user searches for value and clicks on it, it is not set into the field
 Steps to reproduce:
 - open project tomas/VR-Filtering
 - create new feature with all data
 - edit the feature and and in Car-Manufactured search for Audi, and click on the result. 
 - No value is set into the field

https://user-images.githubusercontent.com/83582181/124252974-d5aca100-db27-11eb-96f5-3633325751bf.mp4

**Comment by jozef-budac** [comment]
It is also described in https://github.com/lutraconsulting/input/issues/1533 point 5

**Comment by tomasMizera** [comment]
Closing, will be fixed in: https://github.com/lutraconsulting/input/issues/1559
