### ISSUE TITLE
Constrain validation problem

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1560]
Version: 57994275d071fe6efe7e4a2f830e9364c8cdabc2
OS: Android arm64-v8a

if there is a validation problem on a feature and I delete a feature, the validation error remains on the new feature.
Steps to reproduce:
 - open project input-testing/decimals
 - go to default value tab, set 11 into the 2nd field 
 - now delete the feature
 - open new feature and you are not able to save it, even when there is not any violated constrain 
 
https://user-images.githubusercontent.com/83582181/124250550-456d5c80-db25-11eb-88c6-43fb6b34e478.mp4

**Comment by tomasMizera** [comment]
Is this still in the app?

**Comment by jozef-budac** [comment]
yes, it is still there in latest version
