### ISSUE TITLE
Input crash when a value relation widget is in a QGIS project (only on iphone)

### ISSUE THREAD

**Issue by arno974** [lutraconsulting/input#1565]
When using on iphone (OS : 14.6 - tested on two differents iphone) a QGIS project with a value relation widget (same as here - https://help.inputapp.io/howto/settingup_forms_valuerelation), Input crash when pressing "add point" button.

The same project on Android works perfectly fine. Others projects without this value relation widget work perfectly fine on the same iphone.

The error in the input log file is :
Warning invalid data provider delimitedtext.
1 unavailable layers found

**Comment by saberraz** [comment]
This is related to two different issues:
- https://github.com/lutraconsulting/input/issues/1257
- https://github.com/lutraconsulting/input-sdk/issues/40

The workaround:
- The latest TestFlight (0.9.9 https://testflight.apple.com/join/JO5EIywn should address the crash)
- We do not yet support delimited text provider in iOS. Best to use OGR virtual layer instead (https://gdal.org/drivers/vector/csv.html#reading-csv-containing-spatial-information)

**Comment by arno974** [comment]
Thanks, I will try your solutions.

**Comment by saberraz** [comment]
The crash has been addressed. So, I am closing this ticket. Feel free to re-open or file a new one.
