### ISSUE TITLE
Images in HTML preview panel not resized

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#158]
It is easy to break the preview panel with custom MapTip.

**Comment by wonder-sk** [comment]
that's when using HTML map tip or image map tip? With HTML I have not found a way to auto-resize images, that's why I have added the image map tip (in addition to html and "fields")

**Comment by sklencar** [comment]
It's with HTML map tip. Seems like (max) width/height properties of img are not processed well. Even with no 'auto' value or shrinking max size an image still looks the same.

Here is a snippet of HTML map tip for image:
`
<img style="
  display: block;
  max-width:100px;
  max-height:100px;
  width: auto;
  height: auto;
" 
src='file:///[%@project_folder%]/[% "image" %]'/>
`

**Comment by wonder-sk** [comment]
This can be worked around by using dedicated "image" map tip (which auto-scales images)
```
# image
file:///[%@project_folder%]/[% "image" %]
```

**Comment by saberraz** [comment]
@sklencar I have not seen this issue. Can we close this?

**Comment by saberraz** [comment]
@sklencar I am closing...feel free to reopen if you have an issue.
