### ISSUE TITLE
Notification when opening project produced warnings (e.g. invalid layers)

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1580]
Right now, if there are some map layers that Input is unable to load, the user gets no feedback that things went wrong and why. It would be good to have a simple (non-modal) notification in the top part of the screen saying that there were some issues - and user can decide to either ignore the problems by closing the notification (tapping "x" button) or inspect the problem(s) by tapping a button (e.g. "show more") - which would open a new page with more details (which layer(s) failed to load, and what was the reason).

It would be good if we could also migrate the PROJ error dialog (e.g. when missing a grid shift file) to this kind of notification to make it less invasive.

**Comment by saberraz** [comment]
Duplicate of this: https://github.com/lutraconsulting/input/issues/1263?

**Comment by wonder-sk** [comment]
Fixed in #1763
