### ISSUE TITLE
Field is not saved when scrolling too far

### ISSUE THREAD

**Issue by merlindupre** [lutraconsulting/input#1592]
Hi,
I'll start by saying that Input is awesome.
I am experiencing an issue when filling a long form. When I fill information in a field, the information is lost if I scroll too far, as you can see in this clip:

https://user-images.githubusercontent.com/88735158/128910627-658a7949-f157-4fc9-9983-283518248b26.mp4

**Comment by saberraz** [comment]
Hi @merlindupre 

Thanks for your feedback and reporting an issue.

- Could you first check if you are using the latest version of Input (v. 0.9.9). There has been a similar issue which was fixed recently.
- Also, could you check with your Fields (under Layer Properties > Fields) for this layer and see the Length of the field. It is very likely to be related to https://github.com/lutraconsulting/input/issues/1541

**Comment by merlindupre** [comment]
Hey,
I confirm that I am using v0.9.9.
The length of the field is set at 0. Maybe I wasn't clear but I usually have no problem filling this field and saving it. The issue is only when I scroll too far down.
