### ISSUE TITLE
Handling the project after it was removed in the mergin

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1594]
After the project is removed in the mergin, in input it look like it is still present there.
When I do some changes and want to synchronize, I get error bellow.

Shouldn't have the INPUT user to upload the project to mergin as a new project? 

![236135620_386302236201423_5948909006544164902_n](https://user-images.githubusercontent.com/83582181/129011930-23bb5337-7783-4b71-95b1-0a4e1b964316.png)

**Comment by wonder-sk** [comment]
Related to #1008 and #1102

**Comment by wonder-sk** [comment]
> Shouldn't have the INPUT user to upload the project to mergin as a new project?

Yes, Input should detect a project does not exist on the server anymore - and offer upload of the local project.

**Comment by jozef-budac** [comment]
Closing as duplicate of  #1008 and #1102
