### ISSUE TITLE
Set default attribute values for new features

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#16]
A checkbox (original idea from qfield) so that he current value will be used as default for the future edits.

**Comment by wonder-sk** [comment]
This is a useful feature, but having checkboxes next to attributes all the time is probably visually annoying... what if the checkboxes were hidden by default and only shown when a specific button is toggled?

**Comment by saberraz** [comment]
An option would be: when you long press you get a pop up choice ‘use this value as default for new features’

**Comment by saberraz** [comment]
We already support Default in attribute table.
