### ISSUE TITLE
Ensure free tier has the correct, current name

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#1600]
The free tier on Mergin was recently renamed from *community* to *free*.

We should do a search through Input for any references and update them accordingly.

**Comment by tomasMizera** [comment]
I could not find any reference to _community_ in Input 

<img src="https://user-images.githubusercontent.com/22449698/134637734-2dde33e1-8c90-40ca-8484-467c333e6757.jpeg" width=300>
