### ISSUE TITLE
remove qtquickcontrol 1 from qml

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#1621]
to be able to activate the hidpi auto scaling (and get rid of `utils.dp` from qgsquick) we need to use solely qtquickcontrols2 
so no treeview or tableview

**Comment by tomasMizera** [comment]
We are using `Calendar` component from qtquickcontrols1 and there is no equivalent in controls2, we will either need to find new one somewhere or write our own.

**Comment by PeterPetrik** [comment]
all but calendar #1774 is fixed.
