### ISSUE TITLE
Issue with the 1-to-many relations within 1-to-many relations

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1624]
I have set up a survey as follows:
1- A survey point: showing the location of tree survey
2- Visit (non-spatial table): to be filled in by the surveyor for each visit to a tree: e.g. visit 2019, 2020, etc with some measurements.
3- Photo (non-spatial table): for each visit, the surveyor might want to take multiple photos.

The project works as expected in QGIS, but in Input only relations between 1 and 2 works. The relation between 2 and 3 does not show up at all.

See the attached project:
[tree-survey.zip](https://github.com/lutraconsulting/input/files/7104771/tree-survey.zip)

**Comment by tomasMizera** [comment]
+ relation reference button from `photos` layer do not lead to parent when I click on it
