### ISSUE TITLE
Support expression constraints

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1627]
Not sure if we ever supported this, but after attribute controller refactoring we now do not support expression constraints.

 
![image](https://user-images.githubusercontent.com/22449698/132473037-aa8c9a3e-ac72-4d66-980c-ae4310d0036d.png)

**Comment by wonder-sk** [comment]
Hmm we should be supporting expression constraints too :-)

**Comment by tomasMizera** [comment]
Ah, you are right, false alarm!
