### ISSUE TITLE
About Translator cannot edit some wrong translation

### ISSUE THREAD

**Issue by dfwsbylwy** [lutraconsulting/input#1629]
OK, Thank you. However, there is still a problem. @PeterPetrik 
My ID is dfwsbylwy in https://www.transifex.com, its authority is **Translator**, and cannot edit some wrong translation. Please increase the permissions of my ID to **Reviewers**. Then I can correct a few wrong translations, which were my previous translation errors. Please forgive my bad English.

_Originally posted by @dfwsbylwy in https://github.com/lutraconsulting/input/issues/1623#issuecomment-916803060_

**Comment by saberraz** [comment]
I have upgraded your role to Reviewer. Could you try again on Transifex?

**Comment by dfwsbylwy** [comment]
its ok, thank you.
