### ISSUE TITLE
Automatic APK build to publish

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#163]

**Comment by IzzySoft** [comment]
Best would be to tag releases and attach the APK to its resp. tag :smiley:

**Comment by PeterPetrik** [comment]
Fixed: Now on every commit/tag/pull request inputapp-bot creates APK (signed if PR from this repository), uploads it to dropbox and creates comment on commit/pull with the link. The APK are not uploaded automatically on google play, this has to be done manually

**Comment by IzzySoft** [comment]
@PeterPetrik what about attaching the APK to `releases/`? Makes them easier to find. There's not even a note in the Readme on where to find them (at least not yet).
