### ISSUE TITLE
Always show GNSS accuracy reading

### ISSUE THREAD

**Issue by DunktheLunk** [lutraconsulting/input#1660]
Currently Input doesn’t display the GNSS accuracy reading unless you turn on ‘GPS accuracy’ and set the ‘accuracy threshold’ to a very low value (eg 0m). Then, however, you get a large banner with a lot of text which uses up a lot of screen space (especially if using a mobile or smaller survey device). It would be very useful to have a setting to permanently display just the accuracy reading (in the map view). Perhaps then the large banner could pop up if the user took a point but the accuracy was above the set value. Basically saying are you sure you want to take this point?

**Comment by saberraz** [comment]
I am closing this in favour of this #1679
