### ISSUE TITLE
Authentification failed on Iphone with a custom mergin server

### ISSUE THREAD

**Issue by arno974** [lutraconsulting/input#1670]
As I don't know if it is related to mergin or Input I have specified the bug in both github repo (https://github.com/lutraconsulting/mergin/issues/19).

The problem is while the authentification works on an iPhone using the public mergin server (public.cloudmergin.com/) it does not work using a "private" mergin server (a mergin server on my own server). I have tried to do it on two different iPhone and same result : "Incorrect username or password". The same credentials works when using an android phone.

Have you ever noticed such problems ?

**Comment by wonder-sk** [comment]
Could it be that you have not included a slash at the end of the URL? See https://github.com/lutraconsulting/mergin/issues/8#issuecomment-871625539

**Comment by saberraz** [comment]
Related to #1673

**Comment by arno974** [comment]
Thanks for your solution, the error was probably due to the slash and the fact that we must click again on the pencil !
It is all good now !

**Comment by arno974** [comment]
Thanks for your solution, the error was probably due to the slash and the fact that we must click again on the pencil !
It is all good now !
