### ISSUE TITLE
Error copying from gallery

### ISSUE THREAD

**Issue by djambar** [lutraconsulting/input#1675]
Hi,

On IOS, I get this error when trying to copy an image from the gallery where of course the image is present.

![error_copy_from_gallery](https://user-images.githubusercontent.com/7245422/135730409-723bc144-3f67-4bdf-99ae-742d5fcd9cc5.jpeg)

**Comment by saberraz** [comment]
Hi @djambar 
It looks like your folder path is not set correctly. Would you be able to share the project with me on Mergin. My username is saber.

**Comment by djambar** [comment]
Hi Saber,

Thanks a lot for your reply.
Sorry, could you tell me how to share my project with you in Mergin ?
I don’t see the menu for that purpose :



Best regards,
Patrick
Envoyé de mon iPhone

**Comment by djambar** [comment]
Hi @saber

I have Sharif m’y projectif with you.
Best regards

Envoyé de mon iPhone

**Comment by saberraz** [comment]
You need to remove the content of the path for the Attachment widget:
![image](https://user-images.githubusercontent.com/2649047/135765535-231779dd-f24e-4836-bddc-4fdd82f8a1a0.png)

Feel free to give me Write access on Mergin and I can push the correct version.

**Comment by saberraz** [comment]
Try to sync the project. I have made the changes and it should work now.

**Comment by djambar** [comment]
Thanks a lot. I gave you the write access.

Envoyé de mon iPhone

**Comment by saberraz** [comment]
I fixed the issue. If you synchronise the project on your phone, it should work well: both for taking photos or adding from gallery.

**Comment by djambar** [comment]
Thks for your help. I have synchronised the project, but it is still impossible to load a picture from the gallery :




Envoyé de mon iPhone

**Comment by saberraz** [comment]
Could you try to sync the project and attach the photos one more time?

**Comment by djambar** [comment]
Jolly Good ! It works fine now !
Congrats !

Envoyé de mon iPhone

**Comment by saberraz** [comment]
You had some settings for Project home under your Project Properties. This too, should be left blank.

**Comment by djambar** [comment]
Well noted. Thks.

Envoyé de mon iPhone
