### ISSUE TITLE
Support for Dark mode

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1677]
With dark theme, some elements are not readable in INPUT. 
As dark theme is more popular this days, it would be nice to have this fixed.

![Screenshot_2021-10-04-08-49-10-922_uk co lutraconsulting](https://user-images.githubusercontent.com/83582181/135806024-e068d81e-c540-42b9-b23f-f2f149406ec8.jpg)

**Comment by tomasMizera** [comment]
Duplicate #1535
