### ISSUE TITLE
GPS panel

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1679]
A panel to show GPS status and accuracy. 

1- There could be two mode:
  - A summary mode to be displayed over the map 
![image](https://user-images.githubusercontent.com/2649047/135809385-4873b219-7d8e-4684-826b-7d93e95cbcc7.png)

  - A full mode to show more details
![image](https://user-images.githubusercontent.com/2649047/135809497-29b5bff0-18f8-4884-83f2-49b133b269c0.png)

(screenshots are from GPS Status app: https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en)

2- The panel should support both internal GPS chip and external GPS

**Comment by DunktheLunk** [comment]
I do think it is important to have the accuracy displayed on the map. For example if a user is visiting, checking and/or updating existing assets in an area where there is potential for poor GNSS signal (eg woodland or an urban canyon) it will be important for the user to know the accuracy they have so they can be confident they are at the correct asset (especially if the assets are located very close to one another. 

Attached is how the Leica Zeno system displays the accuracy. If it is outside the limit it will be coloured red. 
.
![Zeno](https://user-images.githubusercontent.com/91281747/135875796-602a8ea2-04b8-410d-a6e1-d5edcd2f68b3.png)

**Comment by jozef-budac** [comment]
Probably related to this ticket: https://github.com/lutraconsulting/input/issues/279
