### ISSUE TITLE
Form survey - udpate failing

### ISSUE THREAD

**Issue by djambar** [lutraconsulting/input#1702]
After synch, The field _nom du projet_ appears in Input  (with IOS) while I have deleted it from QGIS.

**Input fields**
![image1 (2)](https://user-images.githubusercontent.com/7245422/136714931-5f50ef35-3d79-4506-a06d-5edbf5c6a828.jpeg)

**QGIS fileds**
![field param](https://user-images.githubusercontent.com/7245422/136715030-45b5d6b9-bd30-4302-a2b0-84df8cad3824.PNG)

**Comment by djambar** [comment]
Hi Martin,
Thanks for your quick reply. I have shared my project with you.
Have a nice day 
Patrick
Envoyé de mon iPhone

**Comment by wonder-sk** [comment]
Maybe you have not saved or uploaded your changes? Because the "nom du projet" attribute is still in the layer when I downloaded it from Mergin:

![image](https://user-images.githubusercontent.com/193367/136755957-bcc126f1-84be-4407-81d2-dd8765f19ebe.png)
