### ISSUE TITLE
Precision is not applied to the range field

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1744]
When I insert a number with more digits after the dot then precision allowes, it is still stored in this form.

Steps to reproduce:
1) open project input-testing/tc05_decimals
2) in tab "Range Edit - Min/Max) write a number with many digits after the dot (like 2.3243243254) into a field with lower precision and press save (you need to fulfill a hard constrain in Default values tab firstly) 
3) open the feature again and it is there with all the digits after the dot.

![precis](https://user-images.githubusercontent.com/83582181/140316627-b7a2c7cc-488b-425e-abe6-e4931c7c1b90.png)

**Comment by tomasMizera** [comment]
Already mentioned in #1646
