### ISSUE TITLE
Change MY PROJECTS and ALL PROJECTS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#175]
See the gdoc for more info.

Or something along those lines.  A couple of minor improvements:
 - [x] using different tabs for local, private, shared with me and public project
 - [x] adding search project toolbar
 - [x] adding user profile info (show mergin storage, etc)
- [x] update api with namespace according API (download, fetch, upload, etc..)

**Comment by PeterPetrik** [comment]
merged: https://github.com/lutraconsulting/input/pull/292
