### ISSUE TITLE
No error shown when adding/editing/removing feature fails

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1797]
If user got into some trouble and changes are not getting committed for some reason, this is only logged to the diagnostic log, but otherwise user gets no warning at all. This is not a very common situation, but when it happens, it's really bad...

We should show a big warning that changes failed to save, it would also make sense to not close the form where the add/edit/remove action was triggered.

Failed addition of a new feature:
```
2021-12-07T09:13:13.205Z QGIS : Warning: Commit errors:
ERROR: 1 feature(s) not added.

Provider errors:
OGR error creating feature -3: failed to execute insert : attempt to write a readonly database
2021-12-07T09:13:13.206Z QGIS Input: Error: Could not save changes. Rolling back.
2021-12-07T09:13:13.207Z QGIS OGR: Warning: Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()
```

Failed removal of a feature:
```
2021-12-07T09:38:28.191Z QGIS : Warning: Commit errors:
ERROR: 1 feature(s) not deleted.

Provider errors:
OGR error deleting feature 47: sqlite3_exec(DELETE FROM "field_notes" WHERE "fid" = 47) failed: attempt to write a readonly database
2021-12-07T09:38:28.191Z QGIS Input: Error: Could not save changes. Rolling back.
2021-12-07T09:38:28.192Z QGIS OGR: Warning: Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()
```

Failed edit of a geometry:
```
2021-12-07T09:40:27.627Z QGIS : Warning: Commit errors:
ERROR: 1 geometries not changed.
ERROR: 1 attribute value change(s) not applied.

Provider errors:
OGR error setting feature 47: failed to execute update : attempt to write a readonly database
OGR error setting feature 47: failed to execute update : attempt to write a readonly database
2021-12-07T09:40:27.628Z QGIS Input: Error: Could not save changes. Rolling back.
2021-12-07T09:40:27.658Z QGIS OGR: Warning: Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()
```

**Comment by PeterPetrik** [comment]
@wonder-sk do you have an example and short reproduce steps how to emulate such action easily?

**Comment by wonder-sk** [comment]
Yeah one can follow the steps from #1798 to get to broken state...

**Comment by wonder-sk** [comment]
For design of the error dialog, this is a good source of inspiration - https://www.creativepixelmag.com/awesome-flash-message-ui-designs-examples/

We don't need something very fancy - we could have design similar to this:

(it may be worth adding both failure and success popups while at it)

![image](https://user-images.githubusercontent.com/193367/148086394-eaca19e9-129e-450c-841e-cfa3b32bfb77.png)

or this

![image](https://user-images.githubusercontent.com/193367/148086492-aef8b9c5-6232-43a6-a423-3663621965b0.png)

or this

![image](https://user-images.githubusercontent.com/193367/148086839-bb137637-fcd6-42cf-b5e6-af5719594bfb.png)

**Comment by tomasMizera** [comment]
@wonder-sk how about reusing the banner component we already have? We might change its icon to `X` and add some error text together with link to documentation? 

I also have several more questions about this:
 - When would you show this message? Immediately after this issue happened or when user tries to sync?
 - What can user do with that? Is it just dead end and he/she needs to go back to QGIS to fix it? Or maybe tell user to restart the app?
 - Can we detect this sooner? Maybe in plugin and inform user that he/she will not be able to create/delete features?
 - With the success icon, do you also want to show it or just have it for some future use?

**Comment by wonder-sk** [comment]
> how about reusing the banner component we already have? We might change its icon to X and add some error text together with link to documentation?

Yeah we could do that as well...

> When would you show this message? Immediately after this issue happened or when user tries to sync?

I would show it immediately, because at the time when user pressed Save we know we're unable to even write the change to the local storage...

> What can user do with that? Is it just dead end and he/she needs to go back to QGIS to fix it? Or maybe tell user to restart the app?

In theory the reason could be anything, maybe even a mis-configured form, maybe some data corruption in the local storage, maybe something bad happened during the sync... Right now I am aware of the scenario described in #1798 which can cause this error and simply restarting the app may work, but in other cases that may not be the solution...

> Can we detect this sooner? Maybe in plugin and inform user that he/she will not be able to create/delete features?

In the particular case of #1798 for example we can't detect that in the plugin... When we know some scenarios where things could get check beforehand in the plugin, then agreed, it would be best to get the plugin to issue warnings about that.

> With the success icon, do you also want to show it or just have it for some future use?

Right now we don't really need the "success" dialog, so we could keep it for future use or just omit implementation of it for the time being...
