### ISSUE TITLE
Some functionality broken after sync that created conflict file of a gpkg

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#1798]
Steps to reproduce:
1. create a project with a geopackage that is going to break geodiff's rebase (e.g. add a custom trigger)
2. open the project in Input, modify the geopackage (e.g. add a feature)
3. open the project elsewhere (e.g. in qgis plugin or other input) and also update the geopackage (but make sure not to update the QGIS project if using qgis plugin)
4. sync the project in Input - this should cause creation of a conflict file with local changes and the server version will replace the local changes

After these steps, some things will not work:
- adding/editing/removing features in that geopackage will be broken
- map refresh may sometimes show and sometimes not show the features from the geopackage (broken access to spatial index)

If user restarts Input, these issues are gone (switching to another project and back should work too).

It seems that OGR provider still keeps connection to the original DB file that got renamed to a conflict copy, at the same time there's a new file with that name but different content... and therefore things break. Probably reloading QGIS project after a conflict file got created will fix the issue.

**Comment by tomasMizera** [comment]
@wonder-sk I have created ticket months ago with similar problem as you describe in the second point.:

> map refresh may sometimes show and sometimes not show the features from the geopackage (broken access to spatial index)

It is ticket https://github.com/lutraconsulting/input/issues/1124, here when I create a feature, it is sometimes visible, sometimes not and one can not click on it. However, mentioned problem in that ticket is reproducible each time and restarting app does not help. Do you think it can be somehow connected to this issue?

**Comment by wonder-sk** [comment]
> Do you think it can be somehow connected to this issue?

Just checked #1124 and fortunately(?) it's an unrelated issue :slightly_smiling_face:
