### ISSUE TITLE
IMPUT Armv7 version doesn't start

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1824]
On Armv7 architecture, INPUT doesn't start
Here you can find log from ADB

[fulllog.txt](https://github.com/lutraconsulting/input/files/7683557/fulllog.txt)

**Comment by PeterPetrik** [comment]
@jozef-budac this is installed from GP or via our APK?

**Comment by PeterPetrik** [comment]
@jozef-budac can you test against latest master?
