### ISSUE TITLE
Capture lines - new approach

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#185]
when record is pressed for line survey layer, toolbar is modified to contain:
1. confirm (opens feature panel)
2. cancel (cancels the whole session)
3. use gps location (centers map to gps)
4. add point - will add new point at the end of the line
5. undo last point - will remove the most recently added point (initially disabled)
6. enable/disable streaming - when turned on, "add point", "undo last point" and "use gps location" buttons are not available and a new point is added automatically every X seconds as configured.

This could be extended also to polygon capturing - the only difference would be that the last and first point would be connected together to form a polygon.

**Comment by wonder-sk** [comment]
Fixed by #195

**Comment by Mikester-Calgary** [comment]
When I record a line it will not record my motion.  I have no option to enable/disable streaming only manually Add Point as I move.  My Line rec interval is 3 s.  What am I missing?

**Comment by saberraz** [comment]
You need to press and hold the GPS icon at the bottom left to switch to Streaming.

**Comment by Mikester-Calgary** [comment]
Thanks.  Sorry Sab.  Missed that somehow on the instruction page.

**Comment by saberraz** [comment]
No problem. It is not very obvious and there is a ticket to make it a bit more visible:
https://github.com/lutraconsulting/input/issues/516
