### ISSUE TITLE
Calendar and translations

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#1865]

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/input/blob/b9e0cc64ed048f8ac6a4617a7787d028c9ece1d5/app/qml/components/DateTimePicker.qml#L164

we translate full weekdays/monthts but then clip 0-3 from translated text. Is it standard way how to do the calendar?

**Comment by tomasMizera** [comment]
We could use `model.shortName` from the calendar for days and full names of months or again `model.month` from calendar model

**Comment by PeterPetrik** [comment]
arer those translated?

**Comment by tomasMizera** [comment]
Well, it is used in the row for week days and they are translated. However, It is not documented anywhere though :/  I only found that it uses QLocale. https://doc.qt.io/qt-5/qlocale.html#FormatType-enum

**Comment by tomasMizera** [comment]
![image](https://user-images.githubusercontent.com/22449698/146914977-c7729a8b-60e1-43d7-8f08-e9c2a8ec5c76.png)
Note that it only affects the header in the calendar
