### ISSUE TITLE
Save photo in subdirectory 

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#1880]
If you try to save photo into separate directory that does not exists, it fails with "Cannot copy the photo to the working directory"
As workaround you need to create empty directory and sync it to mergin>input

related: https://github.com/lutraconsulting/input/issues/1575#issuecomment-889841033

**Comment by tomasMizera** [comment]
Duplicate of https://github.com/lutraconsulting/input/issues/1611
