### ISSUE TITLE
Check for new translations strings in CI

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#1885]
When I create PR with some new translation strings I do not always recall to generate translations strings.

Let's add CI workflow that would check if there are strings to be uploaded for translation. In that case we will not need to release translations manually and users won't see failing job in readme.

**Comment by PeterPetrik** [comment]
Not sure, we also do not want to confuse translators to do translations after each merged PR. My preference is to manually update english translation file ~week before release, so they have time to translations.
