### ISSUE TITLE
Horizontal and vertical accuracy appears NAN when connected to the Bluetooth GPS device

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1887]
I am testing https://github.com/lutraconsulting/input/pull/1886 and when I am connected to the external GPS, the horizontal and vertical accuracy appears as nan

**Comment by jozef-budac** [comment]
It behaves the same using android device as external GPS provider

![screenshot_20220119-100522](https://user-images.githubusercontent.com/83582181/150099624-8a97ee77-3164-44e4-aee7-0d1f9c3e9183.png)

**Comment by PeterPetrik** [comment]
@tomasMizera this is fixed?

**Comment by tomasMizera** [comment]
@PeterPetrik no, not yet
