### ISSUE TITLE
Calendar widget in forms not showing the selected date

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#190]
When adding a new date or editing an existing date, the calendar widget does not highlight the selected date. It changes it in the form, but the date is not highlighted in the calendar.

**Comment by sklencar** [comment]
Can you provide an image how it is shown in your device? On A6 and A7, its pretty much as following:

![screenshot_2019-03-08-10-29-35-958_uk co lutraconsulting](https://user-images.githubusercontent.com/6735606/54020301-bab30780-418d-11e9-9ed9-05ff00b2c940.png)
