### ISSUE TITLE
Stake out window in landscape mode/small screens

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1948]
When I use stake out in landscape mode, the bubble appears to have the top/bottom cut off. Also, on small screen, it does not show the distance.
![image006](https://user-images.githubusercontent.com/2649047/154668297-edb9f93b-bd05-4acb-9163-354df1e3cf51.png)

**Comment by tomasMizera** [comment]
Is this a blocker @saberraz ?

**Comment by wonder-sk** [comment]
by the way, the screenshot is from Galaxy Tab Active 3 Tablet (the resolution is 1920 x 1200 pixels)

**Comment by saberraz** [comment]
@tomasMizera no. Let's tackle this and other stake out issues reported by user for another release.

**Comment by tomasMizera** [comment]
It is actually not only in landscape mode. There are issues when device has small screen also in portrait mode. It needs to be revisited
