### ISSUE TITLE
Auto-focus for QR code scanner

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1949]
Currently, it is difficult to get a code scanned if you don't point the camera at the right distance. Would be good to have it so that it auto focuses on the image.

**Comment by saberraz** [comment]
https://github.com/Redth/ZXing.Net.Mobile/issues/414

**Comment by PeterPetrik** [comment]
it happens when you want to take code from printed paper, works ok-ish from QR code on the screen.

**Comment by tomasMizera** [comment]
https://doc.qt.io/qt-5/qml-qtmultimedia-camerafocus.html

**Comment by PeterPetrik** [comment]
We use native camera, so qtmultimedia will help us?

**Comment by tomasMizera** [comment]
We do not use native camera for QR code scanner.
