### ISSUE TITLE
IOS - shadow of previous polygon in stream mode while recording another polygon feature  

### ISSUE THREAD

**Issue by PatrikMizera** [lutraconsulting/input#1958]
Input: 1.3.0 
IOS 15.1 

1. record feature in polygon layer or Multipolygon layer. 
2. record polygon (or Multipolygon) feature in stream mode (holding down GPS button) and you will see shadow glitch of 1. polygon you just did.

https://user-images.githubusercontent.com/94351263/154962334-b0d27f8d-5801-4614-b642-b7cf57df07a6.MP4

**Comment by saberraz** [comment]
It is not just the polygon, it can be the rubber-band too.
