### ISSUE TITLE
Problem with Android 5

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#196]
The latest release (0.2.3) crashes upon opening in Android 5.

**Comment by mixedbredie** [comment]
I can confirm this on Galaxy Tab4 8" running Android 5.1.1

**Comment by mixedbredie** [comment]
Also crashes immediately (no splash or anything) on Vodafone Tab prime 6 running Android 5.0.1
Google Play did say that this app may not be optimised for my device.
