### ISSUE TITLE
The app keeps hiding on iOS 13.3

### ISSUE THREAD

**Issue by lollisoft** [lutraconsulting/input#1972]
Hi,

I have just installed the app on my iOS iPhone SE with 13.3 that I cannot update on purpose.
I am a developer and may be able to build it and test it myself, if the issue isn't yet known.

https://user-images.githubusercontent.com/3633520/157644559-6f3dd2ef-42af-4d84-8fee-266ff6b8a7f3.mp4

Thanks

Lothar

**Comment by tomasMizera** [comment]
Hi @lollisoft, thanks for reporting the issue! Could you please provide us with some more info and optionally attach a screencast of the issue?

I would be especially interested in knowing:
 - when is the app hidden? At startup? On project load? On some specific project? / Different event?
 - were you able to run it or it just keeps hiding itself?
 - by hiding, do you mean that if you go to [all running applications](https://support.apple.com/guide/iphone/switch-between-open-apps-iph1a1f981ad/ios) you can see Input there?
 - does reinstall help the problem?

Thanks! Your feedback will be much appreciated.

**Comment by saberraz** [comment]
I wonder if we support iOS 13.3. It is almost 2 years old.

**Comment by tastrax** [comment]
Please continue to support older operating systems for a suitable period of time. Many organisations cant churn their devices every few years. IOS 13.3 came out in Dec 2019.

**Comment by saberraz** [comment]
Hi Phil, we try. But the iOS and some degree Android, forces you to update to the latest SDKs and tooling to be able to release the app on their app stores.

**Comment by lollisoft** [comment]
Hi,

it is clear to me that the rules are from device vendors, but indeed they are too rigid toward wasting electronic devices that still do their work.
I am not willing to update for now, but may help finding out what is the problem to implement conditionals for that error.

I am a software developer and if I am able to test it with building it for my device, I may be able to debug it as well. You need to publish for
the newest API, but if the app can be deployed for my phone, then it is only the test devices (resources are not cheap), that you may not
have.

Regards,

Lothar

**Comment by lollisoft** [comment]
There is no time to create one, and also there is no error message. May be there is any in a hidden place I am unaware of. Did you got my short video?

**Comment by PeterPetrik** [comment]
I haven't received any video. can you attach it here?

**Comment by lollisoft** [comment]
Hope you get it :-)

**Comment by PeterPetrik** [comment]
still not, you need to open https://github.com/lutraconsulting/input/issues/1972 and attach the file as attachement

**Comment by saberraz** [comment]
Closed in favour of #1983

**Comment by lollisoft** [comment]
Hi,

I have attached it, but seen that it has been closed. So keep it FYI.

Regards

Lothar

**Comment by saberraz** [comment]
Thanks for the screencast. Let's discuss it in #1983
