### ISSUE TITLE
iOS crash on 12.x and 13.x

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1983]
Some users have been reporting (see #1972 ) issues with earlier versions of iOS. In Android, you can detect the supported versions and do not display it for those on earlier versions.

I am not sure how it is done in iOS but we should not have the option for users to update to the latest version or install it from the App store if it is not supported.

**Comment by PeterPetrik** [comment]
Not working on: iOS iPhone SE with 13.3

**Comment by PeterPetrik** [comment]
@jozef-budac on which iOS OS versions we did tests?

**Comment by tomasMizera** [comment]
We might be missing this one https://developer.apple.com/documentation/bundleresources/information_property_list/minimumosversion

**Comment by saberraz** [comment]
@PeterPetrik we usually test it on the most recent version(s) of iOS. Our phones/tablets are still supported by the latest iOS version and we keep them up to date with Apple iOS upgrades.

**Comment by PeterPetrik** [comment]
Not working: 12.5.5

**Comment by lollisoft** [comment]
When you plan to deploy on older iOS versions like my version, you need testing for that. At least some test devices in pre flight. If you only test on current or latest versions, you risk unpredictable errors. I have XCode 10.3 and if known to be supported with your project, I'll give it a try...

**Comment by PeterPetrik** [comment]
input-sdk change between 1.2.0 and 1.3.0 
https://github.com/lutraconsulting/input-sdk/compare/ios-20211201-22...ios-20220212-36

input change between 1.2.0 and 1.3.0
https://github.com/lutraconsulting/input/compare/1.2.0...1.3.0

**Comment by jozef-budac** [comment]
We tested the latest release on iOS 15.1

**Comment by lollisoft** [comment]
Hi,

I can report that the currently released app version works on my iOS 13.3 on iPhone SE. Now, I may be able to use the app for further testing within the app.

Thank you,

Lothar

![2022-04-22 10 51 41](https://user-images.githubusercontent.com/3633520/164670531-5a28f4e4-fff8-4c6e-ba54-247f1efd82fa.jpg)
![2022-04-22 10 51 51](https://user-images.githubusercontent.com/3633520/164670577-f9f13de3-9827-48ae-8fd7-833caf684b55.jpg)

**Comment by PeterPetrik** [comment]
https://iosref.com/ios

We are planning to support iOS 14+ from next release, which I think effectively means we stop supporting Phone 6 / 6 Plus from 2014. All other devices could upgrade to iOS 15. @lollisoft which iPhone SE do you have, iPhone SE (gen 2)? Is it possible to upgrade to iOS 15?

**Comment by lollisoft** [comment]
> Am 22.04.2022 um 11:23 schrieb Peter Petrik ***@***.***>:
> 
> 
> https://iosref.com/ios <https://iosref.com/ios>
> We are planning to support iOS 14+ from next release, which I think effectively means we stop supporting Phone 6 / 6 Plus from 2014. All other devices could upgrade to iOS 15. @lollisoft <https://github.com/lollisoft> which iPhone SE do you have, iPhone SE (gen 2)? Is it possible to upgrade to iOS 15?
> 
> 

I have a first gen with max amount of memory. I do use these as long as I can. Actually I do not plan to buy a new one. I am not such a guy holding pace with the latest gimmick from vendors :-)
My phone still is capable of supporting me for my needs...
