### ISSUE TITLE
Shorten the namespace display

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1996]
Some users/organisations namespace is long. In Input, it shortens the name from right, so it often results in project names not visible in small screens. We should probably shorten the namespace and display more of the project name.

For example for a project with the following name:
`mylongorganisationnamespace\myprojectwithlongname`

Current case:
`mylongorganisationnamespace\pr...`

Proposed:
`mylo..\myprojectwithlongname`

**Comment by PeterPetrik** [comment]
Lets do `...ace\myprojectwithlongname` as it is trivial in QML
