### ISSUE TITLE
Share (raster) data between project

### ISSUE THREAD

**Issue by arno974** [lutraconsulting/input#2002]
Hi,

It is more a question than an issue. I've looked the documentation  and I didn't found the answer.
I wonder if it's possible to share raster data between multiple Input projects. Let say for example that I have an aerial imagery that is used in many Input projects. Instead of havng to duplicate this aerial imagery can I share the data between different projects ?

Thanks

**Comment by dracic** [comment]
Workaround - create project raster, put there raster data. Raster project folder should be in same dir with other input projects. Load raster from QGIS ../raster/nameofraster. QGIS and Input will use relative path by default. Share and download on Input raster project.

**Comment by saberraz** [comment]
This is very smart work-around @dracic! Let's document it so other users can benefit from it.

**Comment by arno974** [comment]
Thanks @dracic ! Perfect :)
