### ISSUE TITLE
Input immediately closes on launch  

### ISSUE THREAD

**Issue by Simon-Miles-rbwm** [lutraconsulting/input#201]
I am using an Android 8.0.0, Huawei P10 lite. I am finding that I am having to uninstall and reinstall the INPUT app just to get it to work. After initial use, when you go to launch the app again it shows the splash screen then immediately closes.

**Comment by saberraz** [comment]
Hi Simon,

Could you open the app settings and make sure:

- Permissions are set correctly (allowed) for, storage, location, camera and michrophone
- Clear the cache

**Comment by Simon-Miles-rbwm** [comment]
Permissions - all allowed with the exception of Microphone. 
Granted Microphone and cleared cache but still closing.

**Comment by Simon-Miles-rbwm** [comment]
If I clear data, then it starts to work again. However in doing so its asked me for permissions again, lost my connection to Mergin and when inspecting the App Permissions Camera and Microphone and not enabled. Although I granted them when the app opened.

**Comment by saberraz** [comment]
This could be some sort of custom security enforced by your android.

**Comment by Simon-Miles-rbwm** [comment]
If that is the case, it's the only app that its done it to.

**Comment by saberraz** [comment]
We will look at the permissions and make sure, they are set correctly to avoid the crash.

**Comment by Simon-Miles-rbwm** [comment]
Its now frozen, completely. All that I did was go out of INPUT, go into Slack and Facebook, then back into INPUT.

**Comment by Simon-Miles-rbwm** [comment]
Forcestoped INPUT and now can't open again.

**Comment by saberraz** [comment]
Would be good if you could produce a bug report and send us the report privately:
https://developer.android.com/studio/debug/bug-report

**Comment by Simon-Miles-rbwm** [comment]
I'll see what I can do for you. Won't be until tomoz though

**Comment by mixedbredie** [comment]
I can confirm this on Galaxy Tab4 8" running Android 5.1.1
All permissions are set correctly
Cleared cache and data.  Still crashes.
Bug report being generated now.

**Comment by saberraz** [comment]
Seems to be working fine now!
