### ISSUE TITLE
Wrong expression evaluation of "plus" for numeric fields

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#2010]
A form is set up with two integer fields "Roofs" and "Gutters", and another field uses default value given by expression `"Roofs" + "Gutters"`.

In QGIS, when a new feature is added, e.g. Roofs=1 and Gutters=2, the other field will be correctly evaluated as 3. But in Input the default value will show 12 - probably because for some reason the fields are treated as text rather than numbers.

Project that demonstrates the issue: https://public.cloudmergin.com/projects/support/bug-expression-plus

![Screenshot_20220330_153848](https://user-images.githubusercontent.com/193367/160848250-ba79f1ef-9193-49ff-a952-8e9b2300fc59.jpg)

**Comment by saberraz** [comment]
Duplicate of https://github.com/lutraconsulting/input/issues/1956?

**Comment by wonder-sk** [comment]
Oops, yes :man_facepalming:
