### ISSUE TITLE
Downloading new version of project from mergin shows ‘invalid project’ duplicate in MY PROJECTS

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#202]

**Comment by saberraz** [comment]
It is a known issue and should be resolved in the upcoming release of mergin.

**Comment by timlinux** [comment]
Here are some supporting screenshots to make sure we are on the same page:

![Screenshot_20190319-165031](https://user-images.githubusercontent.com/178003/54618750-6ea07680-4a5b-11e9-93e1-6917e43ccd82.png)

![Screenshot_20190319-165043](https://user-images.githubusercontent.com/178003/54618747-6e07e000-4a5b-11e9-854f-5eba90e3b527.png)

**Comment by wonder-sk** [comment]
@timlinux it was a problem in Input... will be fixed in the next release
