### ISSUE TITLE
Problem with table view

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#203]
The name of the first column is covered by a white space. This might be duplicate....

![image002 (1)](https://user-images.githubusercontent.com/2649047/54545756-2f5e2100-499a-11e9-8107-3bde268d5f9b.png)

**Comment by wonder-sk** [comment]
I think this was fixed in 42ea6f98f3a7a11406f5ae6e59fe3a754c4a89f2 just not released yet
