### ISSUE TITLE
Error when searching under My projects

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#2049]
When I try to search under my project in Input, I get an error. But when I press Try again it works:

https://user-images.githubusercontent.com/2649047/163122686-c3e2184f-3e4b-4912-971f-615e72165bdf.mp4

**Comment by tomasMizera** [comment]
Seems to be duplicate of https://github.com/lutraconsulting/input/issues/1714

**Comment by saberraz** [comment]
Correct!
