### ISSUE TITLE
Dot for new feature is vissible only after moving of the map

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#2100]
In 1.5.1 RC, when new feature is recorded, dot appears only when map moves (rerenders). In current public version, it is present on the map.

https://user-images.githubusercontent.com/83582181/168240981-670d242f-91ae-482d-90cb-93eb0006f80f.mp4

**Comment by alexbruy** [comment]
This caused by the upstream change in the QgsQuick library in https://github.com/qgis/QGIS/commit/6143a52f799abd02407a876dc6590f1fb35cbcf0
