### ISSUE TITLE
"Saving failed" message when deleting unsaved feature

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#2101]
In 1.5.1 RC, there is a "Saving failed" message when deleting unsaved feature

Steps to reproduce:
1) record the feature (don't save it)
2) in the form hit "delete" button
3) the message appears.. 

Expected behavior is, that message doesn't appear

https://user-images.githubusercontent.com/83582181/168251551-e0a65373-b68f-44a2-b96b-866544974ec4.mp4

**Comment by alexbruy** [comment]
Hmm, this is a really strange use case to me. From my point of view there is no sense in deleting unsaved feature as there is a Cancel button which stops digitizing session without saving changes.

As I understand Delete button is here to delete existing features.

**Comment by jozef-budac** [comment]
This scenario is here since I joined Lutra one year ago :) and it was defined as a valid test scenario. If you would like to change it, please consult with Martin or Peter.
