### ISSUE TITLE
Downloading my project fails with unprocessable entity

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#212]
Using the latest build from today.

On @saberraz's advice I remove my whole INPUT folder, remove the app then did a fresh install.

After logging in to mergin, I tried to download my Maceira project and I got this:

![Screenshot_20190319-225818](https://user-images.githubusercontent.com/178003/54647660-42a4e580-4a9b-11e9-89d5-193840552fe5.png)

**Comment by saberraz** [comment]
Adding an option to show progress might help

**Comment by saberraz** [comment]
Working for me. But #217 will address this.
