### ISSUE TITLE
When updating a project with mergin, not always changes are shown in Input

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#219]
To replicate the bug (this is intermittent and might not be 100% reproducible):
1- Upload a project to mergin
2- Download it from Input
3- Keep the project open in Input
4- Upload a modified version of the project to mergin
5- Update the project in Input
6- Go back to the project in Input
7- Changes do not seem to have applied.

If I close the app and restart it, it seems to solve the issue.

**Comment by wonder-sk** [comment]
Yeah we should close and re-open the project on update...
