### ISSUE TITLE
After upload input thinks it has older version

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#226]
It seems that after upload of project data to mergin, the server has new version, but Input still thinks that the local version is old, so on the next sync it tells the user that the server has newer version and it needs to update the local version first.

It looks like we just need to update the local cache of mergin projects after upload to keep it up-to-date with server.

**Comment by saberraz** [comment]
This issue might have been resolved due the new API and fixes. Could you try and report back?

**Comment by wonder-sk** [comment]
Let's close this and revisit later once we have #323 implemented and can better diagnose these issues.
