### ISSUE TITLE
Tab colour scheme makes inactive tab look inactive

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#231]
![IMG_7092](https://user-images.githubusercontent.com/178003/55030647-bba8bd80-5004-11e9-921f-93bc8e53917e.JPG)

In the image above the Image tab is actually active but the inverted black appearance of the details tab makes it look like the details tab is active.

**Comment by timlinux** [comment]
Note the form uses tabs not group boxes.

**Comment by wonder-sk** [comment]
Suggested style for tabs:

![image](https://user-images.githubusercontent.com/193367/55548108-0e543a80-56d3-11e9-94d4-c7e43940f4d1.png)

**Comment by saberraz** [comment]
A small note: in the left screenshot, it should be **Take a photo**

**Comment by wonder-sk** [comment]
(you can ignore the picture widget here - there's #263 for that)
