### ISSUE TITLE
Drag and drop layout is ignored

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#232]
See screenshot in #231, my designed form should render like this:

![IMG_7092](https://user-images.githubusercontent.com/178003/55031014-8d77ad80-5005-11e9-82a8-48394bf43ea6.JPG)

Without making any changes to my project, clicking exactly the same point and clicking the pencil in the info panel now renders the form like this:

![IMG_3708](https://user-images.githubusercontent.com/178003/55030954-6a4cfe00-5005-11e9-8a42-f1b58a0578ed.JPG)

**Comment by timlinux** [comment]
And sorry for making you turn your head left 90' for the first image :-P

**Comment by saberraz** [comment]
I think this only happens when you have a combination of Groups and individual attribute column(s).
