### ISSUE TITLE
Wrong theme shown on first load

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#233]
To replicate:

1. Open my latest Maceira project
2. Look at the default theme: QGIS Desktop (Online). It should be showing a google backdrop
3. Switch to the Survey (offline) theme and back to the desktop theme
4. The desktop theme now renders properly.

![forms](https://user-images.githubusercontent.com/178003/55032232-5ce54300-5008-11e9-8a94-f29cca3c28f9.gif)

**Comment by saberraz** [comment]
@timlinux I think was resolved. Could you please check and re-open this ticket if still valid?
