### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#245]
It would be nice to have a search bar to allow users search their data

**Comment by tastrax** [comment]
+1 for finding a particular Record / Site ID. Search of all fields or the ability to select a single search field

**Comment by saberraz** [comment]
- as user types into search, it's full screen with results
- if user clicks directly a result, map will be shown with the small preview panel for it (same like with identify)
- if user presses enter, a list would be shown, taking half of the screen, with results highlighted on map. clicking a result on the map or in the list would lead to the usual preview panel

**Comment by saberraz** [comment]
Partially addressed by https://github.com/lutraconsulting/input/pull/825

**Comment by gubuntu** [comment]
Althought the browse and search functionality introduced in 0.7.0 is useful for some use cases, it doesn't meet the needs of @ldlsti, which are explained more fully in this Slack message and mockup video (from about halfway). https://lutraconsulting.slack.com/archives/CFYEQG9E3/p1602840850120500. For this use case, search needs to be 
- available on the main project screen as it is the first thing a user will do to see if the person they are interviewing already exists (for example)
- filter on multiple explicit fields (e.g. name, surname and phone number) with fuzzy matching

Please cost this for a quotation or a priority crowdfunding campaign

**Comment by gubuntu** [comment]
In a discussion on 5 Nov, @ldlsti, @wonder-sk and I agreed that doing a (fuzzy) AND search across all fields for space-separated search terms should do the trick. So as not to search keys, FK values would need to be followed and included in the search

**Comment by saberraz** [comment]
Should be addressed in https://github.com/lutraconsulting/input/issues/999
