### ISSUE TITLE
WM(T)S layer causes crash and shut down of Input

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#247]
To reproduce the bug:
1- Add a WM(T)S layer in QGIS
2- Save the project and transfer it to Input
3- Try to open the project
4- Close the app completely and open it again
5- Crash

**Comment by sklencar** [comment]
It's crashing on Input v0.2.6 indeed, but seems working on current Input master compiled with a few days old master of QGIS.

**Comment by saberraz** [comment]
Resolved in 0.2.7
