### ISSUE TITLE
Value Relation widget (attribute form)

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#260]
Currently qgis_quick library does not support Value Relation widget (only Value Map) which is handy when you have available key-value pairs for a field in a separate layer.

**Comment by wonder-sk** [comment]
PR in QGIS merged - need to update to qgis master again.

**Comment by saberraz** [comment]
I am having no luck using the widget in Input

**Comment by PeterPetrik** [comment]
merged to master https://github.com/qgis/QGIS/commit/a067a334cd1b18f122bb99e3fbe26c7483869988

@sklencar maybe you can try to create new version of SDK and use it in the PR?

**Comment by wonder-sk** [comment]
Seems to be working - closing.
