### ISSUE TITLE
Unable to upload edits to Mergin from Input app

### ISSUE THREAD

**Issue by Dukestep** [lutraconsulting/input#264]
I have downloaded a project from Mergin and made some changes to the attributes of layers in the project and deleted some geometries.

Following these edits, I wish to upload the changes back to Mergin. From what I see in the user documentation, I should see a cloud icon with an up arrow for that project in the "All Projects" tab. However, the icon never changes and instead display a green check mark.

Am I missing something really obvious here? 

I am using the latest version of Input.

**Comment by saberraz** [comment]
It should definitely display the cloud with arrow up. If not, it is a bug.
Let me see if I can reproduce it....

**Comment by saberraz** [comment]
OK...I managed to reproduce the issue for one my projects.
I had to delete the project under MY PROJECT and re-download it for the upload to work after change.

Please make a copy of data (/sdcard/INPUT/projects) if you want to delete it. We will look into this issue and release a fix soon.

**Comment by Dukestep** [comment]
Not sure I follow... Tried to reproduce your steps but I didn't get it to work. I'll wait for the next release, see if it solves my issue and follow up with you! If the release doesn't resolve my issue, I don't mind adding you as a user on the project so that you can debug on your end with my project files.

**Comment by saberraz** [comment]
if you could add me to the project (saber), I can have a look too. But, the issue is likely to be with the local cache not being updated, hence the upload button does not appear.

As a work around:
1- Connect your phone to PC using USB
2- Open file explorer, and go to your mobile folder
3- Under INPUT > projects, select your project and copy it to your PC.
4- Delete .projectsCache.txt
5- Upload the files on your PC to mergin
6- In Input app, open MY PROJECTS and delete the problematic project
7- Under ALL PROJECTS, download the project
8- Hopefully things should work as expected

**Comment by Dukestep** [comment]
Followed the work around and still wasn't able to get the upload icon to show... I've added you to the project (Etienne) if you want to dig around and confirm that your fix may work for my case!

**Comment by saberraz** [comment]
hi @Dukestep I managed to replicate your issue.

Then I downloaded your project:
1- renamed it to get rid so there is no _ at the start of the project
2- Got rid of the qgis project back up file.
3- Ran `ogrinfo -sql "VACUUM" filegeo.gpkg`
4- Created a new project (sync_issue) which all seems to be working fine now.

I have shared the project with you...so you can test it too.

**Comment by Dukestep** [comment]
Confirming that your fix resolved the issue!

Is this a user-side issue related to one or a combination of the underscore in the project name, presence of the backup file or the unvacuumed geopackage or is it something that can be fixed on the Input app side of things? Would like to know to avoid recreating these issues with future projects.

Thanks for the support on this. Great app! Looking forward to using it with my team.

**Comment by saberraz** [comment]
Could you share your original project (Etienne) with "viktor"?

I think the fix should be easier than that, because, even creating a new empty folder on mergin and uploading the same files, seems to have resolved the problem!

**Comment by Dukestep** [comment]
I've added "viktor" to the original project. Good to know it's an easy fix :).

**Comment by dracic** [comment]
Should this work with shapefiles? I tested Input with some shapefiles with the same issue. No underscores in project or layer names. Edits are working fine, but sync icon never shows up. Never had that issue with gpkg layers.

**Comment by sklencar** [comment]
I can confirm the bug while working with shapefiles. Although certain shapefiles in project's folder are modified and also a modification timestamp changes after any edit, seems like a system cannot see changes from a project's folder perspective. That causes the issue and changes cannot be uploaded. 

Better modification recognition soon!
