### ISSUE TITLE
INPUT Crashes with my project

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#266]
I shared my project as 'Tim Crashing Project'.

It takes realllllly long to open the project.

Sometimes INPUT will crash while opening the project.

Sometimes the project will load but the first map interaction crashes it.

**Comment by timlinux** [comment]
Oh using the latest INPUT version from the app store as of 4 April 2019

**Comment by edips** [comment]
Input clashes with sample data or your project? Your device has SD Card? Input sometimes open the project slow when the internet is slow. I think it will open the project faster when disabling map theme.

**Comment by PeterPetrik** [comment]
@timlinux is this still issue?
