### ISSUE TITLE
Coordinate system of user's location and Map Canvas

### ISSUE THREAD

**Issue by edips** [lutraconsulting/input#280]
Hello. Does the app set canvas's coordinate system according to proj4 definition in qgs file?
Coordinate system of user's current location is based on WGS84 or coordinate system of the qgs project?
Is it possible to assign EPSG projection using JavaScript? I would like to make an action in menu for combo box to choose EPSG projections in a dialog, When selecting a coordinate system, the map projection should automatically change.

**Comment by wonder-sk** [comment]
> Does the app set canvas's coordinate system according to proj4 definition in qgs file?

Yes.

> Coordinate system of user's current location is based on WGS84 or coordinate system of the qgs project?

User's location is given in WGS 84, when recording it may be reprojected if the layer where recording happens is not in WGS 84.

> Is it possible to assign EPSG projection using JavaScript?

No.

> I would like to make an action in menu for combo box to choose EPSG projections in a dialog

I think Input should stay as simple as possible and should not contain advanced features such as CRS configuration. That can be done in QGIS. Why do you need to support multiple CRS in Input?

**Comment by edips** [comment]
User's location can be reprojected from WGS84 to other projections using Proj4JS. For example 
```var ccoord= Proj4js.proj4(Proj4js.proj4("wgs84 def"),Proj4js.proj4("proj4 def delivered from c++"),["user's latitude longitude"])
north.text = ccoord[1]
east.text=ccoord[0]```
Yes it is better to keep input  simple for general use. My idea is not for input. I think to start a project named QMapViewer using input, QGIS Quick components and Fluid QML components. CRS configuration would be useful for surveyors to input local coordinate system points, traverse or control points. 
By the way input has problem with back button , it sometimes doesn't work. But when I use Fluid components with input , back button works.
Thanks.

**Comment by wonder-sk** [comment]
Good to hear you are thinking of creating an app based on qgis_quick and components from Input...

Actually you don't need to use Proj4js to transform coordinates and rather use existing QGIS classes - there is helper class QgsQuickCoordinateTransformer for that.

**Comment by edips** [comment]
Unfortunately I don't know c++ but I think to learn it with QGIS API. I use JavaScript with qml. I used Proj4JS and Sqlite to convert coordinates in qml. I will try QgsQuickCoordinateTransformer thanks.
