### ISSUE TITLE
Direction from compass

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#281]
Right now we show direction based on changes in GPS position. This is fine but not very useful when the device is rotated in one location. Many devices have integrated compass sensor which gives accurate information about the current direction of the device. The compass also has much faster update rate (several times per second) so it reacts nicely. Only in case the compass is not available we would fall back to using direction from GPS.

**Comment by PeterPetrik** [comment]
merged https://github.com/lutraconsulting/input/pull/297
