### ISSUE TITLE
Input should use a different syntax for Display property

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#285]
And you will end up with having 2 different styles/themes

**Comment by wonder-sk** [comment]
What do you mean?

**Comment by saberraz** [comment]
I might have not worded the issue properly. Tim is having issues managing multiple styles for the same layer to handle Display property of the layer:
- One for html tool to work well with Input
- Another for Input

**Comment by wonder-sk** [comment]
Duplicate of #258 ?

**Comment by saberraz** [comment]
Indeed!
