### ISSUE TITLE
Does Input take Z values

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#286]

**Comment by wonder-sk** [comment]
You mean elevation from GPS? From the code it looks like it does, but of course you need a layer with geometry that keeps Z coordinate. But I have not tested...

**Comment by saberraz** [comment]
It did not capture Z values in my test.

**Comment by Brent-Edwards** [comment]
Same for me, no z captured. Tried with PointZ, PolylineZ and PolygonZ geometry types.

**Comment by jancelin** [comment]
+1
