### ISSUE TITLE
Capturing/Editing geometry-less tables

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#287]
An option to allow users to edit/add data to tables without geometry.

**Comment by timlinux** [comment]
Here are two examples:
* I am starting to captre details for a person on a field survey and discover we dont have him in our pick list. I create a new ‘person’ record, taking a photo of the person and noting various personal details.
* I am capturing a new growth state for my plant. There is no spatial entity at all - I just need to record e.g. flowing of a certain species and note the time and include a picture.
In the second use case it is not even a value relation entry I am trying to manage but rather some non spatial tables in my database

**Comment by saberraz** [comment]
Duplicate of #794 and addressed in https://github.com/lutraconsulting/input/pull/811
