### ISSUE TITLE
Mergin API version check

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#294]
Can you please add check to input runtime to get mergin API version from some endpoint and check if the current version matched the minimal Mergin API version? If not, user should be notified to download new Input APP from google play to be able to use mergin/projects panels. 

one can use https://dev.dev.cloudmergin.com/ping endpoint

**Comment by sklencar** [comment]
Do we want to disable all functionality related to Mergin when Mergin API version doesnt match required version? Do we want to notify a user only once or each time user attempts to use Mergin functionality?

**Comment by PeterPetrik** [comment]
probably disable, so user can try to backup the input folder or use the Input with local files?

**Comment by wonder-sk** [comment]
implemented & merged
