### ISSUE TITLE
Demo project(s)

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#3]

**Comment by saberraz** [comment]
- One demo with global bg
- Another with more complex project showing QGIS styling

**Comment by sklencar** [comment]
Can be the qgis sample project (one with planes) used? It doesnt contain all types of fields and proper background map though. If not, can you provide any?

**Comment by saberraz** [comment]
[survey.tar.gz](https://github.com/lutraconsulting/input/files/2515087/survey.tar.gz)

**Comment by saberraz** [comment]
@sklencar try this
