### ISSUE TITLE
Support for Slider widget

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#316]
If the data is set to Range, users can set the slider as a widget type for adding attribute form.
Can we have this widget in Input please?

**Comment by saberraz** [comment]
@sklencar  could you implement this for @jvdkwast :)

**Comment by wonder-sk** [comment]
Added to qgis_quick in https://github.com/qgis/QGIS/pull/30949 - will be available in the next Input release

**Comment by saberraz** [comment]
Do we need to bump the qgis version in https://github.com/lutraconsulting/OSGeo4A?

**Comment by wonder-sk** [comment]
yes
