### ISSUE TITLE
Error writing to shp

### ISSUE THREAD

**Issue by dsubat** [lutraconsulting/input#322]
Hi there.

I have problem with reading recorder features on PC. In Input collected features are visible and have attributes, but when*. shp is transfered to PC, features do not exsist.

How is this possible? Is there some temp file on device from which I could copy missing features? I cannot accept that *.shp is broken, but in application features are visible.

Happened on two projects till now.

 What is the most stable data format for mobile device instead of *.shp?

**Comment by saberraz** [comment]
Hi @dsubat ,

would it be possible to share your project with me on mergin. My username is saber.

You need to transfer all your files (shp, shx, dbf, prj, etc).

**Comment by dsubat** [comment]
I created a project and shared it with you. 

I didn't use Mergin on this project, and allways copied files locally after collecting on site.

**Comment by saberraz** [comment]
This is now resolved.
