### ISSUE TITLE
WMST layer disappears at high zoom levels

### ISSUE THREAD

**Issue by jvdkwast** [lutraconsulting/input#327]
When zooming in on WMST layers they disappear at high zoom levels. For XYZ tiles or MBTiles this is not a problem.

Example project: IHE_Fieldwork
Layers that show this problem:
IGN Aerial
IGN Topography
Geology

**Comment by saberraz** [comment]
Hi @jvdkwast I presume you meant WMTS, as WMS-T is a different can of worms :)

**Comment by jvdkwast** [comment]
Yes @saberraz you're right. It's WMTS.

**Comment by saberraz** [comment]
I have tested the project in QGIS desktop (master) and the issue appears to be there too. A closer inspection shows that the WMTS only supports zoom scales of 266.591 (Layer > Properties > Information > Information from provider)
![image](https://user-images.githubusercontent.com/2649047/59911047-00c56b80-940b-11e9-83f0-fe0d5e73877a.png)

So, maybe in QGIS, we can have a work-around to just magnify when it hits the highest zoom level.

**Comment by wonder-sk** [comment]
As soon as QGIS gets to the highest zoom level, when zooming in further, QGIS keeps magnifying tiles from the highest zoom level. Maybe the highest zoom level has blank tiles...?

**Comment by saberraz** [comment]
@wonder-sk that is correct. It goes blank from zoom level below 1:847. But in the information it says there should be two other tilesets available.

I have attached the qlr in case one wants to test it.
[wmts.qlr.zip](https://github.com/lutraconsulting/input/files/3313817/wmts.qlr.zip)

**Comment by wonder-sk** [comment]
There must be something wrong with the WMTS server.

Everything works smoothly up to zoom level 12 - e.g. one of the successful requests:
https://wxs.ign.fr/pratique/geoportail/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&FORMAT=image/jpeg&TILEMATRIXSET=PM&TILEMATRIX=12&TILEROW=1370&TILECOL=2051

Then from zoom level 13 the server returns "not found" error:
https://wxs.ign.fr/pratique/geoportail/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&FORMAT=image/jpeg&TILEMATRIXSET=PM&TILEMATRIX=13&TILEROW=2736&TILECOL=4103

Probably the server is just incorrectly configured - it offers zoom levels all the way to zoom level 21 with resolution of ~0.07m

**Comment by saberraz** [comment]
@jvdkwast I think this is an issue with the data provider and not related to QGIS/Input. I have tried it with other WMTS and they work as expected.

**Comment by wonder-sk** [comment]
Closing as it is a server problem.
