### ISSUE TITLE
Syncing results in multiple projects with the same name

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#359]
![Screenshot_20190702-112339_Input](https://user-images.githubusercontent.com/2649047/60505661-16188080-9cbc-11e9-89a3-49fe050eaa11.png)

**Comment by saberraz** [comment]
This seems to be no longer an issue with this apk:
https://github.com/lutraconsulting/input/pull/369

**Comment by saberraz** [comment]
Well, @mostlyAtNight reported the same issue. The issue, goes away, when you close the app and open it.

**Comment by wonder-sk** [comment]
this will hopefully not happen anymore after the mergin client refactoring - please reopen if still the case.
