### ISSUE TITLE
Proper warning when trying to upload changes and storage limit is reached

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#360]
Currently the error is as below which is a bit misleading:
`2019-07-02T12:45:41.811Z - https://public.cloudmergin.com/v1/project/push/saber/zilina. FAILED - Error transferring https://public.cloudmergin.com/v1/project/push/saber/zilina - server replied: BAD REQUEST`

**Comment by wonder-sk** [comment]
Duplicate of #243 ?

**Comment by wonder-sk** [comment]
+ there's #361 for better logging
