### ISSUE TITLE
Input in other languages

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#365]
Possibility to translate the interface to other languages would be great.

**Comment by geomondego** [comment]
Where can we find the files to translate?

**Comment by PeterPetrik** [comment]
> give us a couple of weeks to set up the required infrastructure.

Well, unfortunately those weeks were quite long, but finally we are ready for translated Input :)

The translation is done via transifex https://www.transifex.com/lutra-consulting/input 
and PL, IT, FR, ES and DE translations will be release in the next InputApp version.

**Comment by PeterPetrik** [comment]
fixed in master, will be released in 0.6.2
