### ISSUE TITLE
Username is case-sensitive in Input

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#366]
...but not Mergin.

**Comment by sklencar** [comment]
Is it still valid? Just checked authentication on public instance (`Version: 2019.4.1rc1 (Sicily`) and could log in only with a name as I registered (lowercase). Upper case or camel case didnt work for me, neither for username or email.

Generally, should it be case-insensitive on a client site?

**Comment by wonder-sk** [comment]
Let's close this and reopen if it is still the case.
