### ISSUE TITLE
Input crashed when zoom + camera used

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#378]
Steps to reproduce:

1. Download *Photo Survey (Template)
2. Open project and zoom-in to the southmost of the three points
3. Keep zooming in until you see the image previews
4. Tap the southmost camera icon

I would expect it to open that feature for editing.  Instead, I was asked whether I want to allow Input access to my camera, I tapped OK, then the app hung and closed.

Please note this is first use of Android on a new device (you might have the remove app permissions to reproduce issue).

Let me know who to share the problem project with.

**Comment by saberraz** [comment]
I cannot reproduce the issue. @mostlyAtNight could you test with 0.6.4 and update?

**Comment by tomasMizera** [comment]
This one is most probably a problem with permissions as you said, it is related to this #953

**Comment by saberraz** [comment]
Let's close and reopen if persists.
