### ISSUE TITLE
Sync icon may be better placed on *Home* tab

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#379]
At present, the option to sync a project you have on the device is in the *My projects* tab.  This tab could contain many projects so it may be more sensible to have the sync option next to the project in the Home tab.

**Comment by wonder-sk** [comment]
Agreed.

For this we need some support on the server: the client should be able to tell the list of all local projects for which metadata are required (otherwise we may show outdated sync related information)

**Comment by tomasMizera** [comment]
@wonder-sk  @mostlyAtNight What about UI? Where do we place new icon? Inside drop down menu under _three dots_?

<img src="https://user-images.githubusercontent.com/22449698/100094185-e772eb00-2e58-11eb-9ce4-2ce956824ddc.png" width=300>

**Comment by saberraz** [comment]
I suggest to have it as a separate button near ...Until we get the new design in place.

**Comment by wonder-sk** [comment]
Yes it is meant to be on the left from ... like this:

![image](https://user-images.githubusercontent.com/193367/100096028-b7791700-2e5b-11eb-9496-44e0b169b332.png)

**Comment by tomasMizera** [comment]
Great, thanks for the feedback :)

**Comment by tomasMizera** [comment]
This ticket now waits for new Mergin endpoint.

**Comment by tomasMizera** [comment]
Endpoint is merged on Mergin.

**Comment by tomasMizera** [comment]
Guys what is the desired behavior in these cases?

1. project is only local (not a mergin project) - no icon?
2. user is not logged in - some info icon to sign in?
4. user is logged in but project is from different namespace and user does not have rights to write - disabled upload button?

@wonder-sk @saberraz

**Comment by wonder-sk** [comment]
1. initially it could be with no icon, Viktor has been working on #1061 which should allow us to upload a project that is not a mergin project - then we will add an icon too
2. we could still keep the icon there, and upon clicking it we could say that user needs to log in...
3. we could still show the icon, and upon clicking it would show the error message about missing permissions (probably easier to understand than if the button is just disabled)

**Comment by tomasMizera** [comment]
Frozen now until refactoring of Project models and project creation wizard merge.
