### ISSUE TITLE
Save button obscured

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#384]
Check this:

![image](https://user-images.githubusercontent.com/884954/61296987-2e67bf80-a7d3-11e9-8452-42531eaf213c.png)

I've now finished editing attribute data and want to go back to the map (saving my work).  The obvious button that's visible is 'Back' but if I press that, my point is lost (I have done this many times by accident).  To save I have the (1) minimise the KB then (2) hit save.

Perhaps we can put the save button at the top of the page so we have either 'Save' or 'Cancel' there?

**Comment by wonder-sk** [comment]
@mostlyAtNight How about that upon clicking "Back" we would check if there are any changes to attributes, and if there are, we would ask the user whether to save the changes [yes] / [no] / [cancel]

That would avoid the need to have the bottom toolbar always visible (taking up vertical space) and also avoid having to move the controls around...?

**Comment by wonder-sk** [comment]
Currently the idea to solve this is to have Cancel/Save buttons in the header, so they are always visible:

![image](https://user-images.githubusercontent.com/193367/107041630-0844ae80-67c1-11eb-842b-b4c13218f03b.png)

This should also avoid the common source of problems when users edit something, then click back button, forgetting to save the changes. With this approach they would explicitly choose whether to save or discard changes...
