### ISSUE TITLE
SVG paths messed-up on changing themes

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#385]
This occurs in QGIS desktop () as well as Input.

I have set styles in two different themes with relative path SVGs.  The paths are confirmed as relative in the project file content.

When switching between the map themes, one theme always has broken SVG symbols instead of the camera icons as intended.

To reproduce:

1) Open project and zoom in until you see little cameras
2) Change theme to 'Without previews'

You should now see a load of question marks.

[photo-survey-template.zip](https://github.com/lutraconsulting/input/files/3397451/photo-survey-template.zip)

**Comment by mostlyAtNight** [comment]
Can be worked-around by embedding the SVGs within the .qgs file

**Comment by saberraz** [comment]
@mostlyAtNight best to file a ticket in QGIS. If it gets resolved there and still an issue in Input, we can reopen this.
