### ISSUE TITLE
Image preview fails in Windows

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#387]
On windows, special characters appear in maptip config which causes image preview and other functionality to fail.

Sample project content looks like this:

```
<mapTip># image&#xd;
file://[%@project_folder%]/[% "Photo" %]</mapTip>
```

Input should ideally be able to deal with these characters.  I also think the docs may be incorrect - the line starting with:

`file://[%@project_folder%]` should probably start with `file://[%@project_folder%]`

**Comment by wonder-sk** [comment]
Does it help if you remove `#xd;` from the project file?

**Comment by mostlyAtNight** [comment]
Yes, works well
