### ISSUE TITLE
submit application to appstore

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#422]
https://developer.apple.com/app-store/review/#common-app-rejections
https://developer.apple.com/app-store/review/guidelines/

**Comment by PeterPetrik** [comment]
first step: https://developer.apple.com/testflight/

**Comment by PeterPetrik** [comment]
as for ad-hoc installation:

https://wiki.qt.io/Support_for_iOS_and_tvOS

> "Installers" for iOS and tvOS

> The workflow described above refers to deploying an app to a USB-attached iOS or tvOS device. If you want to send an "installer" for an app to someone remote with an iOS or tvOS device (NB must be one which has somehow been inducted into your limited pool of development/test machines, for example by adding the device GUID in your Apple developer account and creating and downloading a new app signing certificate including the device):
> 
> In Xcode, there is a "Product" menu with "Archive" on it (NB need to have iOS or tvOS device selected as build target, not a simulator).
> That creates an archive in the Organizer window's Archives tab.
> Select the archive and hit the "Distribute" button.
> This brings up a dialog where you get to select "Save for Enterprise or Ad Hoc Deployment" then "use iOS/tvOS Team Provisioning Profile", and then save a .ipa file (an "iPhone application archive file" apparently).
> Send the ipa file to the intended user.
> If they double-click the ipa file it should open iTunes' to install or update the app on the device (when iTune's "apply" is hit).

**Comment by PeterPetrik** [comment]
@sklencar we need to use different certificate for signing (LUTRA CONSULING production one for INPUT)

**Comment by saberraz** [comment]
Sumbited to iOS TestFlight for review.
