### ISSUE TITLE
GPS not working on iOS

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#428]
issue it that the dialog for getting the permissions pops-out but immediately disappears

**Comment by sklencar** [comment]
There is a possible workaround to enable location service on iOS even-though the confirmation dialog within the app for the service doesn't work (So even if the service is requested, somehow a confirmation is not applied). The location access can be granted manually at `Settings -> Privacy -> Location Services -> Input`. If the access is granted there, GPS should work regularly.

The problem with granting access automatically though the dialog might be related with some other issues with iOS build.

**Comment by PeterPetrik** [comment]
@sklencar can you test and release once 470 is merged?
