### ISSUE TITLE
Support MBTiles in iOS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#440]
see #435

**Comment by imaginaryearthnotes** [comment]
Does this mean that there is currently no way to use offline rasters in iOS?

**Comment by saberraz** [comment]
Unfortunately not offline raster tiles.

**Comment by wonder-sk** [comment]
@saberraz what is the problem with offline raster tiles? the original issue (#435) has been fixed and the provider (wms) should be supported on iOS...

**Comment by saberraz** [comment]
Ahhhh...that is correct. This ticket should be closed indeed!

**Comment by saberraz** [comment]
Hi @imaginaryearthnotes it is supported. You can check this example:

In Input > Projects > Explore and download saber\test_mbtiles_raster

**Comment by imaginaryearthnotes** [comment]
Hi @saberraz, thank you. But I really think there is still something wrong.
1. In Qgis-Win LTR 3.10.5 when I download saber\test_mbtiles_raster and try to open it, the source for the osm layer ist missing: type=mbtiles&url=file:./osm.mbtiles
2. I open it anyway and set osm.mbtiles from the project folder as source. Then its shown in QGIS
3. If I then make a new project it will not be shown in INPUT
4. qgis saves the source (looked in the xml file) as only: ./osm.mbtiles
5. if I change the source to (editing the xml): type=mbtiles&url=file:./osm.mbtiles, it works again

Conclusion: INPUT and QGIS 3.10.5 do not read or interpret the source string equally, I'm not sure who is responsible or how to fix this. Here is the project which is loading in qgis but shows nothing in INPUT directly from your project: ulrichkniess/test_mbtiles_raster
This are the exact steps I took:
- download saber/test_mbtiles_raster in QGIS mergin plugin
- load procet from there
- keep layer in prompt for missing source
- point source to file osm.mbtiles in project and saved project file
- delete .mergin folder
- made new public project: ulrichkniess/test_mbtiles_raster

This was long, but hopefully understandable. As I want to successfully render my own mbtiles this is crucial. Thanks for reading.

**Comment by saberraz** [comment]
Hi @imaginaryearthnotes 

thanks for your detailed report.

I think I managed to get to the bottom of the issue. QGIS appears to handle the mbtiles file differently, depending on how you add the file to the QGIS project:

- If you drag-and-drop the file or add it as browser panel, it registers the file as WMS provider (i.e. type=mbtiles&url=file:./osm.mbtiles in the qgs/xml file). Using the above methods, it should work in Input

- If you add the mbtiles from Layer Data Source Manager > Raster , it will register the file as raster file (i.e appears as source="./osm.mbtiles" in the qgs/xml file). Loading the mbtiles as raster, you will have the issue as reported originally in this ticket.

I think this is either a bug or an expected behaviour in QGIS (@wonder-sk is it a left over when you ported it from GDAL to wms?).

For your MBTiles to work, I suggest using Browser panel for the time being.

**Comment by imaginaryearthnotes** [comment]
Hi @saberraz,

I can not confirm this differences, here its all the same. Here the relevant excerpts from the qgs, when added the osm.mbtiles in different ways. Also the reminder, that qgis does not know how to read "type=mbtiles&url=file:./osm.mbtiles" and ask for a different source. this wouldn't make sense if there is a proper way to add the mbtiles-file with resulting in the mentioned source-string?!:
  <projectlayers>...
<datasource>./osm.mbtiles</datasource>...<layername>osm_dblclk_Browser</layername>...<provider>gdal</provider> # added by double click in browser
...
<datasource>./osm.mbtiles</datasource>...<layername>osm_rclk_Browser</layername>...<provider>gdal</provider> # added by right click in browser -> add layer
...
<datasource>./osm.mbtiles</datasource>...<layername>osm_dnd_Browser</layername>...<provider>gdal</provider> # added by drag 'n drop from browser
...
<datasource>./osm.mbtiles</datasource>...<layername>osm_addLayer_Raster</layername>...<provider>gdal</provider> # added by menu->add layer->raster

I have seen in the qgis-file you used qgis 13.0, i will try if that changes the behavior.

Regards.

**Comment by saberraz** [comment]
Ahhh...forgot to mention I use qgis master

**Comment by imaginaryearthnotes** [comment]
Hi @saberraz, 
as conclusion also maybe for others for LTR 3.10.5 my only workaround so far to make it work:
- before snyc with mergin unpack qgz to qgs, del qgz
- edit all mbtiles-layers in .qgs in the `<projectlayers>`-section:
- add "type=mbtiles&amp;url=file:" before file-name in `<datasource>`
- change `<provider>gdal</provider>` to `<provider>wms</provider>`

I'm still confused, if this is an INPUT-bug or QGIS-bug, so that I can write the right bug-report ... it seems to be QGIS right?

**Comment by imaginaryearthnotes** [comment]
In QGIS 3.12.2 all is working as expected. I guess I'll write a bug-report for qgis ltr then ...

**Comment by saberraz** [comment]
OK...looking through QGIS PRs, @wonder-sk did the change from GDAL to WMS for MBTiles in QGIS 3.12:
https://github.com/qgis/QGIS/pull/33855

It is a feature and hence we cannot backport it to QGIS 3.10 LTR.

So, this ticket is still valid for QGIS 3.10 and earlier versions. But, as Input is built for the very latest QGIS, I suggest to live the life a bit on the edge :)

In terms of bug report for QGIS (12 and master): adding MBTiles through Layer menu is still following the legacy GDAL driver and should be switched to WMS. Let me file one and reference this ticket, so we can resolve it in due course.
