### ISSUE TITLE
Not possible to edit relations

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#452]
I have a non-spatial table joined with a spatial table (points). When I try to edit the attribute form, it does not allow me.

It will be good to allow:
- Editing the spatial table (a bug probably)
- Being able to add rows to the non-spatial table from within the spatial form(probably a new edit widget and #287 )

See attached project.
[qgis_joins.zip](https://github.com/lutraconsulting/input/files/3605259/qgis_joins.zip)

**Comment by PeterPetrik** [comment]
Also for many entries, possibility to filter out the values to find faster 

<img width="658" alt="Screenshot 2020-05-15 at 14 01 30" src="https://user-images.githubusercontent.com/804608/82048404-e7797d80-96b4-11ea-9694-71a18fe902e2.png">

cc @timlinux

**Comment by wonder-sk** [comment]
THE Plan:

1. improve UX for value relation widget
   - full screen list of values
   - search on top of the full screen list

2. management of lookup tables
   - menu "Manage data" > full screen view with list of all layers/tables
   - on click on a name of a layer/table > full screen view like in pt 1.
   - extra features to add new row, delete rows, edit(?)

3. add + button directly in value relation widget

**Comment by gubuntu** [comment]
this means handling relation references (as opposed to value relations) like they are handled in desktop right?

**Comment by saberraz** [comment]
The first two items in https://github.com/lutraconsulting/input/issues/452#issuecomment-634787767 as been addressed in this PR:
https://github.com/lutraconsulting/input/pull/811

**Comment by PeterPetrik** [comment]
@saberraz is this closed?

**Comment by saberraz** [comment]
Not fully implemented.
