### ISSUE TITLE
Enhancement - Implement constraints

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#458]
Implement constraints to allow for 'required fields'

![Constraints](https://user-images.githubusercontent.com/8775395/64928925-15769b80-d862-11e9-8cf5-eb97311e17ec.JPG)

**Comment by saberraz** [comment]
It has been implemented in QGIS and will be available in the next Input (0.7.1+).

**Comment by wonder-sk** [comment]
It also requires input PR #868 to be merged - which can be done only when new sdk is ready - reopening for now

**Comment by saberraz** [comment]
Just tested on documentation\form_setup on number field and it does not seem to work.
