### ISSUE TITLE
overlapping labels in ios (small screens)

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#459]
![File](https://user-images.githubusercontent.com/804608/64936661-59b06e80-d857-11e9-91fe-5914923e29e8.jpg)

**Comment by saberraz** [comment]
This is related to iPhone SE

**Comment by wonder-sk** [comment]
I would suggest to have some simple workaround there: e.g. if the width per tab is less than X, the "Shared with me" label would be turned into just "Shared"

**Comment by saberraz** [comment]
Another example:
![File](https://user-images.githubusercontent.com/2649047/65136018-ce71dd00-d9fe-11e9-940f-60956a420539.jpg)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/65251927-6f908e80-daf8-11e9-9a0b-ee3582773285.png)
