### ISSUE TITLE
Crashes on iOS 13

### ISSUE THREAD

**Issue by AsgerPetersen** [lutraconsulting/input#470]
Just installed iOS 13 and now Input crashes right after showing the splash.

Input version is 0.4.2 (3)

**Comment by saberraz** [comment]
@AsgerPetersen have you tried it with iOS 13.1?

**Comment by AsgerPetersen** [comment]
Yes, same behaviour on iOS 13.1

One small observation: It seems like it may be related to GPS access. If GPS is not activated on the phone when Input is started it shows the splash for a few seconds and then crashes immediately when the GPS icon shows (the little arrow in the top of the screen). If the GPS is already active on the phone Input crashes almost immediately when it is started.

**Comment by saberraz** [comment]
OK, I have update my iPhone to 13.1 and I can confirm the crash. If I go to the app settings and block using of the Location, the app opens and works fine (obviously without GPS :( )

**Comment by saberraz** [comment]
I found a work-around, which makes it usable again (at least for me):

1. Wipe TestFlight and Input from your device
1. Install them
1. Go to Privacy > Location Services > Input and change it to **Ask next time** 
1. Launch Input

It stopped crashing for me, but there are some pop ups in the background.

**Comment by PeterPetrik** [comment]
it works but it is the same as disabling GPS.. looks like the workaround https://github.com/lutraconsulting/input/issues/428 no longer works or crashes the app.

**Comment by saberraz** [comment]
Hi @AsgerPetersen could you try with 0.4.3 version?

**Comment by AsgerPetersen** [comment]
Hi @saberraz 
I updated it through TestFlight and it still crashes on my phone. Only difference is that it now asks me to send feedback to the developer. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saberraz** [comment]
Unfortunately, due to code freeze of QGIS, we are unable to publish a new release until after 25/10. The workaround to set the location to Ask again works for the time being.
