### ISSUE TITLE
Consider display notch

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#476]

**Comment by wonder-sk** [comment]
When / where? is this iOS only?

some screenshots demonstrating the issues would be useful

**Comment by tastrax** [comment]
Respect notch on landscape view IOS

![IMG_2138](https://user-images.githubusercontent.com/8775395/70107680-503ae380-169b-11ea-9f7c-f92a4a364695.PNG)

**Comment by tastrax** [comment]
as per below

![IMG_0688](https://user-images.githubusercontent.com/8775395/70108292-0a7f1a80-169d-11ea-916a-a5b0d774cc08.JPG)

**Comment by PeterPetrik** [comment]
fixed in 0.6.x
