### ISSUE TITLE
WinError 183: file already exists (failed to synchronize project)

### ISSUE THREAD

**Issue by rdgomt** [lutraconsulting/input#488]
Hello!

I'm trying to synchronize a project with mergin QGIS plugin but I'm getting this error:

![Sem título](https://user-images.githubusercontent.com/23437436/66692702-4d150f80-ec77-11e9-8124-10e56756279d.png)

It says: it is not possible to create an existing file.

I've tried with shapefiles and geopackage.

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/qgis-mergin-plugin/issues/44

I believe you are using ESRI Shapefile. Best to use Geopackage for your vector data.
