### ISSUE TITLE
Private project not found

### ISSUE THREAD

**Issue by sukuchha** [lutraconsulting/input#491]
I have a project uploaded from QGIS. The project is shown in the web,but i cannot see the project through APP. How can i solve it ?

**Comment by saberraz** [comment]
You need to also upload qgz (or qgs) project file too:
1- First load your layers in QGIS
2- Style them
3- Set up the form
4- Set the survey layer(s)
5- Upload all layers and QGIS project to Mergin

**Comment by sukuchha** [comment]
silly me. i forgot to put QGIS project to the folder i uploaded. Thanks a lot.
