### ISSUE TITLE
Integers in GPKG displayed as "0"

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#493]
I noticed a change since last update two days ago. Every int field in every layer in my gpkg is displayed as "0" in forms.

**Comment by dracic** [comment]
![Screenshot_2019-10-25-13-36-47-407_uk co lutraconsulting](https://user-images.githubusercontent.com/4533263/67568590-eab71700-f72c-11e9-9b39-f28d53f6c3de.png)
![Screenshot_2019-10-25-13-36-52-877_uk co lutraconsulting](https://user-images.githubusercontent.com/4533263/67568591-eab71700-f72c-11e9-95f5-8954386d47ee.png)

**Comment by saberraz** [comment]
Hi @dracic that looks like an upstream issue in QGIS. Do you have the same issue there too in your forms or Display tooltip?

**Comment by dracic** [comment]
In qgis everything looks fine.

**Comment by dracic** [comment]
Well, perhaps it has to do with the fact that QGIS automatically selects range widget for int type, not so much because of int type?

**Comment by dracic** [comment]
I don't see this behavior any more in 0.6.2, so I suppose some fix got in with the new SDK....

**Comment by dracic** [comment]
So the issue appeared again:

![image](https://user-images.githubusercontent.com/4533263/115039245-911e4b80-9ed0-11eb-861d-6fe1da8dbb85.png)

**Comment by saberraz** [comment]
I can confirm the issue. In QGIS, it stays as NULL but in Input it is saved as 0. But still there is an issue with the Slider. In both QGIS and Input the value stays as 0.

**Comment by dracic** [comment]
Also when value is not NULL Input always shows 0, and QGIS shows exact value:

![image](https://user-images.githubusercontent.com/4533263/115050859-7d78e200-9edc-11eb-980c-956e49a3a833.png)
