### ISSUE TITLE
Larger GeoTiff with internal overviews - display issue

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#497]
I have one larger GeoTiff (cca 3GB) I use as a background layer. It is prepared with internal tiling and internal overviews. It renders correctly at smaller scales but at larger scales it doesn't. Are there any size limit regarding GeoTiff rendering?

**Comment by saberraz** [comment]
Input does not have any limit on file sizes. Are you using 64 bit version of the app (Android device from 2016-17 onward)?

Another test, would be to compare the MBtile version of your file instead of GeoTiff.

**Comment by dracic** [comment]
I use Pocopohone F1, so I suppose it is x64. I never had issues with gpkg or mbtiles, although I made smaller subsets of that layer.
