### ISSUE TITLE
Polygon not showing up

### ISSUE THREAD

**Issue by aleruete** [lutraconsulting/input#504]
When I load a project with some point layers, some polygon layers and some WMS background layers, one of the two polygon layers won't show up. If i make changes to the project and open it again in QGis the layers are there. It happens with a couple of projects.  I can share one of those if you want to know more. Is there any known issues about this? Thanks

**Comment by saberraz** [comment]
Hi @aleruete 
I am not aware of such issue. If you can see the feature in QGIS, it should appear with the same style in Input. 

Would it be possible to share the project on Mergin with me (my username is saber) so that I can have a closer look.

**Comment by aleruete** [comment]
> saber

Thank you, now I have invited you! the project is called Parking
