### ISSUE TITLE
IOS - swipe up bar covers icons

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#513]
IOS  - iPhone 11 - Swipe up bar at bottom of screen obscures icons

![IMG_2123](https://user-images.githubusercontent.com/8775395/69005543-ab6c9680-0977-11ea-818e-1e024e12b343.PNG)

**Comment by saberraz** [comment]
See also https://github.com/lutraconsulting/input/issues/476

**Comment by sklencar** [comment]
Both this and #476 issue is fixed in build using `Qt 5.13.1`, however currently using `Qt 5.11.3` for the release build.

**Comment by sklencar** [comment]
Resolved by upgrading to QT 5.14.2
