### ISSUE TITLE
IOS - iPhone 11 - cannot add objects

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#514]
I am unable to add objects on iphone 11.

Record, add point (red pin flashes on screen), add attributes and save but no point added. GPS is within threshold (green)

I assume I can use same Mergin login on multiple devices (I use either iPhone 11 or iPad Air depending on work)?

**Comment by saberraz** [comment]
Could you share the project with me on Mergin (my username is saber)?

**Comment by tastrax** [comment]
Done.

**Comment by saberraz** [comment]
that's odd. I have just added a point and it appears on the map (I am using iPhone 8+):
![image](https://user-images.githubusercontent.com/2649047/69039671-4733ec00-09e4-11ea-9a69-7d2347041a9e.png)

Maybe the point is hidden below the GPS indicator?

**Comment by tastrax** [comment]
I think it is something to do with being logged into two devices at the same time with the same credentials. I just logged out of two devices (iPhone11 and iPad Air4). Logged into to iphone and added a point  without issue. Logged into iPad Air and now it wont add a point.

**Comment by saberraz** [comment]
This should be resolved in the next release with this PR https://github.com/lutraconsulting/input/pull/489

In QGIS, it should all work fine (through the plugin): syncing and refreshing the map should display the changes.

**Comment by tastrax** [comment]
I am getting no sync in QGIS whatsoever - no menu option to Synchronise. Are the two issues related?

![NoSync](https://user-images.githubusercontent.com/8775395/69040888-b93b1e00-0a42-11ea-8940-52c221d0d4e9.jpg)

**Comment by saberraz** [comment]
You need to download the project locally first. And then right click on it to download/upload.
