### ISSUE TITLE
Missing DLLs in Windows installer

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#517]
On  a fresh Windows, after installing Input I got the following missing DLLs:

![image](https://user-images.githubusercontent.com/2649047/69095136-9d874600-0a49-11ea-9c2e-ff6c3a6deed0.png)
![image](https://user-images.githubusercontent.com/2649047/69095159-ab3ccb80-0a49-11ea-8780-38904e68620d.png)

**Comment by saberraz** [comment]
MSVCR100.dll issue was resolved by installing:
https://www.microsoft.com/en-us/download/details.aspx?id=13523

**Comment by saberraz** [comment]
Here is the log from dependency walker:
[dep_walker.txt](https://github.com/lutraconsulting/input/files/3860956/dep_walker.txt)

**Comment by saberraz** [comment]
And this one is the log when I profile Input.exe through dependency walker:
[Input_dep_walker_profiling.zip](https://github.com/lutraconsulting/input/files/3862692/Input_dep_walker_profiling.zip)

**Comment by PeterPetrik** [comment]
fixed https://github.com/lutraconsulting/input/commit/bcbd850d3a787141d337424056bbcbe271838b2e

and win-sdk:4
