### ISSUE TITLE
HTML map tips - font tag issue

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#528]
I tried to format my custom info popup with bigger font and colors similar to the default one. I tried this way:

```
<font size="5" color="#006146">
GJ: [% "gjnaziv" %]<br>
Odsjek: [% "oznaka" %]<br>
Površina: [% "povrsina" %] ha<br>
Uređajni razred: [% "urrazrednaziv" %]<br>
Starost: [% "starost" %]<br>
</font>
```
This doesn't work in Input (QGIS accepts this form), but this one does:

```
<font color="#006146"><font size="5">
GJ: [% "gjnaziv" %]<br>
Odsjek: [% "oznaka" %]<br>
Površina: [% "povrsina" %] ha<br>
Uređajni razred: [% "urrazrednaziv" %]<br>
Starost: [% "starost" %]<br>
</font></font>
```

Is this Qt specific or Bug?

Best regards

**Comment by saberraz** [comment]
The 2nd is inline with: https://doc.qt.io/qt-5/richtext-html-subset.html (see **font** section).
