### ISSUE TITLE
Allow autosync of records on opening app and save of records

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#537]
Feature Request - It would be great to allow autosync of features on save. In this way casual users can just grab a quick record and it automatically gets sync - no need to go to a different screen and sync. Likewise, autosync on start of app to get the latest data in shared or private projects.

**Comment by saberraz** [comment]
That is indeed a nice feature. The app checks if there is network connectivity and if so, it will autosync data and projects in both ways. Maybe, this should be an option under settings, so users can switch between manual sync and auto sync.

**Comment by tastrax** [comment]
That would be great - I also regularly work completely offline (out of 4G/3G range) as well, so having the option is great.

**Comment by chris9404** [comment]
What is the status on this enhancement? 
We find that clients forget to sync manually. They work in fields where there is often no signal, so an option to auto sync when connecting to WIFI would be nice to have.

**Comment by wonder-sk** [comment]
hi @chris9404 this has not been worked on yet... If you'd like to get it implemented sometime soon, please contact us at info@lutraconsulting.co.uk

**Comment by wonder-sk** [comment]
Rough idea on how this could be implemented:

![image](https://user-images.githubusercontent.com/193367/138163351-889b035a-6835-4c92-869c-661818d9a394.png)

**Comment by tomasMizera** [comment]
Implemented in #2012
