### ISSUE TITLE
Project reloading workflows

### ISSUE THREAD

**Issue by timlinux** [lutraconsulting/input#542]
If I update a project on the desktop I should follow this workflow:

1. Save the project in QGIS
2. Synchronise the project in Mergin plugin in QGIS
3. Go to My projects in Input and press the dual arrow icon to sync
4. Go to home and open the project

However if the project is already open in Input, the updated project is not shown when you return to the main, the fresh project is not shown, you need to hard quite Input, restart it and then the updated project is shown.

Proposed fix: Unload the project before you sync if the project being synced matches the active project.

**Comment by PeterPetrik** [comment]
This is REALLY annoying bug ...
