### ISSUE TITLE
Device information to attributes

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#547]
Is there any way to add information from the device to attributes? 

For instance

- Username
- device type
- GPS HDOP, PDOP etc

**Comment by tastrax** [comment]
If I use the variable  @user_full_name  I get "Mobile User" in Input. Any chance that can be replaced by something identifying the user (from device settings)

**Comment by saberraz** [comment]
Similar to this: https://github.com/lutraconsulting/input/issues/490

You can use Mergin username. But the other meta-data will be good to have as a part of project on Mergin, so you can have a full history of your project.

**Comment by saberraz** [comment]
See also: https://github.com/qgis/QGIS/issues/35846

**Comment by saberraz** [comment]
Related also to: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/111

**Comment by wonder-sk** [comment]
Mergin-related QGIS variables are supported in Input >= 0.7.0

See https://github.com/lutraconsulting/input/blob/master/docs/users/project_config.md#qgis-variables

**Comment by sukuchha** [comment]
is it possible to get GPS location in an attribute field now?

**Comment by saberraz** [comment]
Related to https://github.com/qgis/QGIS/issues/41543

**Comment by saberraz** [comment]
@sklencar as discussed

**Comment by sklencar** [comment]
@saberraz Could you please specify requirements for attributes - e.g. name, type, format.

Here is a [link](https://qfield.org/docs/prepare/attributes-form.html?highlight=variables#additional-variables) for additional variables in QField. Note that some of them are available only from external position source.

Thanks.

**Comment by wonder-sk** [comment]
things to capture with variables:
- latitude
- longitude
- altitude
- accuracy (in meters)
- [altitude accuracy]
- speed
- gps heading
- [gps time]
