### ISSUE TITLE
Hidden fields showing in interface - IOS

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#549]
Fields that are hidden in QGIS form design are partly visible in Input. Labels are still visible.

![RespectHiddenFields](https://user-images.githubusercontent.com/8775395/70117856-95bad900-16ba-11ea-81d8-8e2a14ea4cd2.PNG)

**Comment by saberraz** [comment]
Hmmm...I cannot replicate this issue. Here is my form where **fid** is set to **Hidden** widget:
![image](https://user-images.githubusercontent.com/2649047/70122061-d2111980-1667-11ea-99d0-8c4ec58f1a2c.png)

And it appears fine in Input (on my iPhone):
![IMG_0049](https://user-images.githubusercontent.com/2649047/70122548-c114d800-1668-11ea-9158-4b7b4fdbfbdd.PNG)

**Comment by wonder-sk** [comment]
Maybe you used some kind of widget that's currently not supported by Input?

**Comment by tastrax** [comment]
Mmmm - I will check again.

**Comment by tastrax** [comment]
fid is autogenerated
last_updated is just Date/Time

**Comment by saberraz** [comment]
Could you share the screenshot of your attribute edit widget settings (similar to the first image in https://github.com/lutraconsulting/input/issues/549#issuecomment-561516424) for fid and laste_update?

**Comment by tastrax** [comment]
![last_updated](https://user-images.githubusercontent.com/8775395/70131153-eee43600-16d5-11ea-8688-fe680781b8eb.jpg)

![fid](https://user-images.githubusercontent.com/8775395/70131175-f572ad80-16d5-11ea-9753-e778c50e9e7f.jpg)

**Comment by saberraz** [comment]
That is very strange! What can you see in QGIS attribute table when in **Form View**?
![image](https://user-images.githubusercontent.com/2649047/70131547-65534a80-167a-11ea-87a8-242c1a047dc1.png)

**Comment by tastrax** [comment]
![FormView](https://user-images.githubusercontent.com/8775395/70132374-3370d100-16d8-11ea-8202-bebe039d93e7.jpg)

**Comment by tastrax** [comment]
Only fid is hidden at the moment

**Comment by tastrax** [comment]
OK - I just dropped the whole project and reloaded and its working as expected

**Comment by tastrax** [comment]
OK - I think I can replicate the issue. Change from Autogenerate to drag and drop designer (and alter the form layout) - then sync. It then fails by adding the hidden field labels

![editformlayout](https://user-images.githubusercontent.com/8775395/70133377-14733e80-16da-11ea-94bb-7d0dc22dc37f.jpg)

**Comment by tastrax** [comment]
I am assuming this means its a QGIS issue and nothing to do with Input, I will close the issue.

**Comment by saberraz** [comment]
Indeed, best to open a QGIS bug report. Another suggestion for your form: you can use multiple "tabs" to group different fields.

**Comment by tastrax** [comment]
This in now resolved - the issue is only in QGIS now (where blanks spaces are left in the form)
