### ISSUE TITLE
Inconsistent behaviour of Back button

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#551]
There are several issues with android "back" button...

It is not always consistent with in-app "back" button in the top-left corner of pages:

A: Click on a feature in map, then click again the popup to open "feature" panel, then press Back button
Issue: Nothing happens
Expected: Go back to map panel like when the in-app "back" button is pressed

B: Go to Settings > About and then press Back
Issue: it takes you to the map
Expected: Go back to Settings panel like when the in-app "back" button is pressed

When in "map" panel, android "back" button should have the meaning of going one step back. Cases where this is not correct:

C: Press Record button to go to Record mode, then press Back
Issue: Nothing happens
Expected: recording is canceled as if the Cancel button in toolbar got pressed

D: Press Record button to go to Record mode, then click on survey layer name (light green area) to open a popup with active layer selection, then press Back
Issue: Nothing happens
Expected: it should go back to the Record mode with no switch to the active layer

Finally, there's a bit of random behavior:

E: when in main "map" panel and press android back button, sometimes it works (minimizes the app) and sometimes it does nothing.

**Comment by saberraz** [comment]
The back button behaviour has become more unpredictable: minimising the app mostly, which is very confusing for users

**Comment by saberraz** [comment]
1- Open Input > Open a project > when the map canvas appears press Back button
Issue: Nothing happens
Expected behaviour: go back to Projects Home

2- When in Record mode
Issue: Nothing happens
Expected behaviour: Nothing should happen...it gets too complicated with lines/polygons

3- When you press Record with multiple Survey layer and try to select a survey layer:
Issue: Back button does not do any thing
Expected behaviour: it should go back to the record mode with no switch to the survey layer

**Comment by saberraz** [comment]
4- Open Input, go to projects (lands on Home tab), then My projects (or Shared with me...or Explore). Then press Back button
Issue: It takes you the map
Expected behaviour: I think it should be Home

(we should have all the Back operation eventually ending up on Home. Pressing Back from Home, should send the app to the background).

**Comment by wonder-sk** [comment]
For point 1 - my expected behavior is that the app gets minimized (closed). Because the "map" panel is the main panel of the app. "Projects" panel is on top of "map" panel when it is open.

**Comment by wonder-sk** [comment]
For point 4 - I think that's correct behavior...

**Comment by wonder-sk** [comment]
5- a bit random behavior - when I am in main "map" panel and press android back button, sometimes it works (minimizes the app) and sometimes it does nothing

**Comment by saberraz** [comment]
6- Go to Settings > About  and then press Back
Issue: it takes you to the map
Expected behaviour: It should take you to the Settings page (same behaviour as the embedded back on top left)

**Comment by saberraz** [comment]
7- When editing a form, select Delete, it comes up with the confirmation window.
Issue: Back button does not do anything
Expected behaviour: Back should take you back to the form

**Comment by saberraz** [comment]
8- When editing geometry of an existing point (from Edit Form, Edit geometry):
Issue: Back button does not do anything
Expected behaviour: It should leave the geometry as it was and take you back to the form

**Comment by saberraz** [comment]
9- When editing a date using calendar widget, select a date on the widget but do not press OK, and press Back
Issue: it sets the date according to the selection
Expected behaviour: it should leave the date as it was. There is an OK button to confirm the date. Back button should mean = cancel

**Comment by tomasMizera** [comment]
Update on point E: app is minimized only when at least one feature was opened, if it was not, back button does not work
