### ISSUE TITLE
Switch between GPS providers and datum grids

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#552]
If user has external GPS for better accuracy.  One way to switch between native GPS and external GPS is to use system settings.

It would be good to have an option in Input to switch between them without digging into system settings.

**Comment by saberraz** [comment]
A better method is to have **Location Profiles**, where users can set:
- GPS provider
- Grid shift
- Accuracy threshold

**Comment by saberraz** [comment]
The grid shift is addressed by https://github.com/lutraconsulting/input/pull/1051 but it would be nicer to have it automatically downloaded.

**Comment by PeterPetrik** [comment]
External GPS switch released in Input 1.3.0
