### ISSUE TITLE
Not possible to change Time field

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#558]
Here is my setting for a time field:
![image](https://user-images.githubusercontent.com/2649047/70305082-61026b00-17fb-11ea-95ae-5e4538663f9a.png)
But when I try to change the time in Input (by deleting HH:MM:SS) and inserting a new time, it keeps resetting itself to --:--:--

**Comment by saberraz** [comment]
Also, in iPhone, it becomes almost impossible to tap on the calendar widget on the right to set the default time.

**Comment by wonder-sk** [comment]
Fixed in https://github.com/qgis/QGIS/pull/38637
