### ISSUE TITLE
Not possible to change the date when custom format is used

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#559]
By default, date is set to yyyy-MM-dd
If I change it to a custom format: dd-MM-yyyy, it will become impossible to change it in Input.
![image](https://user-images.githubusercontent.com/2649047/70306280-5dbcae80-17fe-11ea-822a-d41d9abf348f.png)

**Comment by tastrax** [comment]
I have noted that with custom format dd/MM/yyyy I get a similar issue.

I also have default value set as  format_date( $now,'dd/MM/yyyy') which allows you to change the date but the format is incorrect when changed and reverts to MM/dd/yyyy

**Comment by wonder-sk** [comment]
Fixed in https://github.com/qgis/QGIS/pull/38637
