### ISSUE TITLE
Sync fails when phone goes to sleep

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#563]
As reported by iPhone user - if the sync takes longer and you don't keep touching the screen to keep it on, the phone goes to sleep which essentially breaks the sync process in the middle and it fails.

This problem does not happen on Android as we force the screen to be on all the time while Input is running in the foreground...

**Comment by mostlyAtNight** [comment]
A possible workaround for this issue until we have a long-term fix would be to:

1. Stop your screen from locking (see link below)
2. Plug in your phone
3. Start the sync and leave it running with the screen unlocked (not near any strangers!)

https://www.howtogeek.com/685035/how-to-stop-your-iphone-screen-from-turning-off/
