### ISSUE TITLE
An option to zoom to the extent of survey layer

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#577]
Would be good to have an option to zoom to extent of survey layer.Currently, zoom to project, zooms to all layers and user can get confused (e.g. if using an XYZ for global coverage.)

**Comment by gubuntu** [comment]
why not use the project extent set in QGIS Server OGC properties?

**Comment by wonder-sk** [comment]
That sounds like a good option. Ordinary users may not be aware of that configuration option at all, but I guess if we document it somewhere, it should not be a problem...

**Comment by gubuntu** [comment]
nice!
