### ISSUE TITLE
Refresh the map after sync

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#579]
It is not clear what has changed after sync. It would be good to refresh the map after each sync for the added/deleted features to show up immediately, without needing the user to zoom in/out or pan.

**Comment by gubuntu** [comment]
in my experience, one has to open another project after sync and then re-open the one you're working on, to force read of all data and project updates. I agree the whole project should auto-reload after sync

**Comment by saberraz** [comment]
Addressed in 0.6.4
