### ISSUE TITLE
Update Geopackage File

### ISSUE THREAD

**Issue by VincentaLayer** [lutraconsulting/input#583]
Hi I have problems with synchronization of my Geopackage file with the Input App.
I created one Geopackage file. This contains 1 boundary layer and my groundthruth layer.
Now I add another boundary layer and add this to my existing geopackage. In my QGIS project
it looks all fine and I go the mergin plug in and press synchronize. But however if I go back to my Input App I can only see one boundary. What could be the problem. It must be possible to layer files and add them without problem?
Greetings

**Comment by saberraz** [comment]
This appears to be related to #584
