### ISSUE TITLE
Input only loads Map Themes

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#584]
and not the current layers visibility, if there is a map theme.

To replicate the issue:

- Add layer A and B
- Create a Map theme based on the visibility of layers A and B
- Upload your project to Input
- Add Layer C

Input does not show Layer C, even if the project was saved with no map theme and Layer C was visible.

**Comment by saberraz** [comment]
Could be related to this: https://github.com/qgis/QGIS/pull/34794

**Comment by wonder-sk** [comment]
@saberraz This should be fixed by #789 I believe, can you test again with a build from master?
