### ISSUE TITLE
Any change for earlier IOS?

### ISSUE THREAD

**Issue by Pi-R-O-Scan** [lutraconsulting/input#587]
Hi, sorry to bother but I was so excited to discover your tool, and suddenly so disapointed that it does not fit with my IPAD 4 which cannot upgrade higher than IOS VERSION 10.

I guess I ll be able to use the android version on my tiny phone screen, but just in case it would be easy to make a version that suits to IOS 10. this would really be fantastic.

Merci merci merci in advance if you manage that !

Great job you are doing... I have to sink in QGIS now to understand how to prepare projects (I suppose there might be plugins to install

.

**Comment by saberraz** [comment]
Hi @Pi-R-O-Scan 

Unfortunately, with Apple software development, they make things a bit difficult to build for older versions. All the SDKs and tools are more geared towards the latest iOS.

Input should work well on small screen (we are keeping the interface simple intentionally, to allow mobile users to use it). 

For a basic instruction, please follow this tutorial:
https://www.lutraconsulting.co.uk/blog/2020/02/14/survey-qgis-input/

**Comment by Pi-R-O-Scan** [comment]
Thanks @saberraz  I understand, my main concern yet is about trying to get a grip on QGIS, -A video Tuto would be great for project preparation and also ABOUT the 300Mb  orthophoto that I have and wether a phone will handle that... let's see
