### ISSUE TITLE
tap field to close pick list

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/input#590]
If you tap on a field with a pick list, it expands. But say you don't want to do anything but instead want to just close the pick list. At the moment you have to either reselect the original entry or use the device back button. 

Ideal behaviour - just tap on the field name again to close the list.

**Comment by saberraz** [comment]
How about tapping anywhere on the map? This behaviour is similar to Google Map and we thought users are already familiar with this behaviour?

**Comment by gubuntu** [comment]
a big pick list takes up the whole screen (as does a big form) so there's no map to tap, otherwise tapping the map would be fine. I personally don't mind hitting the device back button but the client didn't find that intuitive or felt it somehow wrong.

**Comment by saberraz** [comment]
Sorry, I misunderstood the pick list with the pop-down window for feature identify. Now, I see what you mean.

**Comment by saberraz** [comment]
I guess this can be closed @wonder-sk @gubuntu ?

**Comment by wonder-sk** [comment]
yeah - with value relation widget if the list is longer than ~5 items, a full-screen page is shown with a back button.
