### ISSUE TITLE
multiline text edit keyboard blocks Save

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/input#592]
If you hit Enter while editing a multiline field it just adds another line. You have to tap another tab or device backspace to close the keyboard so you can see the Save button.

**Comment by saberraz** [comment]
The correct UI for this should be similar to other apps, where the green bar should move above the keyboard.

**Comment by saberraz** [comment]
Duplicate of https://github.com/lutraconsulting/input/issues/384
