### ISSUE TITLE
implement skip logic

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/input#593]
depending on the response to a question, skip to another question or section

this may be an upstream QGIS issue? But it is a blocker against competing apps.

**Comment by saberraz** [comment]
@gubuntu is it related to forms?
If so, it is implemented in QGIS, we just need to port the widget to Input.

**Comment by gubuntu** [comment]
yes, like https://www.surveymonkey.com/mp/tour/skiplogic/

**Comment by saberraz** [comment]
With visibility group, you can achieve the same result. See https://twitter.com/timlinux/status/1283850239431057409
