### ISSUE TITLE
Input not honouring 'order by value'

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/input#595]
a pick list that is ordered by value in desktop is scrambled in Input

![Screenshot_20200310_110753_uk co lutraconsulting](https://user-images.githubusercontent.com/496911/76307489-96729500-62d1-11ea-998b-467da27a09dc.jpg)

**Comment by saberraz** [comment]
Works with this PR:https://github.com/wonder-sk/QGIS/commit/7c948506080e32c8a402677abac7f41043af7c98
![Screenshot_20200311-163406_Input](https://user-images.githubusercontent.com/2649047/76440915-7cf74900-63b6-11ea-8117-6c699794fb08.png)
