### ISSUE TITLE
Allow autocompete in forms with relations

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#596]
- Allow autocomplete
- Allow shortlisted matches when user types the first 2-3 letters

**Comment by wonder-sk** [comment]
I guess in case the list is longer than N items, we should we showing a full-screen panel with the list where at the top there would be search box that would server as a filter, and the keyboard would pop up immediately so that user can start typing.

**Comment by wonder-sk** [comment]
@saberraz can we close this one given that we have search in 0.7.x ?
