### ISSUE TITLE
Expired MapTiler TMS key : slow down demo project

### ISSUE THREAD

**Issue by kikislater** [lutraconsulting/input#598]
in demo.qgis : there are 2 maptiler basemaps : 

```

https://maps.tilehosting.com/styles/hybrid/%7Bz%7D/%7Bx%7D/%7By%7D.jpg?key%3DQrAbC1d6GEE5cT40IrCj&zmax=18&zmin=0
 
https://maps.tilehosting.com/styles/basic/%7Bz%7D/%7Bx%7D/%7By%7D.png?key%3DQrAbC1d6GEE5cT40IrCj&zmax=18&zmin=0
```

But maptiler keys seem to be expired. TMS are not rendered and project is slow when zoom in / zoom out. 

Could be better to make a demo project without keys like one standard provided ine qgis > tile.openstreetmap.org

**Comment by saberraz** [comment]
Thanks for reporting the issue. This PR should fix it
https://github.com/lutraconsulting/input/pull/599
