### ISSUE TITLE
Broken camera

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#611]
With the recent PRs (update to native camera and update the new sdk) I can no longer use the camera:
![Screenshot_20200414-115310_Input](https://user-images.githubusercontent.com/2649047/79217395-b8b68000-7e46-11ea-9861-07c4afa990d6.png)

**Comment by PeterPetrik** [comment]
which APK do you refer to?

**Comment by saberraz** [comment]
https://github.com/lutraconsulting/input/pull/608#issuecomment-611364198

Ahhh...the native camera is not yet merged.

**Comment by PeterPetrik** [comment]
@saberraz is this still issue?

**Comment by saberraz** [comment]
This is related to a WIP PR.
