### ISSUE TITLE
Allow create and upload new projects

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#614]
If users have a (n orphan) project on their device not linked to a Mergin server project, we need to offer an option to upload and create a new project (if the namespace is available) on the Mergin server.

**Comment by wonder-sk** [comment]
There is a related question to that - when does a project become orphaned? If it was originally download from Mergin, Input will keep that link. Maybe some advanced option somewhere to detach the project from Mergin? And then a way to create+upload a directory to Mergin as a new project?

What I am trying to solve with the above is that automatic detection of orphaned projects may not be reliable. Or the case when the original project should be still kept for some reason and only the local project should be re-uploaded with a new name...
