### ISSUE TITLE
Cannot load online background maps

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#617]
Internet and openssl seems to be working - can login and sync a project from/to Mergin. However, any online background map is not showing, but its contained as a layer in the layer list.
Tried several projects, also with http xyz tiles from openstreetmap:
```
Source
crs=EPSG:3857&format&type=xyz&url=http://a.tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=19&zmin=0
```
Note: Its not showing on both iOS and Android. The former one is without proj.db, Android build is not complaining about proj.db anymore. (TODO: make sure it or it is not set)

**Note**: some providers have been filtered before, fix is here: https://github.com/qgis/QGIS/pull/35890

**Comment by PeterPetrik** [comment]
fixed by https://github.com/lutraconsulting/input/pull/618
