### ISSUE TITLE
APK on android size

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input#621]
APK on android bumped from ~50 to 150MB at 9April with android-7 SDK... qgis_core has 300 MB now... maybe debug build?

**Comment by PeterPetrik** [comment]
android-4 (qt 5.11)
17M	lib/arm64-v8a/libqgis_core.so
android-8 (qt 5.14)
335M lib/arm64-v8a/libqgis_core_arm64-v8a.so

**Comment by PeterPetrik** [comment]
reason... https://github.com/android/ndk/issues/243

fixed with `CMAKE_CXX_FLAGS_RELEASE = -g0` workaround

**Comment by PeterPetrik** [comment]
fixed by https://github.com/lutraconsulting/input-sdk/commit/f3862a7175423e2f00a8969c0f519bbec666dd72

**Comment by PeterPetrik** [comment]
@saberraz can you please create android-9 SDK?

**Comment by saberraz** [comment]
Done and uploaded.

**Comment by PeterPetrik** [comment]
https://www.dropbox.com/s/cl0fdn8eqbu3cva/input-master-3cde7d387934909eca229a31ab7d36f18bd75537-arm64-v8a-signed.apk?dl=0

53 MB
