### ISSUE TITLE
digitise a geometry for an existing record when geom is null

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/input#623]
sometimes existing records have no geometry, so:
- you don't want to create a new record
- there's no geometry to edit

proposal: Implement an 'add part' equivalent, which is how you would do it in QGIS

**Comment by saberraz** [comment]
With https://github.com/lutraconsulting/input/pull/811 you can now add geometry for Points. 
For polygons and lines, we need to implement https://github.com/lutraconsulting/input/issues/471 and it will address the issue.
