### ISSUE TITLE
Drag and drop designed forms are no longer supported

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#632]
This is related to release 0.6.0 testing:

It always displays it as the default form layout.

**Comment by saberraz** [comment]
![image](https://user-images.githubusercontent.com/2649047/80469486-86be1700-8938-11ea-8e4e-47d9d1925bb0.png)

**Comment by wonder-sk** [comment]
@saberraz I think that's just because of the fact that the first "hidden" item is not inside tabs container - if it would be, tabs should show up correctly in Input... (this was never supported I think)

Shall we close this? Or change to a feature request?

**Comment by saberraz** [comment]
That is correct. If there is a one column outside the groups, it does not show up.
