### ISSUE TITLE
Calendar widget icon missing

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#639]
There used to be a calendar icon to the right of the editing line which set the date/time to the current date/time, but it is missing:
![Screenshot_20200501-082413_Input](https://user-images.githubusercontent.com/2649047/80789999-94b4a780-8b85-11ea-810d-420e46bff813.png)

**Comment by wonder-sk** [comment]
Should be fixed in https://github.com/qgis/QGIS/pull/36152

**Comment by PeterPetrik** [comment]
merged the QGIS pr
