### ISSUE TITLE
External GPS Reciver

### ISSUE THREAD

**Issue by Scott-Lewis-hub** [lutraconsulting/input#640]
I am looking to setup my phone 8 with the input app to collect GPS data.
I have the app working correctly using the internal GPS of the phone however this is not accurate enough for my work. I have a Trimble R2 GPS that i would like to connect to the app and use this data in the input app.

Can you please provide guidance on how to do this. 
It does say on the input web home page that this app supports external GPS receivers.

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/input/issues/552

**Comment by saberraz** [comment]
See:
https://help.inputapp.io/howto/external_gps
