### ISSUE TITLE
Problem taking photos

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#642]
✓ and ☓ are not available on Samsung Galaxy phone (xx model??)

**Comment by TonyShep** [comment]
Clicking "Take a photo" opens and displays the camera, but there are no controls to take an image or cancel.
Two handsets:
  Samsung Galaxy Note 9 (Android 10 QP1A)
  LG H930

**Comment by PeterPetrik** [comment]
this should be fixed by https://github.com/lutraconsulting/input-sdk/commit/1dc9453b28d0f30edb8dee6c5a5cc7b1d7e465c1 in next version

**Comment by elanioazul** [comment]
Yes, when uptaking a photo, there is no botton to confirm your ok to updtake that photo. There is only one button of "going back" and you end up without the photo you wanted to take.

**Comment by saberraz** [comment]
Could you make sure:
- You are using the latest version of Input 
- You can replicate it with this project on Mergin: in Input, go to Projects > Explore > saber\test_forms

This could be your project misconfiguration to save the photo in the wrong path.

**Comment by elanioazul** [comment]
Hi, Im using version 0.6.1 so current version, and in my project photos cannot be uptaken. Same version is saving perfectly photos in saber/test_forms project so it seems a self project problem. But I have for the attachment relative paths to the project directory, as I tought was the right way.
