### ISSUE TITLE
Input app not starting on Samsung.

### ISSUE THREAD

**Issue by Mikester-Calgary** [lutraconsulting/input#645]
![IMG_20200505_113935_01](https://user-images.githubusercontent.com/64865458/81106093-3b74ad00-8ed2-11ea-9fc2-a6812b9c7783.jpg)

Error message on Samsung startup "Input keeps stopping".

**Comment by saberraz** [comment]
Duplicate of #641

**Comment by Mikester-Calgary** [comment]
Sab
I don't see and answer or.a fix there...

**Comment by saberraz** [comment]
Unfortunately Android 32-bit is broken and we are working on a fix. Meanwhile you can downgrade to:
https://github.com/lutraconsulting/input/releases/download/r0.4.90/input-armv7-signed_v0.4.9.apk

Once downloaded and installed Input, please do not update until we push version 0.6.1

**Comment by Mikester-Calgary** [comment]
Thanks Sab.  Very impressed with your responsiveness.  (And your product to
this point.)
m
