### ISSUE TITLE
Add WMTS support

### ISSUE THREAD

**Issue by romainbh** [lutraconsulting/input#650]
WMS layers work fine, but WMTS won't load.

I.e. the web map services of Switzerland:
- WMS works ([link](http://wms.geo.admin.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0&lang=fr))
- WMTS not ([link](http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml?lang=fr))

Thanks a lot for your work!

**Comment by saberraz** [comment]
Hi @romainbh 
thanks for reporting the issue. I think the source of issue is probably QGIS.

When you set up your project in QGIS, did you add it from your Browser panel or from Data Source Manager? See:

https://github.com/qgis/QGIS/issues/36264

**Comment by romainbh** [comment]
Hi @saberraz 
Thanks for your answer.

I add WMTS layers from Data Source Manager, they work fine in QGIS (see example below).
[wmts_test.zip](https://github.com/lutraconsulting/input/files/4594215/wmts_test.zip)

But you're right, QGIS has an issue when adding WMTS from Browser ;-)

**Comment by saberraz** [comment]
I am closing this as it is related to QGIS.

**Comment by romainbh** [comment]
Some news: I tested the [project](https://github.com/lutraconsulting/input/files/4594215/wmts_test.zip) with [QField](https://qfield.org/) and it works fine. The issue should not be in QGIS but really in Input.

**Comment by saberraz** [comment]
Hi @romainbh 
This appears to be an issue with the recent versions of QGIS master (which Input is based):
![image](https://user-images.githubusercontent.com/2649047/84660184-6231f480-af10-11ea-96ca-772f5269cdee.png)

**Comment by romainbh** [comment]
Hi @saberraz 
Thanks for your answer. Damn, I hope this will be fixed before the next QGIS release. And this way Input will be able to show WMTS layers 👍

**Comment by saberraz** [comment]
Hi @romainbh 

If you add the link from the Data Source manager (and not the browser panel), you can still use the WMTS in QGIS and Input. It is just an issue with the WMTS when added from the Browser Pannel

We will look into the issue for the next QGIS and Input release.

**Comment by romainbh** [comment]
Hi @saberraz 

I just tested again, and I found something interesting! Here are two projects: [WMTS_Input.zip](https://github.com/lutraconsulting/input/files/4786567/WMTS_Input.zip)

Both are exactely the same (same WMTS layers in EPSG:21781, same themes), except the CRS of the project. One project is in EPSG:21781, the same as layers, and the second is in EPSG:2056.

**Result:** the project in 21781 works fine in QGIS and Input, but the one in 2056 doesn't work in Input (but works fine in QGIS 3.12.3 and also in QField).

So the project with reprojection from 21781 to 2056 cause an issue. But I don't know if this issue is due to the master version of QGIS/Input or Input itself...

Hope this helps

**Comment by saberraz** [comment]
It is definitely QGIS master:
![image](https://user-images.githubusercontent.com/2649047/84775722-755bc780-afd7-11ea-912c-b39eb3c15e63.png)

**Comment by romainbh** [comment]
Hope this will be fixed soon ;-)
Thanks a lot @saberraz for your help and for this amazing app!

**Comment by saberraz** [comment]
No problem at all. We will fix the issue in QGIS 3.14 and update the SDK for Input shortly after QGIS release.

**Comment by saberraz** [comment]
Hi @romainbh I managed to get to the bottom of your issue both in QGIS and in Input.
![image](https://user-images.githubusercontent.com/2649047/84779217-06cd3880-afdc-11ea-8796-0a90c738bc18.png)
![Screenshot_20200616-141705_Input](https://user-images.githubusercontent.com/2649047/84779444-50b61e80-afdc-11ea-8e8f-6c8c8705025a.png)

**Comment by saberraz** [comment]
This is due to the grid shift for datum transformation in GDAL 3+. Your project requires `CHENyx06a.gsb ` for transformation between EPSG:21781 to EPSG:2056.

Input and QGIS are both using GDAL 3+. Hence you need to manually download the grid shift. In QGIS the download is handled automatically. But in Input, we have not implemented the download of the gsb files automatically.

BUT...if you are using Input on Android, you can copy the attached GSB file (download and unzip) to `/sdcard/INPUT/qgis-data/proj/` folder. The transformation will have an improved accuracy of 0.01m!!!

We would like to handle the downloading and applying the grid shifts automatically. As iOS users currently cannot have such a work-around.
[CHENyx06a.gsb.zip](https://github.com/lutraconsulting/input/files/4786840/CHENyx06a.gsb.zip)

**Comment by romainbh** [comment]
Oh yeah, it works! Thanks a lot for your help!

In Switzerland we have these two EPSG, an old (21781) and a new (2056). The new is most and most used, but a lot of layers remains in the old SCR... Even the Swiss Confederation is still using the old system (the WMTS layers came from them).

I had this issue with QGIS 3, I had to download and install this CHENyx06a.gsb file to open all projects containing both EPSG. But it was a time ago... Too bad that GDAL 3+ doesn't contains this grid shift by default.
