### ISSUE TITLE
Edit existing geometry.

### ISSUE THREAD

**Issue by Mikester-Calgary** [lutraconsulting/input#654]
Is it possible to edit existing geometry position with Input without deleting and recording again?

**Comment by saberraz** [comment]
It is possible for Point layers. But not for lines/polygons at the moment (https://github.com/lutraconsulting/input/issues/471)

For changing location of an existing point:
1- Select the point feature on your map
2- A pop-up will appear
3- Select the Pencil icon
4- In the form, select Edit geometry
5- Move the map to where you'd like the new point to be positioned
6- Select Add point
7- Select Save

See the screenshots for 1-2-3, 4, and 5-6
![1-2-3](https://user-images.githubusercontent.com/2649047/81387824-423c3380-910f-11ea-9ba0-be234bdad547.png)
![4](https://user-images.githubusercontent.com/2649047/81387832-45372400-910f-11ea-8818-e0baf1a6be14.png)
![5-6](https://user-images.githubusercontent.com/2649047/81387837-4700e780-910f-11ea-8164-c23cef1cf9d8.png)

**Comment by Mikester-Calgary** [comment]
Sab:
Am I correct that Sync ONLY pushes data from the desktop or the hand held
back to the Mergin cloud space?
So if you want to refresh your hand held or QGIS desktop version you have
to delete it locally and re-download it from Mergin.  Does that sound right?
If you Share a Mergin project with someone and they Sync it back in will
ONLY go back to their Mergin cloud space and not to the Mergin cloud space
of the one who shared it with them.  Correct?
I am having some trouble figuring where my syncs are ending up with someone
I shared my project with.
Thanks as always.
m

**Comment by saberraz** [comment]
Hi @Mikester-Calgary 

The sync should work in all directions. For example:
- If you change your data on your device or PC and there is also change from the server, when you sync on your device/PC, it will patch download and apply changes from server to your local changes. AND uploads the changes to the server and applies the changes to the server copy. So, the files on server and your device/PC have the same status.

For your project sharing with Mergin: when you share a project with a user, they will become a contributor  (depending if you give them write permission). So, when they edit the data, the changes will be synced to YOUR project, the same way you edit your data (i.e. both ways).

For more information, have a look at:
https://www.lutraconsulting.co.uk/blog/2019/11/23/input-geodiff/

Feel free to ping me on my email and I can arrange a quick demo for you.

**Comment by Mikester-Calgary** [comment]
Thanks Sab
That all sounds right to me.
My colleague cannot seem to be able to sync back from his Samsung tablet
for some reason.  I just assumed it was placing the sync version of my
shared Mergin project back into his Mergin account and not mine.
But by your description that should not be the case.  I guess he must have
some trouble on his end.

I read through that page.  Thank you.
When and how can I get my hands on the Beta version of Input?

I will give it one more go before I bug you for a demo.
Thanks for all your help.
m

**Comment by saberraz** [comment]
Hi @Mikester-Calgary 

For sharing to work:
1- Make sure you give Write permission to your colleague
2- Also, your colleague needs to use the latest version of Input from Google Play Store or Apple App Store (see https://inputapps.io) for the links.

The blog post was done a while back. But the feature should be available on the current release from the above link.

**Comment by Mikester-Calgary** [comment]
Sab:
Well it must be issue no 2.
If you recall you sent me this:

Unfortunately Android 32-bit is broken and we are working on a fix.
Meanwhile you can downgrade to:
https://github.com/lutraconsulting/input/releases/download/r0.4.90/input-armv7-signed_v0.4.9.apk


That must be what is getting in the way yes?
Are you saying  this issue has been resolved? And https://inputapps.io  now
contains a version that works?
Thanks again for all your help.
m

**Comment by saberraz** [comment]
Yes, please upgrade to the latest version 0.6.1 on Google Play Store. We have resolved the issue a with 32-bit.

**Comment by Mikester-Calgary** [comment]
Thanks Sab.
Will the update smoke his current project on his device?

**Comment by Mikester-Calgary** [comment]
Sab
Is there anyway now or on the horizon to collect/read RFID tags or bar
codes as part of the field input into the Lutra/Input app?
m

**Comment by saberraz** [comment]
Hi @Mikester-Calgary 
You mean something like this feature request:
https://github.com/lutraconsulting/input/issues/408

**Comment by Mikester-Calgary** [comment]
Something like I guess.  No mention of RFID or anything that I found.
Thanks for responding Sab.
m
