### ISSUE TITLE
Internal Server Error on project download on iOS 

### ISSUE THREAD

**Issue by imaginaryearthnotes** [lutraconsulting/input#656]
- synchronized succesfully a project from QGIS plugin
- when clicking in "Input" on the download button, there comes the error "Internal Server Error" with no progress or result.

**Comment by saberraz** [comment]
Hi @imaginaryearthnotes 

That is strange...can you browse the public projects on Input (Projects > Explore)

**Comment by imaginaryearthnotes** [comment]
ok, sorry. I guess I did not pay close enough attention to the tutorials and settings of projects for syncronizing.
