### ISSUE TITLE
Implement Mergin register page in the App

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#663]
When user tries to register to Mergin from within the app, it opens an external web browser. It will be good to use QtWebView so that it uses the native web browser to render the page from within the app.

**Comment by PeterPetrik** [comment]
alternatively we can use the native QML, usage of QtWebView would bring another dependencies and I am not sure what would it give it to us? I propose to implement it as separate window similar to login page, and implement new API in mergin server for registrations (under some strict conditions, so it cannot be used by bots to do massive auto-registration)

**Comment by PeterPetrik** [comment]
fixed in release 0.7.1
