### ISSUE TITLE
Project status only indicates local changes

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#704]
If I have a change from the server and try to check the status of the project on Input, it displays No Changes. The Sync icon is not affected and correctly shows pending changes from server. The project status correctly displays changes if it is local to the device.

Similar to the Mergin plugin, it should state the pending changes from local and remote.

**Comment by elanioazul** [comment]
I would say, "No changes" message is displayed but at some point those changes arrive to input. I think they would happen quicker.
I also noticed (maybe Im doing something wrong) changes done by colaborators with the right permissions are not being sent back to mergin server. Only mines (owner) are.
Is this only an issue happening to me?
Thx

**Comment by saberraz** [comment]
Hi

Do your users have the correct permission (write) to the project?

To sync their changes, they need to go to Projects > Shared with me > and press the Sync icon to the left of the project.

Depending on the number of users and timing of sync, it will take a number of syncs to have all changes propagated to all users.

**Comment by elanioazul** [comment]
Thank you for the answer
