### ISSUE TITLE
Preview panel - geometry derived info attributes

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#710]
I'm getting a lot of questions from users on how to get some info about recorded geometries (area, lenght). So as a workaround we use labels for that purpose. It would be useful to have something like we have in QGIS when we use identify tool and get geometry derived attributes (area, length, number of vertices), at least for survey layers.

**Comment by saberraz** [comment]
Input supports some basic HTML syntax for the preview panel. You can set that in Display settings of layer (see https://github.com/lutraconsulting/input/blob/master/docs/users/project_config.md#settings-for-input-preview-panel).

For example if you look at saber\test_digitizing project in Mergin (under Projects > Explore): I have set the Display as:
![image](https://user-images.githubusercontent.com/2649047/82641230-f1930300-9c03-11ea-9bdd-abdc2d231b1a.png)

And the result when user identifies the feature on Input:
![Screenshot_20200522-080644_Input](https://user-images.githubusercontent.com/2649047/82641284-07082d00-9c04-11ea-8ae4-7baba9fba04e.png)

**Comment by dracic** [comment]
I completely forgot HTML tips and possibility to do some calculations in them... Sorry. But could be useful for others...
