### ISSUE TITLE
Can Input get the pitch of an device?

### ISSUE THREAD

**Issue by chewbacca0712** [lutraconsulting/input#727]
Hi, When you take a photo, it would be nice if the pitch, roll yaw data was also collected, for example in a text file. For example as [AngleCam](https://play.google.com/store/apps/details?id=com.derekr.AngleCam&hl=en_US).

The Orientation is important to know exactly where what is seen in the photo is.

Thanks

**Comment by saberraz** [comment]
As a work-around: in Android, you can download OpenCamera and extract the info from your desktop PC

**Comment by saberraz** [comment]
Implemented in 0.9.3
