### ISSUE TITLE
Filtering a Value Relation in a form entry to limit selections

### ISSUE THREAD

**Issue by Mikester-Calgary** [lutraconsulting/input#740]
![Input App-Value Relation Filter](https://user-images.githubusercontent.com/64865458/83654530-7c67ec00-a57a-11ea-91f2-99f3516ab7ee.PNG)
 
I have a Value Relation set in a form widget in Input.  The form works fine to get the values but the filter that works fine in QGIS does not work in Input.
I have attached a screen clip of the Value Relation setup I am using.
Will a filter that is applied in this widget not work when uploaded to Input?
Please let me know.
m

**Comment by Mikester-Calgary** [comment]
![Input App-Value Relation Filter](https://user-images.githubusercontent.com/64865458/83655097-37908500-a57b-11ea-89e7-db4d39b453c9.PNG)
Maybe I should have put the whole dialogue box on here.

**Comment by Mikester-Calgary** [comment]
I also notice that the "Allow Multiple Selections" doesn't seem to work in Input either.

**Comment by saberraz** [comment]
> I also notice that the "Allow Multiple Selections" doesn't seem to work in Input either.

Lets have a separate ticket #741 for this.

**Comment by Mikester-Calgary** [comment]
Thanks Sab for the quick response.  Does that mean these are in the works?

**Comment by saberraz** [comment]
Hi @Mikester-Calgary 

The features need to be added to QGIS Quick library and then we should be able to use it in Input. They are definitely useful and generic features which we'd look into for future releases.

Thanks for reporting the issues.

**Comment by sukuchha** [comment]
Qfield implemented this feature,  if this can be made to work in input as well that will be great.

**Comment by she-weeds** [comment]
Am I correct in understanding this particular feature will be released in 0.7 per https://github.com/lutraconsulting/input/pull/852

Would be great to search through options as shown!!

**Comment by Mikester-Calgary** [comment]
Should this feature have been present in the v0.6.90 beta release I am testing presently?

I would have thought it would have been in there???

m

**Comment by Mikester-Calgary** [comment]
That is awesome!  When can we get our hands on it?  Either Test Pilot or new version?

**Comment by saberraz** [comment]
We are doing the testing and should be available in the next week or so

**Comment by Mikester-Calgary** [comment]
You guys are great!
