### ISSUE TITLE
Synchronisation fails

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input#748]
Using Input Beta 6.0.3 on Xiaomi Redmi Note 8 Pro, Android 10, MIUI Global 11.0.2, I am unable to upload project to Mergin. I got various behaviours:

* `FAILED` - Software caused connection abort
* server replied: `BAD REQUEST`. Another process is running. Please try later.
* also `Push request accepted` and the app is closed.

In all cases no file is actually uploaded. The project contains some vector tiles (120mb) and a point vector layer.  While working with the project I have found another problem with attaching a photo after changing phone orientation mode (#728). I was trying to upload the project with the incorrect images (0 kb size) and without them (manually deleted the files).

Project files and logs were uploaded to Lutra internal storage.

**Comment by saberraz** [comment]
@erpas could you try with 0.7.0 release?

**Comment by erpas** [comment]
It works fine with Input 0.7.0
