### ISSUE TITLE
Mergin has just deleted everything!

### ISSUE THREAD

**Issue by Cotnap** [lutraconsulting/input#758]
Trying out Mergin/Input for first time and loaded a sample project and tried creating a few of my own. Decided to clean up projects in QGIS browser before trying again and appeared to have deleted entire folder where projects were sitting which had a lot of other unrelated stuff in it which has now gone! I shudder to think how much work I have lost. Not even in bin. A warning would be useful.

**Comment by saberraz** [comment]
hi @Cotnap 

You are right. We have made it more difficult for users to delete the project from the website. But from the plugin, it is still an issue:
https://github.com/lutraconsulting/qgis-mergin-plugin/issues/128

We will address that in the next release.

**Comment by Cotnap** [comment]
If my understanding of the process is correct - I suggest you disable the Remove Locally option as while it may be convenient for experienced users, the ramifictions for others are too high.

**Comment by saberraz** [comment]
Will be addressed in the QGIS plugin.
