### ISSUE TITLE
iPhone now rotating photos captured in Input

### ISSUE THREAD

**Issue by Mikester-Calgary** [lutraconsulting/input#760]
I updated IOS on iPhone yesterday and now Input is rotating the photos I capture in my Input app.
I anyone else seeing this?  It is not showing the X and the checkmark so I can't even keep the sideways image!

**Comment by saberraz** [comment]
Hi @Mikester-Calgary 
What version of Input are you using (the release on the App Store or the TestFlight?)

Could you make sure you have the Edit Widget for Photo is set correctly?
Widget type: **Attachment**
Default path: **leave as blank**
Select the options for: **Relative paths** and **Relative to project**

![image](https://user-images.githubusercontent.com/2649047/84602547-13d51500-ae80-11ea-8aaf-5a618d7f8e07.png)

**Comment by Mikester-Calgary** [comment]
v0.6.0 from the App Store.
I had a path in the default so I removed it and got back the X and checkmark but it is still rotating the captured image preview.
Thanks for the prompt attention as always!

**Comment by Mikester-Calgary** [comment]
The Integrated Document Viewer is set to "No Content" in case you were wondering.

**Comment by saberraz** [comment]
The document viewer should not affect the camera settings.

If you feel advanutrous, you can use the TestFlight version of Input in iOS. It will allow using the native camera (zoom in/out, HDR, landscape/portrait...etc) when taking phots:
https://testflight.apple.com/join/JO5EIywn

**Comment by Mikester-Calgary** [comment]
How do I get the invitation code?

**Comment by saberraz** [comment]
drop us (info@lutraconsulting.co.uk) an email (the one you have registered with your iPhone) and we can add you to the TestFlight users.

**Comment by Mikester-Calgary** [comment]
Sab:Input ver. 0.6.3 is awesome.  Once the cascading form input works it will be all I could ask for.  (For now.)Good work.  Any idea when it will be ready for broad release?m Sent from Mail for Windows 10 From: SabSent: June 14, 2020 2:18 PMTo: lutraconsulting/inputCc: Mikester-Calgary; MentionSubject: Re: [lutraconsulting/input] iPhone now rotating photos captured in Input (#760) Closed #760.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Mikester-Calgary** [comment]
Sab:
Do we need a new redeem code to run the 0.6.4 Input app from Testflight?
Mine is only showing me the 0.6.3 ver.
I am excited.  Sounds like you got most of the value map form stuff done in
there too.
Please let me know.
m

**Comment by saberraz** [comment]
Hi

The build toolchain for iOS is broken and we are working on it. You should get a notification to update as soon as we push a new release and Apple approves it. We have not made any changes to value map relations. This release is mainly a bug fix with a couple of new features:
https://github.com/lutraconsulting/input/releases/tag/0.6.4

**Comment by Mikester-Calgary** [comment]
Oh that’s too bad.  Had me excited there for a second.  I saw all that on a develop list somewhere I guess I thought it was done!Thanks Sab.m Sent from Mail for Windows 10 From: SabSent: July 15, 2020 8:16 AMTo: lutraconsulting/inputCc: Mikester-Calgary; MentionSubject: Re: [lutraconsulting/input] iPhone now rotating photos captured in Input (#760) HiThe build toolchain for iOS is broken and we are working on it. You should get a notification to update as soon as we push a new release and Apple approves it. We have not made any changes to value map relations. This release is mainly a bug fix with a couple of new features:https://github.com/lutraconsulting/input/releases/tag/0.6.4—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by saberraz** [comment]
We are working on the attribute table for version 0.7:
https://github.com/lutraconsulting/input/projects/5

**Comment by Mikester-Calgary** [comment]
Thanks Sab.Any idea when that might be released?I have an application that will require exactly that utility and I would hate to have to go to a lesser data capture app in the short term.Please let me know if you have any idea.m Sent from Mail for Windows 10 From: SabSent: July 15, 2020 8:59 AMTo: lutraconsulting/inputCc: Mikester-Calgary; MentionSubject: Re: [lutraconsulting/input] iPhone now rotating photos captured in Input (#760) We are working on the attribute table for version 0.7:https://github.com/lutraconsulting/input/projects/5—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by saberraz** [comment]
We are aiming for the 2nd half of August to have attribute table completed.

**Comment by Mikester-Calgary** [comment]
Not to be a dick Sab but is this still on target for end of August here?
The beta runs beautifully!  I have encountered no problems.

m

**Comment by Mikester-Calgary** [comment]
Sab:

Is there a new beta release for the Input app we can try?

 

Also, how can I get on the beta team for the QGIS Point Cloud extension?

 

Hope your are well.

Mike

**Comment by wonder-sk** [comment]
> Is there a new beta release for the Input app we can try?

0.6.4 is currently the most recent beta. The version 0.7 will be released sometime soon (maybe ~2 weeks)

> Also, how can I get on the beta team for the QGIS Point Cloud extension?

There will be no special beta team for point clouds in QGIS - as soon as some pieces of the work will land in QGIS source code, it will be available for everyone in QGIS development nightly builds...
