### ISSUE TITLE
Incorect modified time

### ISSUE THREAD

**Issue by PachKosti** [lutraconsulting/input#762]
Related to https://gitlab.cloud.lutraconsulting.co.uk/mergin/mergin/-/issues/338
Probably set bad time zone during upload, should be converted to UTC

**Comment by wonder-sk** [comment]
From the code it seems Input already _does_ send modified time in UTC... so if time is incorrect, it may be due to user's bad date/time settings.

**Comment by saberraz** [comment]
Closed on Mergin
