### ISSUE TITLE
Custom DateTime field displays only 1st selected features value 

### ISSUE THREAD

**Issue by diethard2** [lutraconsulting/input#773]
I did include a custom DateTime field with following format: dd-MM-yyyy HH:mm:ss.

The datetime value is displayed correctly in the Input app for the first feature selected in the map. However the contents of this datetime field remains the same when you select another features that has a different datetime value.

When inserting a new record I use the following expression for the default value for the DateTime field and that seems to work fine: 
format_date( now(), 'yyyy-MM-dd hh:MM:ss')

The problems occurs on an Iphone 5s with ios 12.4.6 installed and an Iphone 7

For me it was OK to hide de field by removing the field from the form I created using the Drag and Drop designer.

**Comment by saberraz** [comment]
This issue and https://github.com/lutraconsulting/input/issues/558 can be resolved in one go!

**Comment by saberraz** [comment]
This has been fixed in 0.7.1. Please test and reopen if you any issues.
