### ISSUE TITLE
Generated XYZ tiles (MBTiles) display on Android but not on Iphone 

### ISSUE THREAD

**Issue by diethard2** [lutraconsulting/input#774]
MBTiles where not displayed as background map on Iphone 5s an Iphone 7. I followed instructions carefully, when I configured an offline theme. On my iphones it did not display but I was surprised when on a friends Android phone the offline theme worked great for the same project.

**Comment by saberraz** [comment]
Hi @diethard2 

What version of QGIS are you using? This is likely to be related to:
https://github.com/lutraconsulting/input/issues/440#issuecomment-626029545

**Comment by diethard2** [comment]
For this project I used QGIS LTR version 3.10.7. Do I understand that when
I Install a more recent version than 3.12 and load and save the project,
the problem is solved? Can I use QGIS Pi?

Op za 27 jun. 2020 om 18:36 schreef Sab <notifications@github.com>:

**Comment by diethard2** [comment]
Openen QGIS project in 3.14.0, saved synchronized it and downloaded it in Input. On iOS unfortunately still no background map.

**Comment by saberraz** [comment]
Hi @diethard2 

Could you see if you can open the MBTiles here:
In Input > Projects > Explore and download saber\test_mbtiles_raster

**Comment by diethard2** [comment]
Got it! Works indeed if you add the mbtiles using the browser! Before I used indeed the Data Source Manager!

**Comment by saberraz** [comment]
In a separate matter, you can use Vector tiles, they are much nicer to display :)
https://twitter.com/lutraconsulting/status/1275115535391432710

**Comment by diethard2** [comment]
Great! I will try in a future release of the project. Thanks a lot Saber!

**Comment by saberraz** [comment]
OK...I leave this issue open to remind us to fix the upstream problem in QGIS: https://github.com/qgis/QGIS/issues/36312
