### ISSUE TITLE
Input cannot open jpg rasters

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#777]
or TIF with jpeg compression in iOS only. Works fine in Android.
see saber/test_jpg project.

**Comment by saberraz** [comment]
Workaround: Using Translate algorithm under QGIS processing toolbox, you can translate your raster to TIF with HIGH Compression.

**Comment by PeterPetrik** [comment]
most likely missing GDAL driver in https://github.com/lutraconsulting/input-sdk/blob/02d8d65d57e9788537a87c154be6616b9f3ecc00/ios/recipes/gdal/recipe.sh#L72

**Comment by saberraz** [comment]
See https://github.com/lutraconsulting/input-sdk/issues/35
