### ISSUE TITLE
Conflict file created for no apparent reason

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#778]
Please PM me for the mergin project name (@saberraz - you have access already - this is the one we spoke about this morning).

Conflict appeared in v12 of the project - can we determine why this occurred and fix?

Pete

**Comment by PeterPetrik** [comment]
very likely https://github.com/lutraconsulting/geodiff/issues/62 fixed on Android, iOS fixed too, but not released yet
