### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#784]
- add search bar similiar to project list search
- emits signal on text change ( after ~200ms )
- handle signal in BE

**Comment by saberraz** [comment]
How are we handling showing the matching records? It will be confusing for users if they search for "ABD" and they just see a bunch of FID and Description.

**Comment by tomasMizera** [comment]
@saberraz it will be implemented here #795. 

> - add found attribute with its value to features description text

So we will add that "ABD" together with attribute name to description text
