### ISSUE TITLE
Deleting feature deletes two!

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#786]
Deleting a feature deletes two features! (one later reported)

<img src="https://user-images.githubusercontent.com/22449698/86600670-a6a93100-bfa0-11ea-918d-1b3fd2d20fe5.gif" width="190" />

Tested on [current master](https://github.com/lutraconsulting/input/commit/4e26c4a89c7bf34a8ff2bc38112940aaa62eec73)

**Comment by edips** [comment]
Yes when the objects are very close, it deletes two objects.

**Comment by wonder-sk** [comment]
Already fixed in #786
