### ISSUE TITLE
Inconsistent layer visibility between QGIS and Input when there is a map theme

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#789]
See:
saber/map_theme_bug

Image from QGIS:
![image](https://user-images.githubusercontent.com/2649047/87336086-3c146a00-c539-11ea-96b4-38abd63225cd.png)

Image from Input:
![Screenshot_20200713-194711_Input](https://user-images.githubusercontent.com/2649047/87336189-5d755600-c539-11ea-88cc-044721007c70.png)

**Comment by saberraz** [comment]
To reproduce:
1- Start QGIS
2- Add a layer to QGIS
3- Add a Map Theme for the added layer
4- Add another layer
5- Save the project and sync it to Input

In QGIS:
It displays map shown in step 4. In Input, it displays map from stage 3.

**Comment by wonder-sk** [comment]
Fixed in #843
