### ISSUE TITLE
Respect QGIS setting for last value entered in attribute table

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#798]
In QGIS > Settings > Options > Digitizing under Feature Creation, there is the option to Reuse last entered attribute values.

By default this option is disabled, but if user has turned it to ON, we should respect it in Input.

**Comment by tosiek12** [comment]
It would be super useful to have this feature - we are doing full inventarization with multiple fields to be filled so setting it in all new point is realy annoing...
It is planned to be done anytime soon? ;)

**Comment by saberraz** [comment]
This should be straight forward to do. If you sign up to our Mergin service, we are happy to include it in the next release (before mid Jan 2021).

**Comment by tosiek12** [comment]
> This should be straight forward to do. If you sign up to our Mergin service, we are happy to include it in the next release (before mid Jan 2021).

Great! ;) We will be doing some more tests before new year so to adjust data model to be user friendly, but for now lack of this functionality seams like show stopper... Account is created with this email antek.trad at gmail.com. ;) so we will be waiting for new release ;)

**Comment by tosiek12** [comment]
> This should be straight forward to do. If you sign up to our Mergin service, we are happy to include it in the next release (before mid Jan 2021).

Any update with this issue? I see #1090 is connected to this one.

**Comment by saberraz** [comment]
we will address both issues in the next release (late jan or early feb).
