### ISSUE TITLE
Change the layout

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#8]
We will need two different layouts:
- phone - portrait only
- tablet - landscape only

The priority is to make the app usable on the phone, then we can focus on tablet.

**Comment by saberraz** [comment]
Currently only landscape is supported

**Comment by wonder-sk** [comment]
We will need two different layouts:
- phone - portrait only
- tablet - landscape only

The priority is to make the app usable on the phone, then we can focus on tablet.

**Comment by sklencar** [comment]
Design change restricted to main toolbar in this phase
- moved to bottom
- proper layout and behavior of buttons
- overflow menu

**Comment by wonder-sk** [comment]
Addressed in #39 and #40
