### ISSUE TITLE
GPS and app in background

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#80]
When the app is in background and no data capturing is in progress, it keeps the GPS on. I have the close the application to stop the GPS usage. This will cause battery drain.

**Comment by wonder-sk** [comment]
Right, we should only keep GPS on in case we are recording.

**Comment by saberraz** [comment]
In the latest version, this bug resurfaced.

**Comment by wonder-sk** [comment]
Confirmed - caused by the fact we currently build Input using a patched version of QGIS 3.4.x while the fix is only available in QGIS 3.6

**Comment by wonder-sk** [comment]
Fixed in the newest build
