### ISSUE TITLE
Cannot sync "Another process is running"

### ISSUE THREAD

**Issue by roya0045** [lutraconsulting/input#816]
Greetings,

We are using an iPhone to do field surveys and we are trying to sync the projects. Currently we are having an issue as we cannot synchronise the data from the phone to the server as it state that there is another process running and that the data could not be updated.

Initially the project shown as updated, which was not the case (possibly related to #563 ) We added a point to force the sync and we are now having an error message when trying to sync. We have restarted the app but it didn't change anything.

Is there a way to safely remove what is blocking the process and perform synchronization or simply retrieve the data from the phone and update the branch from qgis ?

Thanks!

**Comment by saberraz** [comment]
Hi @roya0045 
Could you check what version of Input you are running (... > Settings > About). We have resolved this issue recently

**Comment by roya0045** [comment]
@saberraz 0.4.90

**Comment by saberraz** [comment]
That is way old...could you upgrade please.

**Comment by roya0045** [comment]
That was what we could get on the store, I'll see about an update, Thanks!

**Comment by saberraz** [comment]
I suggest using TestFlight:
https://testflight.apple.com/join/JO5EIywn

Click on the link above from your iPhone and it will guide you through upgrade

**Comment by roya0045** [comment]
@saberraz Updated to 0.6.0 just now, still the same error.

**Comment by saberraz** [comment]
Unfortunately, you might need to wipe the project and redownload the project.

You can back up your data through iTune and USB cable first so you do not lose the changes.

**Comment by roya0045** [comment]
@saberraz is there a documented procedure to make the backup that I could forward to my colleague? I'm not familiar with what is saved on iTune and to either retreive or reupload the project information.

**Comment by saberraz** [comment]
If you connect your iPhone to your computer and open iTune, you should be able to see the storage there:

![image](https://user-images.githubusercontent.com/2649047/88302392-b5604980-ccfd-11ea-8d1d-6e1f8537f70f.png)

**Comment by roya0045** [comment]
@saberraz Thanks, we retrived the info, I'll close the ticket. Thank you for the quick response and help!
