### ISSUE TITLE
Support for staking out points

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#822]
https://en.wikipedia.org/wiki/Construction_surveying#:~:text=Construction%20surveying%20or%20building%20surveying,such%20as%20roads%20or%20buildings.

An example of how it works in other apps:
https://docs.emlid.com/reachrs2/common/reachview/survey/#staking-out-points

**Comment by jancelin** [comment]
The objectives would be:
 * View the quality of GNSS reception (fix, float, single)
 * To select a point to reach.  Have the distance, the line to the point and the direction.
* To have an acquisition of geographic data averaged over X seconds with the acquisition
quality.

An example : 
![Screenshot_20200729-111400](https://user-images.githubusercontent.com/6421175/88781404-a4e02100-d18c-11ea-8d0f-835906d4ee49.png)

**Comment by pchirouze** [comment]
Good idea !

**Comment by jancelin** [comment]
Hi @saberraz,
 I am relaunching the discussion on this subject.
 how is it possible to imagine the development of this feature?

**Comment by saberraz** [comment]
Hi @jancelin 

This is indeed a nice feature. We usually ask for these types of features to be funded. Would you be interested in sponsoring the work? Feel free to drop us an email.

**Comment by saberraz** [comment]
It would be good to display the coordinates in QGIS CRS as well as lat/long
![Screenshot_20211007-121700_UTM_Map](https://user-images.githubusercontent.com/2649047/136356981-9b193b34-d7e4-4357-b798-8ac9ba889570.png)

**Comment by saberraz** [comment]
Here is my proposed workflow:

1- User selects an existing point on the map (we will only support Point layer)
2- The preview panel comes with an extra option: Navigate to: (DISPLAY NAME of)  the feature
![Untitled-2021-11-12-0848(1)](https://user-images.githubusercontent.com/2649047/141431648-926170db-670c-4934-95f3-726cc514f3bf.png)

**Comment by wonder-sk** [comment]
Few notes from brainstorming:
- auto-zooming / auto-panning can be disabled if user manually moves/zooms map - in such situation we would show a button to re-center which will enable auto-zooming / auto-panning again
- when stake out mode is closed, we show the preview panel, and if the point is outside of the current map view, we will re-center
- it may be useful to show the feature title when in stake out mode
- icon to enter stake out to be picked
- accuracy will be shown in the "bubble" as it is now (not inside the panel)

**Comment by tomasMizera** [comment]
Now fully implemented in latest master: https://github.com/lutraconsulting/input/commit/845ce3aeb371b962579cc32eaafe8adc1708bd7f
