### ISSUE TITLE
Input app doesn't see my Mergin project

### ISSUE THREAD

**Issue by ludwa6** [lutraconsulting/input#837]
Following [this excellent tutorial](https://www.youtube.com/watch?v=8AZ9gPAhL_4), i have created in QGIS a public project called "Crop mapping", which i have uploaded & sync'd to my Mergin account ("walt") -and it appears there as it should. It is 18.62 mb -which still only brings my total uploads to ~25mb, well within the 100mb limit imposed on free accounts. 

So: i can't understand why, logged into this same Mergin account via input app (version 0.6.0, what i just downloaded) on my iPhone, this "Crop mapping" project does not appear. Neither is it accessible through the "Explore" feature, though access is. set to "Public."  Looking into [Project Settings ](https://public.cloudmergin.com/projects/walt/Crop%20mapping/settings)via web interface, it shows that my user account is listed as Owner with Write privileges enabled.

I can't think of anything that would account for this discrepancy in views of the same account between Mergin web and Input app, so it looks to me like a bug. Would greatly appreciate any help in getting this one sorted!

**Comment by saberraz** [comment]
Hi @ludwa6 

I can see your project under Explore:
![IMG_0552](https://user-images.githubusercontent.com/2649047/90984216-855dcd80-e56b-11ea-828a-81ca96c11fdb.PNG)

**Comment by ludwa6** [comment]
Right you are, @saberraz !  It just took a **very** long time to show up in the app... But, better late than never; i'll just have to learn to be more patient.  Thanks for the heads-up, mate!
