### ISSUE TITLE
When taking photos allow for setting size + quality

### ISSUE THREAD

**Issue by ghillert** [lutraconsulting/input#841]
As we now have phone cameras with almost 50 mega pixel resolution, it is super important to have the option to minimize file-sizes (No desire to synch up gigabyte-sized Input-projects with QGIS). As a work-around I am using the OSS project [Open Camera](https://opencamera.org.uk/). Nonetheless, it would be cool if Input had some support for keeping image files small.

**Comment by saberraz** [comment]
Input now supports native camera. I believe if you set the picture settings from the main camera app, it should be applied in Input when taking photos.

**Comment by ghillert** [comment]
The native camera is very limited for that purpose. On my phone I only have the option to limit the resolution to either 48 Mega Pixel or 12 Mega Pixel. That is too large for my purpose. Is there maybe a way to delegate to a 3rd party app to take pictures? E.g. **Open Camera** https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en_US&gl=US

**Comment by saberraz** [comment]
You can reset your mobile default app settings for camera. When you are presented to take a photo, you can then select OpenCamera or other camera apps installed on your Android. Note that Google has removed this option (you are forced to use the stock camera as the default camera app) from Android 11+

**Comment by fabionardini** [comment]
On iOS would be nice to resize the photo while taking thru input app. As ghillert said the native camera size is very limited also on iOS.

**Comment by saberraz** [comment]
The proposed solution which we will be working on, is to have a setting in Input to allow photo resolution to be set to low, medium and high.

**Comment by fivkl** [comment]
This feature will essentially make or break our project as we will need many thousands of photos uploaded by volunteers, so we need it to be instinctive within Input. Are you able to update when this feature will be released please? Many thanks.

**Comment by PeterPetrik** [comment]
we are doing small voting now on our community slack: https://merginmaps.slack.com/archives/C02DWECUEN8/p1649149902616039

**Comment by fivkl** [comment]
Thanks Peter, good to know.
Do you think it stands a good chance?
