### ISSUE TITLE
Add ability to add images to dedicated directory

### ISSUE THREAD

**Issue by ghillert** [lutraconsulting/input#842]
It looks like that images added e.g. via `Add from gallery` (On Android) are stored in the project's root directory. It would be nice if images could be stored in a dedicated `default` directory, e.g. `images`. I was under the impression that that would be possible by specifying a `default path` under the `Attachment` _Widget Type_ on the _Attributes form_ but that does not seem to work.

![image](https://user-images.githubusercontent.com/685363/91156697-262db500-e660-11ea-844f-6af6876c5b03.png)

**Comment by saberraz** [comment]
How about if you set it to something like this:
@project_folder + '/images'

![image](https://user-images.githubusercontent.com/2649047/91158418-83f0ea00-e6be-11ea-8409-de51201c04e0.png)
