### ISSUE TITLE
Amend line geometry or add photos before creating line geometry 

### ISSUE THREAD

**Issue by ashhartuk** [lutraconsulting/input#849]
Hi, 

Is there a timeline to enable changing of line geometry please. We often need to survey unknown length of path, sometimes for 1km and need to capture images as we walk. Currently we have to create line geometry before adding images to the record.

**Comment by saberraz** [comment]
Having https://github.com/lutraconsulting/input/issues/500 should address your issue.

**Comment by tomasMizera** [comment]
Hi @ashhartuk, this is already implemented, you can change the geometry of existing lines.
