### ISSUE TITLE
Input should add more details when reporting not enough space

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#853]
If users try to upload more data than their quota allows, they get a warning - but without any further details.

Input should tell them what is their quota size, and how much data are in their project, possibly with instructions how to get the quota increased...

**Comment by jozef-budac** [comment]
@wonder-sk do you think all details are present now?

![screenshot_20211108-123539](https://user-images.githubusercontent.com/83582181/140735789-b110afd2-efb1-4aae-bc56-50564cfcee84.png)

**Comment by wonder-sk** [comment]
looking good - is this a mockup or is it actually in the app already? :-)  ... wondering about the zero usage and zero data in the free plan

**Comment by jozef-budac** [comment]
This is already in the app. This zero plan was manually changed in admin to simulate data reach limit. So it is correct.
If you think this is sufficient, this ticket can be closed :)
