### ISSUE TITLE
Write EXIF metadata to images created from camera

### ISSUE THREAD

**Issue by roya0045** [lutraconsulting/input#872]
Greetings,

We took some images with an iPhone and noticed that after the extraction of the images (to limit data usage of the project), the EXIF geolocation attributes were not added to the images as opposed to images taken with the default photography application.

It would be appreciated if the images would also have such element as geolocation metadata to use as a standalone file to be shared.

Though this currently seems to rely on qtextended. https://forum.qt.io/topic/84097/qimagewriter-and-exif/3

**Comment by saberraz** [comment]
Fixed in Android. iOS coming soon.

**Comment by roya0045** [comment]
@saberraz Great! Thanks a ton!

**Comment by saberraz** [comment]
This is still not completely addressed. iOS does not write the exif data from native camera.

**Comment by saberraz** [comment]
Not yet! :)

**Comment by PeterPetrik** [comment]
released in 0.9.3
