### ISSUE TITLE
WFS with VPN connection

### ISSUE THREAD

**Issue by gregrz** [lutraconsulting/input#880]
When working with a project, which contains a WFS only available via VPN, all layers show correctly within QGIS Desktop. Synced to the mobile device via Mergin, however, the WFS layers requiring a VPN connection do not appear despite the mobile VPN being active. Could this have something to do with Mergin being between client and host? (Mobile system iPadOS 13.6)

**Comment by wonder-sk** [comment]
I think we currently do not build WFS data provider for the iPhone/iPad version of Input. It could be added, but this will require some updates in the QGIS source code first in order to be able to have it available in Input. (Android version should work though)

**Comment by gregrz** [comment]
Ok, thanks! Future availability for iPadOS/iOS highly appreciated.

**Comment by saberraz** [comment]
See https://github.com/lutraconsulting/input-sdk/issues/36
