### ISSUE TITLE
Unfinished project download may leave incomplete directory

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#884]
Download of a project may get interrupted, even without getting a signal about the failure of a request.

This will leave a half-populated directory and may cause further trouble later.

We should have a mechanism that will ensure that half-downloaded projects are never shown in the list - and any half-downloaded project data get pruned. For example, we could download to a dir with a special prefix, and directories with such prefix would be never shown (+would get deleted when Input starts)

TODO: find out when exactly this happens (app gets to background? app is forcefully quit?)

**Comment by tomasMizera** [comment]
<img src="https://user-images.githubusercontent.com/22449698/94915228-ca4f1b00-04ac-11eb-811b-6cb2dc11e19f.jpg" width=250>

**Comment by tomasMizera** [comment]
Upon investigating I found out that failed download (only when application quits) keeps the directory. When opening app again it lists the project with error. Next time trying to download creates **new** directory with 0,1,2... at the end based on how many times it failed already.
