### ISSUE TITLE
Unique user for testing

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#902]
This is a suggestion and topic to discuss rather than reporting a bug.

While running automatic tests against deployed test.dev server with the same user, it might happen (with small but existing probability) that sets of tests running in parallel cause inconsistent state in DB for the user which can result into failing tests.
To avoid such coincidence and confusion it would be good to have a unique user for each set of tests.

**Comment by tomasMizera** [comment]
+1 This would also make the test runs independent regarding to server purchasing history
