### ISSUE TITLE
Show a warning if a local project is not available in Mergin anymore

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#903]
If user deletes or transfers a project, Input lets them do any changes to such a project, but then they won't be able to sync their changes back. Ideally there should be a warning somewhere that a project is not available anymore.

**Comment by saberraz** [comment]
Related to https://github.com/lutraconsulting/input/issues/614

**Comment by tomasMizera** [comment]
Isn't this the same as #1008 ?

**Comment by wonder-sk** [comment]
Looks like it is :-)
