### ISSUE TITLE
Instant crash when opening projects on iOS

### ISSUE THREAD

**Issue by she-weeds** [lutraconsulting/input#912]
I'm not sure if this is specifically related to my device, but I've decided to resume testing Input after last using it in March. I can't open a single project on Input 0.6.0 on iOS (iPhone 8, iOS 14.0.1) without it instantly crashing, regardless of the project contents. I've tried the following to no avail:

* restarting the phone, 
* signing in/signing off my account, 
* using a new account
* creating a project on the server and not via Mergin plugin
* uninstalling/reinstalling Input
* turning airplane mode on/off 
* creating qgs project in 3.12 rather than 3.14
* using qgz rather than qgs
* using the most basic of forms and projects (single shapefile with one column text input)

Yet the exact same projects work on Input 0.6.4 for Android. I am also able to login and sync projects without any issue on iOS.

Any tips on how to further troubleshoot this would be much appreciated.

**Comment by saberraz** [comment]
Hi @she-weeds 
Could you maybe upgrade to the TestFlight version of Input (click on the link below from your iPad/iPhone):
https://testflight.apple.com/join/JO5EIywn

**Comment by she-weeds** [comment]
Hi, apologies for the late reply. I have just tried out the TestFlight version (0.6.4) and it works fine now as far as I can tell. Can open project, digitise, edit, delete, and changes are successfully synced back using Mergin. 

Any chance of knowing when the updates from this version will be pushed out to general release soon? I'd like to know when I can get my colleagues to test it out. Thanks.
