### ISSUE TITLE
Default value not calculated from other fields on insert

### ISSUE THREAD

**Issue by she-weeds** [lutraconsulting/input#921]
I'm aware default values have been addressed in #296 and #315 but I am still running into an issue with default values that are calculated from other fields - somehow I swear this worked in earlier versions but I can't check that out any more.

Let's say I have a numeric column `"basefield"` and another column called `"calcfield"` with a default value expression (`"basefield"*0.12`) and 'Apply default value on update' checked.

Now in QGIS, whenever I enter a value in `"basefield"` I automatically see the calculated value in `"calcfield"` in the form itself as below with "dbh_cm" and "tpz_rad_m".

![default_value](https://user-images.githubusercontent.com/41975056/95670832-046e9a00-0bdc-11eb-8792-2a5e02fa99d6.gif)

In Input, I can't see the data automatically update in the form (which is fine - although very nice to have). 

But more crucially, the form does not save the calculated value after initial insert. It remains null. Only when the feature is edited does it seem to apply the calculated value (and from then on continues to apply calculated values appropriately if the base value is changed).

This is the case even if I use `current_value()` in the default value expression (e.g. `coalesce(current_value('basefield'),"basefield")`).

Note this isn't an issue if the default value expression refers to a variable, static value or an aggregate expression (e.g. auto increment expression like `maximum("id")+1`)

Using Input 0.6.4 on iOS via Testflight, QGIS 3.14.16

edit: This is also a known issue in [Qfield](https://github.com/opengisch/QField/issues/914) fwiw.

**Comment by saberraz** [comment]
This works for me on Input 0.7.1. Please update and reopen if you still have issues.
