### ISSUE TITLE
Cover mergin functions used in frontend

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#930]
This issue is mostly about back-compatibility. 
`MerginApi::hasWriteAccess` is a function of MerginApi, which is used only in QML to check user permission before any (sync) request is done. Since server has changed, this function is not compatible anymore for older version of Input (<= 0.6.4) and new mergin server (version from October 2020). However, there is no test to check this compatibility with older versions.

Writing this issue just for reference for further discussion.

**Comment by wonder-sk** [comment]
Mergin server is now compatible again :-)

But yes, we need to add checks to this function in input test suite to make sure it always works

**Comment by tomasMizera** [comment]
Check is no longer done in QML, closing
