### ISSUE TITLE
Subscription plan does not appear under Settings

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#936]
I am not sure if this is due to using **test** account for subscription or it is a bug. But, when I subscribe to Mergin, the subscription is not listed under my profile on my device, according to [this](https://support.apple.com/en-gb/HT202039#:~:text=Tap%20your%20name.,to%20Subscriptions%20and%20tap%20Subscriptions.)

**Comment by PeterPetrik** [comment]
on device on  "My Account" you should see the subscribtion plan you have purchased. Only you cannot manage it through mergin web or app, needs to be done directly via Apple Management panel

**Comment by saberraz** [comment]
It works fine!
