### ISSUE TITLE
Better handling of permissions

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#953]
Tested on Android

When user do not allow permissions, these things happen:

- **provided location and storage, but not camera:** 
experienced: application stops when user clicks on _take a photo_ inside feature form
expected?: we should opt for permission again or notify user to provide camera permission in settings
Fixed in #1081 

- **provided location and camera, but not storage:** 
experienced: no projects are in the _Home_ project list, text says that "no downloaded project found" and leads user to a tutorial how to download or create new project. However when user downloads project without **storage permission**, project is grayed and has error "Failed to find a QGIS project file"
expected?: we should either add to text that user should check permissions in settings (we might add a link to settings) or mention this problem in _help.inputapp.io_. However, probably the best would be to opt for this permission again.
Resolved in #1084 

- **provided camera and storage, but not location:**
**critical**, happens when user clicks on _deny and never ask again_
experienced: no buttons are clickable! user is stuck in home page or active project, app is terribly slow
expected?: app works normally, but GPS button is disabled (red now)

- **no permissions allowed:**
experienced: total mess, app is slow, almost all buttons are not working, unusable
expected?: prompt user that to run this application we need specific permissions and lead him to settings

- **provided location, but not camera and storage:**
experienced: the same as if only storage was not provided

Expected scenarios are up for discussion, these are just what I would expect from an app to do.

**Comment by saberraz** [comment]
Reported by user: Input crashes upon opening a project when location is not available or turned off by user.

**Comment by PeterPetrik** [comment]
I think that androidutils & iosutils should be just probably internal implementions for inpututils (or new class platform utils) where the interface will be clear and would provide the functions like
```
enum PermissionType{
camera,
location,
storage
}

- getPermission(PermissionType type)
- hasPermission(PermissionType type)
- getPhoto(..)
- ...
```

**Comment by PeterPetrik** [comment]
for location: https://github.com/lutraconsulting/input/issues/1057

**Comment by tomasMizera** [comment]
Camera permission crash sorted in #1081

**Comment by tomasMizera** [comment]
Storage permission #1084
