### ISSUE TITLE
Loading WFS: not reloading after loading project

### ISSUE THREAD

**Issue by Oostjoost** [lutraconsulting/input#960]
I want to edit WFS-T so changes are automatically stored in the PostGis database via GeoServer. For visualisation I then use the WMS layer. The Input app recognises the WFS as a Vector layer and I can capture new geometries.

The problem is when I am zooming or panning the points of the WFS layer dissapear and clicking on the points isn't recognised for editing the feature.

I think after loading the project the WFS layer isn't reloaded. But possible it is an other issue.

All the layers are in the same coordinate system.

**Comment by saberraz** [comment]
This could be related to how QGIS handles WFS caching of the data.

**Comment by Oostjoost** [comment]
When I set the rendering interval within de layers properties in Qgis to for example 5 sec, then everything works fine. I would think that panning and zooming would trigger this action as well.

**Comment by saberraz** [comment]
Does it resolve the issue in Input as well?

**Comment by Oostjoost** [comment]
It's a workaround but not how I expect it to work. For example in QField it does work and I thought both apps use the same code-base. Also in Qgis it's not necessary to make this adjustment for a WFS to render.

**Comment by Oostjoost** [comment]
Thnx for the quick replies, I appreciate that.

**Comment by Oostjoost** [comment]
Is there any perspective when this issue is fixed?

**Comment by saberraz** [comment]
IMO, it is best to avoid WFS as a survey layer. It is a great protocol for publishing data but not probably for live editing.

What I suggest is to have a look at at https://github.com/lutraconsulting/mergin-db-sync

You can set up it so that your PostGIS table will be synced with Mergin. The benefit is that they can edit the data even offline.

**Comment by Oostjoost** [comment]
Very nice and also hilarious. I was building a plugin in QGIS to work with database syncing in the same way from a geopackage. The reasons why I build this is syncing Input GeoPackages to my Postgres DB. I also can see te benefits of offline working.

If I am right your syncing tool can be used with an online database as well and there is no manually action to start the sync?

In QGIS I also use a lot of WFS-T editing of layers, because then I can use GeoServer as an extra Authentication on top of my DB. I am not particullary in favor of directly connecting to a Database.

**Comment by saberraz** [comment]
This is how DB-Sync would work:
![image](https://user-images.githubusercontent.com/2649047/100389887-9284cf80-3026-11eb-8a0e-402a3d2abd4e.png)


- DB-Sync would run as a daemon on your server and get the latest version of files from Mergin 
- Mobile phones would sync directly through Input to Mergin
- You can also change data in QGIS to your project and sync it through Mergin plugin

Mergin versions the data, so you can track who changes what (to have the change source, you can add a field in PostGIS/Geopackage and set the default value to _@mergin_username_) (see project history in your Mergin project).

- No direct connection to PostGIS from any device/user
- All the connection information are stored on DB-Sync which runs on your server. So, you can expose what to Mergin and accordingly to users.
- Users can do off-line edits
- No need for VPN to access WFS, PostGIS....

**Comment by saberraz** [comment]
I suppose this is now resolved by using db-sync. Feel free to re-open if it is still the case.
