### ISSUE TITLE
Missing language from translations

### ISSUE THREAD

**Issue by berkayoruc** [lutraconsulting/input#962]
How can I change application language? I can't find any documentation.

**Comment by saberraz** [comment]
@berkayoruc Input should pick up the language settings from your device. For example, if your first choice of language on your device is Turkish, Input should defaults to Turkish language. If your system language does not exist amongst the Input translations, it will default to English.

**Comment by berkayoruc** [comment]
My first choice on device is Turkish, but Input lang is English still.

**Comment by saberraz** [comment]
Which version of Input are you using?

**Comment by berkayoruc** [comment]
Now, I downloaded from Turkish pull request.

**Comment by saberraz** [comment]
Hmm...it looks like the Turkish translations are not included. Let me change the ticket title..

**Comment by PeterPetrik** [comment]
PR will just update the ts file (human readable). to be able to use in app, we need to run /scripts/update_qm_translation to generate binary one. Let  me merge the  PR and reacreate the qm file.
we have already submitted 0.7.0, so this translation will appear in 0.7.1

**Comment by berkayoruc** [comment]
Thank you @PeterPetrik

**Comment by PeterPetrik** [comment]
should be fixed by https://github.com/lutraconsulting/input/commit/ecdd43946d397f3fe5fed88226591cfda16f1d65
