### ISSUE TITLE
Value disappears after selecting result from value relation searchbar

### ISSUE THREAD

**Issue by she-weeds** [lutraconsulting/input#973]
First off congrats on the new beta release with such a powerful search bar for value relations. This is hugely welcome, thank you so much!

I've just been testing 0.7.1 out via TestFlight with a value relation from a csv, and when I select an item from using the search bar, the form doesn't retain the value - it disappears after a split second - whereas if I select the item from scrolling down it does. The value is not saved, there is no data in the file itself. This happens regardless of setting constraints on the field.

See screenshot below for example.

[IMG_6147](https://user-images.githubusercontent.com/41975056/97100540-7c62b700-16e8-11eb-9c53-90ecd52035a3.gif)

**Comment by saberraz** [comment]
Could you share your project with me on Mergin? My username is saber.

**Comment by saberraz** [comment]
OK, I managed to replicate the issue:

1- Download lutraconsulting\test_forms from your Input app
2- Add a point
3- In the new form, move to Group2
4- In valuerelation column, search for value25
5- There is no entry selected
6- Note that if you select the value without using search bar, it works fine

**Comment by tomasMizera** [comment]
This issue will be fixed with PR in qgis quick: https://github.com/qgis/QGIS/pull/39721

**Comment by blacktesta** [comment]
I downloaded lutraconsulting\test_forms. Added a point, moved to Group2.
In valuerelation column selected the value without search. It disappeared too. In my other projects the bug is repeated.
Input v0.7.0

**Comment by saberraz** [comment]
Do you mean there was no point after you pressed Save? Or the value did not stay when you moved to Group 2 but the point was captured?

**Comment by blacktesta** [comment]
Point was captured. But when I select a value the field remains empty.

**Comment by saberraz** [comment]
Resolved by https://github.com/lutraconsulting/input/pull/1353
