### ISSUE TITLE
Support for filtering options in value relation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#975]
See:
https://public.cloudmergin.com/projects/Mikester/Phase%201%20Collection/tree

![Sab_test](https://user-images.githubusercontent.com/2649047/97144337-2b8ca600-175c-11eb-8b36-b448da859157.JPG)

**Comment by wonder-sk** [comment]
Duplicate of #740 ?

**Comment by saberraz** [comment]
Indeed...
