### ISSUE TITLE
NTRIP server

### ISSUE THREAD

**Issue by waiotahi** [lutraconsulting/input#986]
I'm wanting to use a GNSS external receiver with Input on iOS. The GNSS receiver allows corrections broadcast over NTRIP/RTCM and we get these through the devices internet/cellular connection. We would connect to GNSS receiver to the iOS device via bluetooth (Receiver is MFi approved) and hopefully connect to Input. The Input 'help' suggests when connecting an external receiver that the iOS device needs to be in airplane mode, but if we use airplane mode we can't connect to the NTRIP server.
Does the airplane mode have to be on for ALL external receivers to connect?

**Comment by saberraz** [comment]
We have not tested the external GPS with iOS yet and it was a comment by an Input user.

I am going to update the documents with more information soon, when I have my external GPS receiver.

**Comment by saberraz** [comment]
@waiotahi I have my external GPS connected to iphone but could not figure out if it is using the internal or external GPS. I suggest to close this and sort out GPS info from this ticket: https://github.com/lutraconsulting/input/issues/552

**Comment by waiotahi** [comment]
This link might be useful https://junipersys.com/support/article/14650

**Comment by waiotahi** [comment]
I have done some testing with the external GNSS receiver using NTRIP corrections and appears to be working fine with the Input app. Receiver is getting corrections via internet / telling me the estimated horizontal error is <20 cm. I set the GPS accuracy threshold within the app to 1m and didn't get the 'low accuracy' error message - so I assume that Input is picking up the external receiver. I do get the low accuracy error message when the external receiver is not connected and accuracy threshold still kept at 1m - I suggest this ticket could be closed

**Comment by saberraz** [comment]
@waiotahi that is a great news. Thanks for testing and reporting back. In future release we will add metadata for GPS accuracy so you can attach them to your data when capturing location.
