### ISSUE TITLE
Application crash on Android while creating  new project

### ISSUE THREAD

**Issue by tomasMizera** [lutraconsulting/input#991]
Latest changes in either QGIS or Input crashes application. It dies in this scenario:

1. open project for the first time
2. hit record
3. try to create first feature

Application is immediately closed with sigseg.

If application is runned again, project is loaded without any problem and features can be recorded too. Only first run crashes.

Tested on Android and desktop build, happens on both. (on desktop dies immediately after hitting record)

**Comment by tomasMizera** [comment]
@sklencar could you please test this on iOS?

**Comment by tomasMizera** [comment]
Will be closed by https://github.com/qgis/QGIS/pull/39960

**Comment by saberraz** [comment]
@tomasMizera I am still experiencing the issue with the latest debug release you passed me.

**Comment by saberraz** [comment]
Seems to be appearing on iOS now #1020
