### ISSUE TITLE
Split search string to words

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input#999]
Currently if user types multiple words, the search is trying to match the whole string to a single attribute. It would be very useful if the search functionality would split the search string into words and then match the words independently (and only features matching all words would show up).

For example - if I have a layer with people and one attribute with first name and another attribute with surname, "jon smi" search would show me a person that has "Jonathan" as first name and "Smith" as surname.

**Comment by tomasMizera** [comment]
PR https://github.com/qgis/QGIS/pull/39959 resolves this issue
